// Portails de randonnée par pays — région « europe »
// Couverture : UE, Balkans, Royaume-Uni, Irlande, Scandinavie, Islande, Féroé, Åland, micro-États,
//   îles anglo-normandes et Man, Moldavie, Biélorussie, Ukraine, Russie européenne, Caucase, Turquie, Chypre.
// Méthode (2026-09-17) :
//   1. Visorando : récupération des points de départ de TOUTES les randonnées publiées (45 056, via l'appel
//      AJAX public de la carte de recherche, bbox monde), puis attribution d'un pays à chaque point par la
//      commune la plus proche (fichiers public/data/communes*.txt du projet). Contrôle croisé avec les pages
//      pays de Visorando dont le titre donne le compte exact quand il est < 20 (Albanie 10, Estonie 6,
//      Jersey 13, Guernesey 3 : identiques). Comptes obtenus (toutes activités) : FR ~35 190, GB ~3 610,
//      DE ~1 500, BE ~1 380, ES ~950, CH ~620, IT ~580, AT ~156, PT ~132 ; ensuite GR 78, LU 70, NO 55,
//      IE 39, AD 33, SI 25… (tous < 100).
//   2. Portails : repérage (recherche web, sites connus), puis vérification de chaque URL par curl (HTML
//      rendu serveur) ou dans un vrai navigateur quand la page est rendue en JavaScript. Les modèles
//      {town}/{lat}/{lon} ont été testés sur un lieu réel (souvent deux, plus un témoin négatif « xyzqwe »
//      qui renvoie 0 résultat). Aucun contrôle anti-robot contourné ; bandeaux cookies non acceptés.
// Limites :
//   - Les portails Outdooractive (alpenvereinaktiv, termeszetjaro.hu, Via Dinarica) acceptent la position
//     dans le fragment d'URL (#zc=zoom,lon,lat) : lecture côté navigateur uniquement, rendu JavaScript.
//   - Beaucoup de portails n'offrent qu'une page nationale (searchByUrl: false).
//   - Pays sans portail utile ou non vérifiable : non listés — GR (visitgreece.gr page randonnée en erreur
//     500, pas de portail public national), MC, VA, BY, UA, RU (pas de portail national vérifiable / contexte).
//   - Aucune donnée n'est récupérée : simple lien « Plus de randonnées ».
module.exports = {
  visorandoCountries: ['FR', 'GB', 'DE', 'BE', 'ES', 'CH', 'IT', 'AT', 'PT'],
  portals: [
    // ---------- Europe de l'Ouest ----------
    { country: 'FR', name: 'Visorando', url: 'https://www.visorando.com/index.php?component=rando&task=searchCircuitV2&loc={town}', searchByUrl: true, official: false,
      verified: 'Annecy : carte de recherche, 103 résultats autour d\'Annecy (Gorges du Fier, Parmelan) (2026-09-17). Plateforme commerciale française de référence',
      source: 'https://www.visorando.com/' },
    { country: 'FR', name: 'Mon GR® (FFRandonnée)', url: 'https://www.mongr.fr/trouver-prochaine-randonnee', searchByUrl: false, official: true,
      verified: 'Page de recherche des GR® de la Fédération française de randonnée ; liste des itinéraires GR (formulaire POST, pas de filtre par URL) (2026-09-17)',
      source: 'https://www.mongr.fr/' },
    { country: 'BE', name: 'Grote Routepaden', url: 'https://www.groteroutepaden.be/nl/search?txtSearch={town}', searchByUrl: true, official: false,
      verified: 'Brugge et Dinant : GR et streekpaden passant par la ville ; témoin « xyzqwe » : 0 (2026-09-17). Association (asbl), recherche du site (itinéraires + articles)',
      source: 'https://www.groteroutepaden.be/' },
    { country: 'NL', name: 'Wandelnet', url: 'https://www.wandelnet.nl/wandelroute-zoeken', searchByUrl: false, official: false,
      verified: 'Moteur de recherche des LAW, streekpaden, NS-wandelingen ; le paramètre de lieu dans l\'URL n\'est pas appliqué (même liste pour Utrecht et Maastricht) (2026-09-17). Fondation nationale',
      source: 'https://www.wandelnet.nl/' },
    { country: 'LU', name: 'Visit Luxembourg – Randonnées', url: 'https://www.visitluxembourg.com/fr/explorer-le-luxembourg/nature-outdoor/randonnees?query={town}', searchByUrl: true, official: true,
      verified: 'Vianden : 206 résultats ; Echternach : 112 (circuits pédestres Echternach, Mullerthal) ; sans filtre : 647 (2026-09-17)',
      source: 'https://www.visitluxembourg.com/fr/randonnee' },
    { country: 'CH', name: 'Suisse Rando', url: 'https://www.schweizer-wanderwege.ch/fr/propositions-de-randonnees/?criteria%5Bfulltext%5D={town}', searchByUrl: true, official: true,
      verified: 'Zermatt : 13 propositions (Zmutt, Gornergrat, Cervin) ; Lausanne : 24 ; témoin « xyzqwe » : 0 (2026-09-17). Fédération Schweizer Wanderwege',
      source: 'https://www.schweizer-wanderwege.ch/fr/propositions-de-randonnees/' },
    { country: 'LI', name: 'Suisse Rando', url: 'https://www.schweizer-wanderwege.ch/fr/propositions-de-randonnees/?criteria%5Bfulltext%5D={town}', searchByUrl: true, official: true,
      verified: 'Vaduz : 3 propositions au Liechtenstein (Principauté de Liechtenstein, Les Walser du Liechtenstein) (2026-09-17). Fédération suisse ; tourismus.li bloqué par un contrôle anti-robot',
      source: 'https://www.schweizer-wanderwege.ch/fr/propositions-de-randonnees/' },
    { country: 'DE', name: 'Wanderbares Deutschland', url: 'https://www.wanderbares-deutschland.de/suche?search={town}', searchByUrl: true, official: true,
      verified: 'Heidelberg : 7 itinéraires (Neckarsteig, Burgensteig) ; Oberstdorf : 4 ; témoin « xyzqwe » : 0 (2026-09-17). Deutscher Wanderverband',
      source: 'https://www.wanderbares-deutschland.de/' },
    { country: 'DE', name: 'alpenvereinaktiv.com', url: 'https://www.alpenvereinaktiv.com/de/touren/#cat=Wanderung&zc=11.,{lon},{lat}', searchByUrl: true, official: true,
      verified: 'Garmisch-Partenkirchen : randonnées recommandées autour (Gaistal, Leutasch, Pleisenhütte, côté autrichien de la frontière) (2026-09-17). DAV/ÖAV/AVS ; surtout utile en zone alpine',
      source: 'https://www.alpenvereinaktiv.com/de/touren/' },
    { country: 'AT', name: 'alpenvereinaktiv.com', url: 'https://www.alpenvereinaktiv.com/de/touren/#cat=Wanderung&zc=11.,{lon},{lat}', searchByUrl: true, official: true,
      verified: 'Innsbruck : randonnées recommandées des Alpes de Tux (Lizumer Hütte, Torjoch, Ramsjoch) (2026-09-17). Österreichischer Alpenverein / DAV / AVS',
      source: 'https://www.alpenvereinaktiv.com/de/touren/' },
    // URL : https://infomont.cai.it/ redirige (HTTP 3xx) vers la carte https://1.osm2cai.cai.it/?layer=4 — adresse finale
    // reprise directement (constat du 11e audit, 2026-09-19 : data/hiking.json avait été corrigé à la main, ici reporté).
    { country: 'IT', name: 'Infomont – CAI', url: 'https://1.osm2cai.cai.it/?layer=4', searchByUrl: false, official: true,
      verified: 'Catasto digitale CAI (« APP del sentierista ») : carte et liste de 10 000 sentiers (2026-09-17 ; redirection de infomont.cai.it vérifiée le 2026-09-19). Pas de position dans l\'URL',
      source: 'https://www.cai.it/sentieri-e-rifugi/infomont/' },
    { country: 'ES', name: 'Mi Senda FEDME', url: 'https://misendafedme.es/buscador-de-senderos/', searchByUrl: false, official: true,
      verified: 'Buscador de senderos GR®, PR®, SL® homologués (localité, communauté autonome) ; formulaire POST (2026-09-17)',
      source: 'https://misendafedme.es/' },
    { country: 'PT', name: 'Natural.pt – Percursos', url: 'https://natural.pt/pathways', searchByUrl: false, official: true,
      verified: 'Liste des parcours pédestres des aires protégées (ICNF) ; le paramètre search n\'est pas appliqué (2026-09-17). visitportugal.com bloqué par un contrôle anti-robot',
      source: 'https://natural.pt/' },
    { country: 'AD', name: 'Visit Andorra – Hiking', url: 'https://visitandorra.com/en/nature--sports/hiking/', searchByUrl: false, official: true,
      verified: 'Page nationale : GRP, GR, sentiers par niveau (2026-09-17)',
      source: 'https://visitandorra.com/' },
    { country: 'SM', name: 'Visit San Marino – Sentieri', url: 'https://www.visitsanmarino.com/pub2/VisitSM/contenuto/Vivi/Itinerari-naturalistici.html', searchByUrl: false, official: true,
      verified: 'Liste des itinéraires naturalistes : Sentiero della Rupe, Canepa, Gessi di Montegiardino… (2026-09-17)',
      source: 'https://www.visitsanmarino.com/' },
    { country: 'MT', name: 'Visit Malta – Walks', url: 'https://www.visitmalta.com/en/hikes-and-walks-malta-gozo/', searchByUrl: false, official: true,
      verified: 'Liste des balades recommandées (Żurrieq, Baħrija, Watch Towers Walk…) (2026-09-17)',
      source: 'https://www.visitmalta.com/' },
    { country: 'GI', name: 'Gibraltar Nature Reserve', url: 'https://naturereserve.gi/discover-trails/', searchByUrl: false, official: true,
      verified: 'Sentiers de l\'Upper Rock (Mediterranean Steps, Nature Lover, Monkey Trail…) (2026-09-17)',
      source: 'https://naturereserve.gi/' },

    // ---------- Îles britanniques ----------
    { country: 'GB', name: 'National Trails', url: 'https://www.nationaltrail.co.uk/', searchByUrl: false, official: true,
      verified: 'Sentiers nationaux d\'Angleterre et du pays de Galles (Pennine Way, South West Coast Path, Offa\'s Dyke…) avec filtres (2026-09-17)',
      source: 'https://www.nationaltrail.co.uk/' },
    { country: 'GB', name: 'Ramblers – Routes', url: 'https://www.ramblers.org.uk/go-walking/routes', searchByUrl: false, official: false,
      verified: 'Bibliothèque de plus de 4 000 itinéraires (Angleterre, Écosse, pays de Galles) ; recherche par lieu non reflétée dans l\'URL (2026-09-17). Association caritative',
      source: 'https://www.ramblers.org.uk/' },
    { country: 'IE', name: 'Sport Ireland Trails', url: 'https://www.sportireland.ie/outdoors/walking/trails', searchByUrl: false, official: true,
      verified: 'Liste de plus de 1 000 sentiers balisés (filtres comté, format, niveau) ; le filtre par nom ne couvre pas les villes (2026-09-17)',
      source: 'https://www.sportireland.ie/outdoors/find-your-trails' },
    { country: 'IM', name: 'Visit Isle of Man – Walks', url: 'https://www.visitisleofman.com/see-and-do/active-and-adventure/walking-and-hiking/self-guided-walks', searchByUrl: false, official: true,
      verified: 'Balades autoguidées, Raad ny Foillan et sentiers patrimoniaux (2026-09-17)',
      source: 'https://www.visitisleofman.com/' },
    { country: 'JE', name: 'Visit Jersey – Walking', url: 'https://www.jersey.com/things-to-do/attractions/scenic-walking-routes/', searchByUrl: false, official: true,
      verified: 'Zones et itinéraires de marche (Jersey Tidal Trail, côtes nord/sud/est/ouest) (2026-09-17)',
      source: 'https://www.jersey.com/holidays/active/walking/' },
    { country: 'GG', name: 'Visit Guernsey – Hiking Routes', url: 'https://www.visitguernsey.com/experiences/hiking/hiking-routes/', searchByUrl: false, official: true,
      verified: 'Itinéraires autoguidés sur les cinq îles du bailliage (2026-09-17)',
      source: 'https://www.visitguernsey.com/experiences/hiking/' },

    // ---------- Nord ----------
    { country: 'NO', name: 'UT.no', url: 'https://ut.no/utforsker/norge/turforslag', searchByUrl: false, official: false,
      verified: '15 898 suggestions de randonnées pour toute la Norvège ; le paramètre de recherche de l\'URL n\'est pas pris en compte (2026-09-17). DNT (association nationale de tourisme)',
      source: 'https://ut.no/' },
    { country: 'SE', name: 'Naturkartan – Trails', url: 'https://www.naturkartan.se/en/explore?category=7,31,33', searchByUrl: false, official: false,
      verified: 'Carte des sentiers de toute la Suède (grappes par région) ; position non stockée dans l\'URL (2026-09-17). Outdoormap AB, utilisé par communes et comtés',
      source: 'https://www.naturkartan.se/' },
    { country: 'FI', name: 'Luontoon.fi', url: 'https://www.luontoon.fi/fi/lajit/retkeily-ja-ulkoilu/kartta', searchByUrl: false, official: true,
      verified: 'Carte et liste des destinations et sentiers (197 destinations : parcs nationaux, longueurs des sentiers) (2026-09-17). Metsähallitus',
      source: 'https://www.luontoon.fi/fi' },
    { country: 'AX', name: 'Visit Åland – Hiking', url: 'https://visitaland.com/en/experience/outdoor/hiking-in-aland/', searchByUrl: false, official: true,
      verified: 'Trois grands itinéraires (10 à 80 km) et 40 sentiers nature (2026-09-17)',
      source: 'https://visitaland.com/en/' },
    { country: 'DK', name: 'Udinaturen.dk', url: 'https://udinaturen.dk/kort/', searchByUrl: false, official: true,
      verified: 'Carte nationale des itinéraires et équipements nature (choix de région, filtre « Gå eller vandre », recherche libre) (2026-09-17). Miljøstyrelsen',
      source: 'https://udinaturen.dk/' },
    { country: 'IS', name: 'Ferðafélag Íslands – Trails', url: 'https://www.fi.is/en/hiking-trails/trails', searchByUrl: false, official: false,
      verified: 'Liste des grands sentiers (Laugavegur, Fimmvörðuháls, Hornstrandir…) par région (2026-09-17). Association (Iceland Touring Association)',
      source: 'https://www.fi.is/en' },
    { country: 'FO', name: 'Visit Faroe Islands – Hiking', url: 'https://visitfaroeislands.com/en/whatson/hiking', searchByUrl: false, official: true,
      verified: 'Carte des randonnées avec filtres région, difficulté, durée (2026-09-17)',
      source: 'https://visitfaroeislands.com/en/see-do/activities/hiking' },
    { country: 'EE', name: 'RMK – Kuhu minna', url: 'https://rmk.ee/looduses-liikumine/kuhu-minna/', searchByUrl: false, official: true,
      verified: '723 lieux (sentiers de randonnée, sentiers d\'étude, aires de loisirs) avec filtres ; paramètre keyword non appliqué côté URL (2026-09-17). Centre de gestion des forêts de l\'État',
      source: 'https://rmk.ee/' },
    { country: 'EE', name: 'Baltic Trails', url: 'https://baltictrails.eu/en/forest', searchByUrl: false, official: false,
      verified: 'Sentier forestier E11 (720 km en Estonie) découpé en étapes d\'environ 20 km (2026-09-17). Projet transfrontalier balte',
      source: 'https://baltictrails.eu/' },
    { country: 'LV', name: 'Baltic Trails', url: 'https://baltictrails.eu/en/forest', searchByUrl: false, official: false,
      verified: 'Mežtaka (674 km en Lettonie) par étapes ; aussi Jūrtaka sur /en/coastal (2026-09-17). Projet transfrontalier balte',
      source: 'https://baltictrails.eu/' },
    { country: 'LT', name: 'Baltic Trails', url: 'https://baltictrails.eu/en/forest', searchByUrl: false, official: false,
      verified: 'Miško takas (747 km en Lituanie) par étapes (2026-09-17). Projet transfrontalier balte',
      source: 'https://baltictrails.eu/' },

    // ---------- Europe centrale ----------
    { country: 'PL', name: 'PTTK – Szlaki turystyczne', url: 'https://szlaki.pttk.pl/', searchByUrl: false, official: true,
      verified: 'Répertoire des sentiers balisés PTTK par voïvodie (liens vers les sites régionaux) (2026-09-17). Site ancien',
      source: 'https://pttk.pl/' },
    { country: 'CZ', name: 'Mapy.com – Turistická', url: 'https://mapy.com/fr/turisticka?x={lon}&y={lat}&z=13', searchByUrl: true, official: false,
      verified: 'Sněžka (Krkonoše) : carte touristique centrée, sentiers balisés KČT visibles (2026-09-17). Commercial (Seznam) mais référence nationale des sentiers KČT',
      source: 'https://mapy.com/' },
    { country: 'SK', name: 'Turistická mapa KST', url: 'https://mapy.kst.sk/#13/{lat}/{lon}', searchByUrl: true, official: true,
      verified: 'Starý Smokovec (Vysoké Tatry) : carte centrée avec les sentiers balisés (2026-09-17). Klub slovenských turistov (Freemap)',
      source: 'https://mapy.kst.sk/' },
    { country: 'HU', name: 'Természetjáró', url: 'https://www.termeszetjaro.hu/hu/tours/#cat=22729870&zc=12.,{lon},{lat}', searchByUrl: true, official: true,
      verified: 'Visegrád : randonnées pédestres autour (Visegrád rejtett ösvényein, Törökmező) (2026-09-17). Magyar Természetjáró Szövetség',
      source: 'https://www.termeszetjaro.hu/' },
    { country: 'SI', name: 'maPZS', url: 'https://mapzs.pzs.si/', searchByUrl: false, official: true,
      verified: 'Application cartographique des sentiers de montagne et de randonnée avec liste filtrable (2026-09-17). Planinska zveza Slovenije',
      source: 'https://pzs.si/' },
    { country: 'HR', name: 'HPS – Registar putova', url: 'https://info.hps.hr/putovi/putovi', searchByUrl: false, official: true,
      verified: 'Registre des sentiers de montagne (nom, club, zone, longueur, durée) (2026-09-17). Hrvatski planinarski savez',
      source: 'https://www.hps.hr/' },

    // ---------- Balkans ----------
    { country: 'BA', name: 'Via Dinarica', url: 'https://trail.viadinarica.com/en/routes/#zc=11.,{lon},{lat}', searchByUrl: true, official: false,
      verified: 'Bjelašnica (Sarajevo) : nombreuses grappes d\'itinéraires sur la carte (2026-09-17). Alliance Via Dinarica (portail Outdooractive)',
      source: 'https://www.viadinarica.com/en/' },
    { country: 'ME', name: 'Via Dinarica', url: 'https://trail.viadinarica.com/en/routes/#zc=11.,{lon},{lat}', searchByUrl: true, official: false,
      verified: 'Žabljak (Durmitor) : grappes d\'itinéraires sur la carte (2026-09-17)',
      source: 'https://www.viadinarica.com/en/' },
    { country: 'ME', name: 'Montenegro – Hiking', url: 'https://www.montenegro.travel/en/explore-montenegro/nature-and-adventure/hiking-and-trekking', searchByUrl: false, official: true,
      verified: 'Page de l\'office national du tourisme : régions de randonnée et parcs nationaux (2026-09-17)',
      source: 'https://www.montenegro.travel/' },
    { country: 'AL', name: 'Via Dinarica', url: 'https://trail.viadinarica.com/en/routes/#zc=11.,{lon},{lat}', searchByUrl: true, official: false,
      verified: 'Theth : grappes d\'itinéraires sur la carte (2026-09-17). peaksofthebalkans.com bloqué par un contrôle anti-robot',
      source: 'https://www.viadinarica.com/en/' },
    { country: 'XK', name: 'Via Dinarica', url: 'https://trail.viadinarica.com/en/routes/#zc=11.,{lon},{lat}', searchByUrl: true, official: false,
      verified: 'Peja / Rugova : grappes d\'itinéraires sur la carte (2026-09-17)',
      source: 'https://www.viadinarica.com/en/' },
    { country: 'RS', name: 'PSS – Planinarski putevi', url: 'https://pss.rs/terrain_register_category/planinarski-putevi/', searchByUrl: false, official: true,
      verified: 'Registre des sentiers de montagne et pédestres (71 pages) (2026-09-17). Planinarski savez Srbije',
      source: 'https://pss.rs/' },
    { country: 'MK', name: 'Via Dinarica', url: 'https://trail.viadinarica.com/en/routes/#zc=11.,{lon},{lat}', searchByUrl: true, official: false,
      verified: 'Mavrovo : quelques itinéraires sur la carte (couverture faible) (2026-09-17). Aucun portail national public trouvé',
      source: 'https://www.viadinarica.com/en/' },
    { country: 'BG', name: 'BG Mountains – Routes', url: 'https://bgmountains.org/en/gps-routes/routes', searchByUrl: false, official: false,
      verified: 'Liste d\'itinéraires GPS par massif (7 pages) (2026-09-17). Projet communautaire, aucun portail public national trouvé',
      source: 'https://bgmountains.org/' },
    { country: 'RO', name: 'Munții Noștri', url: 'https://muntii-nostri.ro/trails/?search={town}', searchByUrl: true, official: false,
      verified: 'Sinaia : 12 itinéraires ; Brașov : 16 (Tâmpa, Pietrele lui Solomon) ; Bușteni avec diacritiques OK ; témoin « xyzqwe » : 0 (2026-09-17). Plateforme nationale dominante, non publique',
      source: 'https://muntii-nostri.ro/' },
    { country: 'MD', name: 'Moldova Travel – Hiking', url: 'https://moldova.travel/en/hiking-trails-in-moldova/', searchByUrl: false, official: false,
      verified: 'Sentiers balisés recommandés (Orheiul Vechi, Stâncile Prutului, Nisporeni) (2026-09-17). Portail touristique national soutenu par USAID ; statut public non confirmé',
      source: 'https://moldova.travel/en/' },

    // ---------- Méditerranée orientale, Caucase ----------
    { country: 'CY', name: 'Visit Cyprus – Nature Trails', url: 'https://www.visitcyprus.com/multimedia/nature-trails-and-hiking-map/', searchByUrl: false, official: true,
      verified: 'Carte et liste des sentiers nature de Chypre (2026-09-17). Deputy Ministry of Tourism',
      source: 'https://www.visitcyprus.com/' },
    { country: 'TR', name: 'Culture Routes in Turkey', url: 'https://cultureroutesinturkey.com/all-routes/', searchByUrl: false, official: false,
      verified: 'Liste des itinéraires de grande randonnée (Lycian Way, Carian Trail, St Paul Trail, Evliya Çelebi…) (2026-09-17). Association, référence des sentiers balisés en Turquie',
      source: 'https://cultureroutesinturkey.com/' },
    { country: 'GE', name: 'APA – Ecotourism Trails', url: 'https://apa.gov.ge/en/eco-tourism/Trails', searchByUrl: false, official: true,
      verified: 'Sentiers des aires protégées (Borjomi-Kharagauli, Lagodekhi, Algeti…) (2026-09-17). Agency of Protected Areas of Georgia',
      source: 'https://apa.gov.ge/en/' },
    { country: 'AM', name: 'HIKEArmenia', url: 'https://hikearmenia.org/all-trails', searchByUrl: false, official: false,
      verified: 'Liste des sentiers (Armenian National Trail, Tatev, Old Khndzoresk…) (2026-09-17). ONG, référence nationale',
      source: 'https://hikearmenia.org/' },
    { country: 'AZ', name: 'Azerbaijan Travel – Hikings', url: 'https://azerbaijan.travel/hikings', searchByUrl: false, official: true,
      verified: 'Liste des randonnées (Azgilli–Chiragli, Azgilli–Javadkhan…) par région (2026-09-17). Azerbaijan Tourism Board',
      source: 'https://azerbaijan.travel/' }
  ]
};
