// Zones rouges / orange France Diplomatie — lot Amériques (consultation du 16/09/2026).
// Sources : https://www.diplomatie.gouv.fr/fr/information-par-pays/<pays>/conseils-aux-voyageurs-securite
// (texte « Zones de vigilance » + carte). Dates = « Dernière actualisation » de la rubrique Zones de vigilance.
const U = s => 'https://www.diplomatie.gouv.fr/fr/information-par-pays/' + s + '/conseils-aux-voyageurs-securite';
const p = (name, lat, lon, km) => ({ name, lat, lon, km });

module.exports = [
  // ───────────── MEXIQUE (actualisation 11/03/2026 ; carte datée 16/04/2025) ─────────────
  { country: 'MX', level: 'red', label: "État du Tamaulipas (hors sud-ouest et sud, déconseillés sauf raison impérative)",
    match: { regions: ['Tamaulipas'] },
    except: { near: [p('Tamaulipas sud-ouest (Tula, Jaumave)', 23.2, -99.7, 60), p('Ciudad Mante', 22.75, -99.0, 40), p('Tampico-Altamira', 22.5, -98.2, 70)] },
    source: U('mexique'), date: '2026-03-11' },
  { country: 'MX', level: 'orange', label: "Sud-ouest et sud du Tamaulipas (approximation par cercles)",
    match: { near: [p('Tamaulipas sud-ouest (Tula, Jaumave)', 23.2, -99.7, 60), p('Ciudad Mante', 22.75, -99.0, 40), p('Tampico-Altamira', 22.5, -98.2, 70)] },
    source: U('mexique'), date: '2026-03-11' },
  // 7e audit (18/09/2026) : l'exception « Ixtapa-Zihuatanejo » était un cercle de 12 km qui neutralisait le rouge sur
  // 53 lieux, dont une cinquantaine de hameaux de l'arrière-pays que la fiche laisse en rouge. Ramenée aux deux
  // localités de la station balnéaire (coordonnées GeoNames des données du projet). La fiche ne reconnaît ces
  // exceptions qu'« à la condition expresse de s'y rendre par la voie aérienne » : le libellé le rappelle.
  { country: 'MX', level: 'red', label: "États de Guerrero et de Colima (hors ville d'Acapulco, en orange, et station balnéaire d'Ixtapa-Zihuatanejo — exceptions que France Diplomatie ne reconnaît qu'à la condition de s'y rendre par voie aérienne)",
    match: { regions: ['Guerrero', 'Colima'] },
    except: { near: [p('Acapulco', 16.86, -99.88, 15), p('Zihuatanejo', 17.6434, -101.5521, 5), p('Ixtapa', 17.6678, -101.6416, 4)] },
    source: U('mexique'), date: '2026-03-11' },
  { country: 'MX', level: 'red', label: "Sud du Michoacán, d'Uruapan à la côte (et sud-ouest de l'État de Mexico d'après la carte) — approximation par cercles",
    match: { near: [p('Apatzingán / Uruapan', 19.0, -102.4, 80), p('Lázaro Cárdenas', 18.3, -102.6, 60), p('Coalcomán', 18.7, -103.2, 40), p('Tierra Caliente (Huetamo)', 18.8, -101.3, 70), p('Tejupilco / Luvianos', 18.85, -100.3, 35)] },
    source: U('mexique'), date: '2026-03-11' },
  { country: 'MX', level: 'red', label: "Villes de Tijuana et Tecate, Culiacán et ses alentours, triangle Celaya-Irapuato-Salamanca",
    match: { near: [p('Tijuana', 32.52, -117.03, 20), p('Tecate', 32.57, -116.63, 8), p('Culiacán', 24.8, -107.39, 25), p('Triangle Celaya-Irapuato-Salamanca', 20.6, -101.1, 35)] },
    source: U('mexique'), date: '2026-03-11' },
  { country: 'MX', level: 'orange', label: "Zone frontalière avec les États-Unis (bande de 40 km, approximation)",
    match: { borderKm: 40, with: 'US' },
    source: U('mexique'), date: '2026-03-11' },
  { country: 'MX', level: 'orange', label: "États de Basse-Californie, Chihuahua (hors ville de Chihuahua), Sinaloa, Durango, Nayarit, Zacatecas et Morelos",
    match: { regions: ['Baja California', 'Chihuahua', 'Sinaloa', 'Durango', 'Nayarit', 'Zacatecas', 'Morelos'] },
    except: { near: [p('Chihuahua (ville)', 28.63, -106.09, 15)] },
    source: U('mexique'), date: '2026-03-11' },
  { country: 'MX', level: 'orange', label: "Jalisco (sud-ouest, nord et Los Altos), hors Guadalajara, bande Guadalajara–Ocotlán et Puerto Vallarta — d'après la carte",
    match: { regions: ['Jalisco'] },
    except: { near: [p('Guadalajara', 20.6, -103.2, 60), p('Ocotlán / La Barca', 20.5, -102.5, 50), p('Puerto Vallarta', 20.62, -105.23, 15)] },
    source: U('mexique'), date: '2026-03-11' },
  { country: 'MX', level: 'orange', label: "Sud du Guanajuato (Uriangato, Acámbaro, Salvatierra) — approximation",
    match: { near: [p('Sud du Guanajuato', 20.15, -100.9, 45)] },
    source: U('mexique'), date: '2026-03-11' },
  { country: 'MX', level: 'orange', label: "Est du Nuevo León, à la frontière du Tamaulipas — approximation",
    match: { near: [p('Anáhuac / Cerralvo', 26.0, -99.6, 50), p('China / General Bravo', 25.3, -99.5, 40), p('Linares', 24.7, -99.6, 35)] },
    source: U('mexique'), date: '2026-03-11' },
  { country: 'MX', level: 'orange', label: "Nord du Veracruz, à partir de Martínez de la Torre — approximation",
    match: { near: [p('Pánuco', 21.9, -98.0, 60), p('Tuxpan / Álamo', 21.2, -97.7, 60), p('Poza Rica / Papantla', 20.5, -97.3, 45), p('Martínez de la Torre / Tlapacoyan', 20.1, -97.1, 25)] },
    source: U('mexique'), date: '2026-03-11' },
  { country: 'MX', level: 'orange', label: "Chiapas (dont frontière guatémaltèque et Selva Lacandona), hors Tuxtla Gutiérrez, San Cristóbal de las Casas et site de Palenque",
    match: { regions: ['Chiapas'] },
    except: { near: [p('Tuxtla Gutiérrez', 16.75, -93.12, 15), p('San Cristóbal de las Casas', 16.74, -92.64, 8), p('Site archéologique de Palenque', 17.48, -92.05, 5)] },
    source: U('mexique'), date: '2026-03-11' },
  { country: 'MX', level: 'orange', label: "Villes d'Acapulco, Ciudad Obregón, Toluca, Veracruz et Coatzacoalcos",
    match: { near: [p('Acapulco', 16.86, -99.88, 15), p('Ciudad Obregón', 27.49, -109.94, 12), p('Toluca', 19.29, -99.66, 15), p('Veracruz', 19.17, -96.13, 12), p('Coatzacoalcos', 18.13, -94.46, 10)] },
    source: U('mexique'), date: '2026-03-11' },
  { country: 'MX', level: 'orange', label: "Communes de l'État de Mexico : Ecatepec, Naucalpan, Nezahualcóyotl, Cuautitlán, Tultitlán, Izcalli, Tlalnepantla",
    match: { near: [p('Ecatepec de Morelos', 19.6, -99.05, 8), p('Naucalpan de Juárez', 19.47, -99.24, 4), p('Nezahualcóyotl', 19.4, -99.01, 5), p('Cuautitlán', 19.67, -99.18, 4), p('Tultitlán', 19.64, -99.17, 4), p('Cuautitlán Izcalli', 19.65, -99.21, 4), p('Tlalnepantla de Baz', 19.54, -99.19, 5)] },
    source: U('mexique'), date: '2026-03-11' },

  // ───────────── COLOMBIE (27/05/2026, carte du même jour) ─────────────
  { country: 'CO', level: 'red', label: "Zone frontalière avec le Venezuela (bande de 40 km)",
    match: { borderKm: 40, with: 'VE' }, source: U('colombie'), date: '2026-05-27' },
  { country: 'CO', level: 'red', label: "Zone frontalière avec le Brésil (bande de 20 km)",
    match: { borderKm: 20, with: 'BR' }, source: U('colombie'), date: '2026-05-27' },
  { country: 'CO', level: 'red', label: "Zone frontalière avec le Pérou (bande de 15 km)",
    match: { borderKm: 15, with: 'PE' }, source: U('colombie'), date: '2026-05-27' },
  { country: 'CO', level: 'red', label: "Département d'Arauca (frontière vénézuélienne élargie d'après la carte)",
    match: { regions: ['Arauca Department'] }, source: U('colombie'), date: '2026-05-27' },
  { country: 'CO', level: 'red', label: "Catatumbo et haute Guajira (frontière vénézuélienne élargie d'après la carte)",
    match: { near: [p('Catatumbo (Tibú)', 8.6, -73.0, 50), p('Haute Guajira (Uribia)', 11.9, -71.8, 70)] },
    source: U('colombie'), date: '2026-05-27' },
  { country: 'CO', level: 'red', label: "Côte pacifique et frontière panaméenne : Chocó (hors Nuquí, Bahía Solano, Quibdó, Capurganá) et Cauca (hors Popayán)",
    match: { regions: ['Chocó', 'Cauca Department'] },
    except: { near: [p('Nuquí', 5.71, -77.27, 8), p('Bahía Solano', 6.22, -77.4, 8), p('Quibdó', 5.69, -76.66, 6), p('Capurganá', 8.63, -77.35, 5), p('Popayán', 2.44, -76.61, 8)] },
    source: U('colombie'), date: '2026-05-27' },
  { country: 'CO', level: 'red', label: "Littoral du Valle del Cauca (Buenaventura) et golfe d'Urabá",
    match: { near: [p('Buenaventura', 3.88, -77.03, 45), p('Urabá (Turbo, Apartadó)', 8.0, -76.6, 35)] },
    source: U('colombie'), date: '2026-05-27' },
  { country: 'CO', level: 'red', label: "Frontière équatorienne : Nariño (hors Pasto et Tumaco) et Putumayo",
    match: { regions: ['Nariño', 'Putumayo Department'] },
    except: { near: [p('Pasto', 1.21, -77.28, 8), p('Tumaco', 1.8, -78.76, 6)] },
    source: U('colombie'), date: '2026-05-27' },
  { country: 'CO', level: 'orange', label: "Tumaco",
    match: { near: [p('Tumaco', 1.8, -78.76, 6)] }, source: U('colombie'), date: '2026-05-27' },
  { country: 'CO', level: 'orange', label: "Est et sud : Vichada, Guainía, Guaviare, Vaupés, Amazonas, Caquetá (hors San José del Guaviare, Mitú, Florencia, Leticia)",
    match: { regions: ['Vichada Department', 'Guainía Department', 'Guaviare Department', 'Vaupés', 'Amazonas Department', 'Caquetá'] },
    except: { near: [p('San José del Guaviare', 2.57, -72.64, 8), p('Mitú', 1.25, -70.23, 5), p('Florencia', 1.61, -75.61, 8), p('Leticia', -4.2, -69.94, 15)] },
    source: U('colombie'), date: '2026-05-27' },
  { country: 'CO', level: 'orange', label: "Sud du Meta (La Macarena) — d'après la carte, approximation",
    match: { near: [p('Sud du Meta', 3.0, -73.3, 95)] }, source: U('colombie'), date: '2026-05-27' },
  { country: 'CO', level: 'orange', label: "Nord d'Antioquia et de Santander, sud de Córdoba, Sucre et Bolívar, sud du Cesar et Valledupar — approximation par cercles",
    match: { near: [
      p('Sud de Córdoba (Tierralta)', 7.4, -76.1, 60), p('Bajo Cauca (Caucasia)', 7.4, -75.2, 60), p('Sud de Bolívar', 7.4, -74.3, 60), p('Barrancabermeja / nord Santander', 7.4, -73.8, 60),
      p('Córdoba (Montelíbano)', 8.4, -76.1, 60), p('Sud de Sucre', 8.4, -75.2, 60), p('Sud de Bolívar nord', 8.4, -74.3, 60), p('Sud du Cesar', 8.4, -73.8, 60),
      p('Cesar central', 9.3, -73.5, 45), p('Cesar nord', 10.0, -73.35, 25), p('Valledupar', 10.47, -73.25, 8)] },
    source: U('colombie'), date: '2026-05-27' },

  // ───────────── VENEZUELA (13/03/2026 ; carte 05/06/2023) ─────────────
  { country: 'VE', level: 'orange', label: "Ensemble du pays (dont Caracas et aéroport de Maiquetía), hors îles Los Roques",
    match: { all: true }, except: { regions: ['Dependencias Federales'] },
    source: U('venezuela'), date: '2026-03-13' },
  { country: 'VE', level: 'red', label: "Zone frontalière avec la Colombie (bande de 30 km)",
    match: { borderKm: 30, with: 'CO' }, source: U('venezuela'), date: '2026-03-13' },
  { country: 'VE', level: 'red', label: "Zone frontalière avec le Brésil (bande de 30 km)",
    match: { borderKm: 30, with: 'BR' }, source: U('venezuela'), date: '2026-03-13' },
  { country: 'VE', level: 'red', label: "Zone frontalière avec le Guyana (bande de 30 km)",
    match: { borderKm: 30, with: 'GY' }, source: U('venezuela'), date: '2026-03-13' },
  { country: 'VE', level: 'red', label: "Delta Amacuro",
    match: { regions: ['Delta Amacuro'] }, source: U('venezuela'), date: '2026-03-13' },
  { country: 'VE', level: 'red', label: "Arc minier (nord-est de l'État de Bolívar) — approximation par cercles",
    match: { near: [p('Arc minier ouest', 8.0, -64.0, 45), p('Ciudad Guayana / Guasipati', 7.9, -62.9, 80), p('El Callao / Tumeremo / El Dorado', 7.3, -61.6, 80)] },
    source: U('venezuela'), date: '2026-03-13' },
  { country: 'VE', level: 'red', label: "Nord de l'État de Sucre (zone côtière, péninsule de Paria) et péninsule de Paraguaná",
    match: { near: [p('Côte de Sucre ouest', 10.5, -64.0, 30), p('Carúpano', 10.6, -63.3, 35), p('Péninsule de Paria', 10.65, -62.5, 35), p('Péninsule de Paraguaná', 11.95, -70.0, 40)] },
    source: U('venezuela'), date: '2026-03-13' },

  // ───────────── HAÏTI (07/04/2026) ─────────────
  { country: 'HT', level: 'red', label: "Ensemble du pays",
    match: { all: true }, source: U('haiti'), date: '2026-04-07' },

  // ───────────── CUBA (27/03/2026, carte du même jour) ─────────────
  { country: 'CU', level: 'orange', label: "Ensemble de l'île (crise énergétique : voyages non essentiels déconseillés)",
    match: { all: true }, source: U('cuba'), date: '2026-03-27' },

  // ───────────── HONDURAS (18/03/2026 ; carte 12/02/2016) ─────────────
  { country: 'HN', level: 'orange', label: "Ensemble du pays, hors îles de la Baie, département de Valle et département de Copán",
    match: { all: true }, except: { regions: ['Bay Islands', 'Valle Department', 'Copán Department'] },
    source: U('honduras'), date: '2026-03-18' },

  // ───────────── NICARAGUA (11/03/2026) ─────────────
  { country: 'NI', level: 'orange', label: "Ville de Bluefields et ses environs immédiats",
    match: { near: [p('Bluefields', 12.01, -83.76, 15)] }, source: U('nicaragua'), date: '2026-03-11' },

  // ───────────── PANAMA (25/03/2026, carte 20/03/2026) ─────────────
  { country: 'PA', level: 'red', label: "Darién : zone frontalière avec la Colombie — approximation par cercles",
    match: { near: [p('Darién est (Yaviza–frontière)', 8.2, -77.5, 45), p('Darién sud-est', 7.6, -77.8, 45), p('Darién nord-est', 8.5, -77.7, 30)] },
    source: U('panama'), date: '2026-03-25' },
  { country: 'PA', level: 'orange', label: "Province du Darién",
    match: { regions: ['Darién'] }, source: U('panama'), date: '2026-03-25' },
  { country: 'PA', level: 'orange', label: "Extrémité orientale de la Guna Yala (Caledonia, Puerto Obaldía)",
    match: { near: [p('Guna Yala orientale', 8.8, -77.65, 40)] }, source: U('panama'), date: '2026-03-25' },
  { country: 'PA', level: 'orange', label: "Littoral du golfe des Moustiques — approximation par cercles",
    match: { near: [p('Golfe des Moustiques 1', 8.95, -81.85, 20), p('Golfe des Moustiques 2', 8.85, -81.45, 20), p('Golfe des Moustiques 3 (Calovébora)', 8.8, -81.05, 20), p('Golfe des Moustiques 4 (Belén)', 8.95, -80.65, 20), p('Golfe des Moustiques 5 (Miguel de la Borda)', 9.1, -80.3, 20)] },
    source: U('panama'), date: '2026-03-25' },
  { country: 'PA', level: 'orange', label: "Colón / Cristóbal et villes autour de Panama : San Miguelito, Pedregal, Tocumen, Arraiján, La Chorrera",
    match: { near: [p('Colón / Cristóbal', 9.36, -79.9, 8), p('San Miguelito', 9.03, -79.5, 4), p('Pedregal', 9.07, -79.43, 4), p('Tocumen', 9.08, -79.38, 5), p('Arraiján', 8.95, -79.65, 6), p('La Chorrera', 8.88, -79.78, 7)] },
    source: U('panama'), date: '2026-03-25' },

  // ───────────── JAMAÏQUE (09/03/2026) ─────────────
  { country: 'JM', level: 'red', label: "Ville de Spanish Town",
    match: { near: [p('Spanish Town', 17.99, -76.96, 6)] }, source: U('jamaique'), date: '2026-03-09' },

  // ───────────── TRINITÉ-ET-TOBAGO (13/03/2026 ; carte 14/06/2023) ─────────────
  { country: 'TT', level: 'orange', label: "Laventille, Morvant, Beetham, San Juan ; Chaguanas ; Sangre Grande ; Rio Claro-Mayaro ; côte sud (Siparia, Cedros, Penal, Point Fortin)",
    match: { regions: ['San Juan/Laventille', 'Chaguanas', 'Sangre Grande Regional Corporation', 'Mayaro', 'Siparia Regional Corporation', 'Penal/Debe', 'Point Fortin'] },
    source: U('trinite-et-tobago'), date: '2026-03-13' },
  { country: 'TT', level: 'orange', label: "Tunapuna, Curepe et Moruga",
    match: { near: [p('Tunapuna / Curepe', 10.645, -61.4, 5), p('Moruga', 10.1, -61.28, 10)] },
    source: U('trinite-et-tobago'), date: '2026-03-13' },

  // ───────────── ÉQUATEUR (05/03/2026 ; carte 05/04/2024) ─────────────
  { country: 'EC', level: 'red', label: "Zone frontalière avec la Colombie (bande de 15 km, hors couloir de Tulcán et Nueva Loja)",
    match: { borderKm: 15, with: 'CO' },
    except: { near: [p('Tulcán', 0.81, -77.72, 15), p('Nueva Loja', 0.09, -76.89, 8)] },
    source: U('equateur'), date: '2026-03-05' },
  { country: 'EC', level: 'red', label: "Littoral nord de la province d'Esmeraldas, de San Lorenzo à Esmeraldas",
    match: { near: [p('Littoral San Lorenzo–Esmeraldas', 1.15, -79.3, 40)] }, source: U('equateur'), date: '2026-03-05' },
  { country: 'EC', level: 'orange', label: "Provinces d'Esmeraldas, Manabí, Santa Elena, Guayas (dont Guayaquil), El Oro, Los Ríos et Santo Domingo de los Tsáchilas",
    match: { regions: ['Esmeraldas', 'Manabí', 'Santa Elena', 'Guayas', 'El Oro', 'Los Ríos', 'Santo Domingo de los Tsáchilas'] },
    source: U('equateur'), date: '2026-03-05' },
  { country: 'EC', level: 'orange', label: "Couloir de Tulcán et ville de Nueva Loja (Lago Agrio)",
    match: { near: [p('Tulcán', 0.81, -77.72, 15), p('Nueva Loja', 0.09, -76.89, 10)] }, source: U('equateur'), date: '2026-03-05' },

  // ───────────── PÉROU (11/03/2026 ; carte 21/12/2023) ─────────────
  { country: 'PE', level: 'red', label: "VRAEM (vallées des rivières Apurímac, Ene et Mantaro) — approximation par cercles",
    match: { near: [p('VRAEM (Pichari, Llochegua)', -12.4, -73.9, 70), p('VRAEM nord (Satipo, Mazamari)', -11.5, -74.4, 65), p('VRAEM est (La Convención nord)', -11.6, -73.2, 60), p('VRAEM sud (Kepashiato)', -12.8, -73.2, 45)] },
    source: U('perou'), date: '2026-03-11' },
  { country: 'PE', level: 'red', label: "Zone amazonienne frontalière avec la Colombie (Putumayo, bande de 40 km)",
    match: { borderKm: 40, with: 'CO' }, source: U('perou'), date: '2026-03-11' },
  { country: 'PE', level: 'orange', label: "Ville d'Abancay et Cordillère Azul (région de Huánuco) — approximation",
    match: { near: [p('Abancay', -13.64, -72.88, 10), p('Cordillère Azul ouest (Tingo María)', -9.1, -75.9, 65), p('Cordillère Azul est', -9.4, -75.2, 55)] },
    source: U('perou'), date: '2026-03-11' },

  // ───────────── BRÉSIL (04/03/2026 ; carte 10/07/2017) ─────────────
  { country: 'BR', level: 'red', label: "Zone frontalière avec le Venezuela (bande de 30 km)",
    match: { borderKm: 30, with: 'VE' }, except: { near: [p('Cucuí', 1.2, -66.85, 10)] },
    source: U('bresil'), date: '2026-03-04' },
  { country: 'BR', level: 'orange', label: "Zone frontalière avec la Colombie (bande de 50 km)",
    match: { borderKm: 50, with: 'CO' }, except: { near: [p('Cucuí', 1.2, -66.85, 10), p('Tabatinga', -4.25, -69.94, 15), p('Benjamin Constant', -4.38, -70.03, 10)] },
    source: U('bresil'), date: '2026-03-04' },
  { country: 'BR', level: 'orange', label: "Zone frontalière avec le Pérou (bande de 50 km)",
    match: { borderKm: 50, with: 'PE' }, except: { near: [p('Tabatinga', -4.25, -69.94, 15), p('Benjamin Constant', -4.38, -70.03, 10), p('Rio Branco', -9.97, -67.81, 15)] },
    source: U('bresil'), date: '2026-03-04' },
  { country: 'BR', level: 'orange', label: "Zone frontalière avec la Bolivie (bande de 50 km : Acre, Rondônia, Mato Grosso, Mato Grosso do Sul)",
    match: { borderKm: 50, with: 'BO' }, except: { near: [p('Rio Branco', -9.97, -67.81, 15)] },
    source: U('bresil'), date: '2026-03-04' },
  { country: 'BR', level: 'orange', label: "Zone frontalière avec le Paraguay jusqu'à Ponta Porã (bande de 50 km, hors Paraná et extrême sud du Mato Grosso do Sul)",
    match: { borderKm: 50, with: 'PY' }, except: { near: [p('Frontière Paraguay sud (Guaíra–Foz do Iguaçu)', -24.6, -54.6, 200)] },
    source: U('bresil'), date: '2026-03-04' },
  { country: 'BR', level: 'orange', label: "Zone frontalière avec le Venezuela (bande de 50 km)",
    match: { borderKm: 50, with: 'VE' }, except: { near: [p('Cucuí', 1.2, -66.85, 10), p('São Gabriel da Cachoeira', -0.13, -67.09, 10)] },
    source: U('bresil'), date: '2026-03-04' },
  { country: 'BR', level: 'orange', label: "Zone frontalière avec le Guyana (bande de 50 km)",
    match: { borderKm: 50, with: 'GY' }, source: U('bresil'), date: '2026-03-04' },
  { country: 'BR', level: 'orange', label: "Zone frontalière avec le Suriname (bande de 50 km)",
    match: { borderKm: 50, with: 'SR' }, source: U('bresil'), date: '2026-03-04' },
  { country: 'BR', level: 'orange', label: "Ouest de l'État d'Amazonas (hors Manaus et est de l'État, São Gabriel da Cachoeira, Tabatinga)",
    match: { regions: ['Amazonas'] },
    except: { near: [p("Manaus et est de l'Amazonas", -3.2, -58.5, 260), p("Sud-est de l'Amazonas (Manicoré, Apuí)", -6.5, -60.0, 180), p('São Gabriel da Cachoeira', -0.13, -67.09, 10), p('Tabatinga', -4.25, -69.94, 15), p('Benjamin Constant', -4.38, -70.03, 10)] },
    source: U('bresil'), date: '2026-03-04' },
  { country: 'BR', level: 'orange', label: "État d'Acre (hors Rio Branco)",
    match: { regions: ['Acre'] }, except: { near: [p('Rio Branco', -9.97, -67.81, 15)] },
    source: U('bresil'), date: '2026-03-04' },
  { country: 'BR', level: 'orange', label: "Nord de l'Amapá (frontière avec la Guyane, Oiapoque) — approximation",
    match: { near: [p('Oiapoque', 3.84, -51.83, 60)] }, source: U('bresil'), date: '2026-03-04' },

  // ───────────── BOLIVIE (17/03/2026 ; carte 17/07/2019) ─────────────
  { country: 'BO', level: 'orange', label: "Zone frontalière avec le Brésil (bande de 40 km)",
    match: { borderKm: 40, with: 'BR' }, source: U('bolivie'), date: '2026-03-17' },

  // ───────────── PARAGUAY (11/03/2026 ; carte 23/12/2019) ─────────────
  { country: 'PY', level: 'orange', label: "Pedro Juan Caballero et frontière brésilienne de l'Amambay ; limite San Pedro–Concepción (zone EPP) — approximation par cercles",
    match: { near: [
      p('Pedro Juan Caballero', -22.55, -55.73, 20), p('Frontière Amambay nord-ouest', -22.2, -56.3, 20), p('Frontière Amambay nord', -22.35, -55.95, 20),
      p('Frontière Amambay centre', -23.0, -55.6, 20), p('Capitán Bado', -23.4, -55.5, 20), p('Frontière Amambay–Canindeyú', -23.8, -55.4, 20), p('Ypejhú', -24.1, -55.3, 20),
      p('Limite San Pedro–Concepción ouest', -23.5, -56.8, 35), p('Limite San Pedro–Concepción est', -23.2, -56.1, 35), p('Yby Yaú', -23.0, -56.5, 30)] },
    source: U('paraguay'), date: '2026-03-11' },
];
