// Groupe « europe » : lignes de ferry existantes, transportant des véhicules, sans grille tarifaire fixe lisible.
// Recherches du 16 septembre 2026. Distances : orthodromie entre ports (calculée), durées : horaires publiés ou ordre
// de grandeur signalé dans la note. Aucune règle d'île nouvelle : toutes les masses utilisées existent déjà.
const N = { 1: null, 2: null, 5: null, foot: null };
const D = '2026-09-16';
module.exports = {
  landmassRules: {},
  ferries: [
    // ---------- Îles britanniques et irlandaises, Atlantique Nord ----------
    { a: 'continental', b: 'ireland', routeKey: 'rosslareCherbourg', name: 'Rosslare ↔ Cherbourg',
      operator: 'Stena Line (jusqu’à 3 départs/semaine), Brittany Ferries (jusqu’à 2/semaine)', durationH: 17, distanceKm: 440,
      priceStatus: 'variable', priceByClass: N,
      source: 'https://www.stenaline.co.uk/routes/rosslare-cherbourg', date: D,
      note: "Ligne ro-pax toute l'année (voitures, camping-cars, motos). Prix calculé à la réservation selon la date et le remplissage (« from » seulement sur les comparateurs, ~80 €). Durée 16-19 h selon navire ; retenue plutôt que Cork-Roscoff ou Dublin-Cherbourg car la plus fréquente. Distance orthodromique Rosslare-Cherbourg." },
    { a: 'greatBritain', b: 'guernsey', routeKey: 'pooleGuernsey', name: 'Poole ↔ St Peter Port (Guernesey)',
      operator: 'Condor Ferries (Brittany Ferries), Condor Voyager', durationH: 3, distanceKm: 145,
      priceStatus: 'variable', priceByClass: N,
      source: 'https://www.condorferries.co.uk/ferry-routes-ports/ferries-to-guernsey/ferries-to-guernsey-from-the-uk', date: D,
      note: "4 départs/semaine (ven.-lun.), rapide transportant voitures, caravanes ≤5 m, camping-cars ≤7 m. Aucun tarif affiché : moteur de réservation « best fares », prix selon le jour. Portsmouth-Guernesey (Commodore Clipper, ~7 h, 6/semaine) existe aussi ; Poole retenue car la plus courte." },
    { a: 'greatBritain', b: 'jersey', routeKey: 'pooleJersey', name: 'Poole ↔ St Helier (Jersey)',
      operator: 'Condor Ferries (Brittany Ferries), Condor Voyager', durationH: 4, distanceKm: 170,
      priceStatus: 'variable', priceByClass: N,
      source: 'https://www.condorferries.co.uk/ferry-routes-ports/ferries-to-jersey/ferries-to-jersey-from-poole', date: D,
      note: "Lun., jeu., ven., sam. ; « take your car » ; la page indique que le prix dépend du jour choisi (aucune grille). Durée ~4 h et distance 104 miles (167 km) publiées par Condor." },
    { a: 'ireland', b: 'isleOfMan', routeKey: 'larneDouglas', name: 'Larne ↔ Douglas',
      operator: 'Isle of Man Steam Packet Company (Ben-my-Chree, Manannan, Manxman)', durationH: 4.75, distanceKm: 116,
      priceStatus: 'variable', priceByClass: N,
      source: 'https://www.steam-packet.com/routes-and-times/larne-isle-of-man', date: D,
      note: "Nouvelle ligne toute l'année depuis avril 2026 (Belfast abandonné fin 2025). Voitures acceptées ; seulement « car from £98.50/€117 each way », tarif dynamique. Durée 2 h 45 (Manannan) ou 4 h 45 (navire conventionnel) : valeur conventionnelle retenue, le Ben-my-Chree assurant l'essentiel des rotations depuis juillet 2026. Dublin-Douglas existe aussi mais ses départs sont annulés du 23 juillet au 1er octobre 2026 (travaux de Holyhead) : Larne retenue. Larne est en Irlande du Nord (masse ireland)." },
    { a: 'continental', b: 'faroe', routeKey: 'hirtshalsTorshavn', name: 'Hirtshals ↔ Tórshavn',
      operator: 'Smyril Line (MS Norröna)', durationH: 31, distanceKm: 1053,
      priceStatus: 'variable', priceByClass: N,
      source: 'https://www.icelandferries.com/hirtshals-torshavn/', date: D,
      note: "Toute l'année, 2 départs/semaine en été, 1 en hiver ; Norröna : 800 voitures. Tarification dynamique (saison, cabine obligatoire, véhicule) : aucune grille officielle 2026 (déjà constaté dans le README). Durée 31 h en été, 38-40 h en hiver. Distance orthodromique." },
    { a: 'faroe', b: 'iceland', routeKey: 'torshavnSeydisfjordur', name: 'Tórshavn ↔ Seyðisfjörður',
      operator: 'Smyril Line (MS Norröna)', durationH: 15, distanceKm: 508,
      priceStatus: 'variable', priceByClass: N,
      source: 'https://www.northferries.com/en/smyril-line/', date: D,
      note: "Prolongement islandais de la même ligne (« only ferry connection to Iceland »), de mi-mars à fin novembre (pas de départ vers l'Islande du 3 janvier au 8 mars 2026 selon l'horaire officiel). Tarification dynamique. Durée ~15 h hors escale en été. Distance orthodromique." },
    // ---------- Méditerranée occidentale ----------
    { a: 'corsica', b: 'sardinia', routeKey: 'bonifacioSantaTeresa', name: 'Bonifacio ↔ Santa Teresa Gallura',
      operator: 'Moby Lines (Ichnusa Lines selon la saison)', durationH: 0.83, distanceKm: 17,
      priceStatus: 'variable', priceByClass: N,
      source: 'https://www.moby.it/rotte/traghetti-sardegna/santa-teresa-bonifacio-santa-teresa/', date: D,
      note: "Voitures, fourgons et camping-cars acceptés ; ~50 min ; prix « a partire da » variables selon saison et disponibilité, aucune grille fixe publiée. Distance orthodromique." },
    { a: 'sardinia', b: 'sicily', routeKey: 'cagliariPalermo', name: 'Cagliari ↔ Palermo',
      operator: 'Grimaldi Lines (juin-septembre 2026), autre compagnie le reste de l’année', durationH: 12, distanceKm: 389,
      priceStatus: 'variable', priceByClass: N,
      source: 'https://www.grimaldi-lines.com/en/route/cagliari-palermo/', date: D,
      note: "1 départ/semaine, voitures et camping-cars acceptés ; Grimaldi précise que les départs jusqu'au 31/05/2026 et à partir du 01/10/2026 sont opérés par une autre compagnie. Tarif calculé à la réservation. Durée ~12 h. Distance orthodromique." },
    // ---------- Adriatique ----------
    { a: 'korcula', b: 'lastovo', routeKey: 'velaLukaUbli', name: 'Vela Luka ↔ Ubli (Lastovo)',
      operator: 'Jadrolinija, ligne 604 (Split – Vela Luka – Ubli)', durationH: 1.5, distanceKm: 26,
      priceStatus: 'unknown', priceByClass: N,
      source: 'https://www.jadrolinija.hr/hr/putovanje/split_-vela_luka_korcula_-_ubli_lastovo', date: D,
      note: "Trajekt pour véhicules, toute l'année ; 1 h 30 entre Vela Luka et Lastovo (page Jadrolinija). Le tarif du tronçon Vela Luka-Ubli n'est affiché ni sur la page (chargé par la boutique en ligne) ni dans un document lisible ; le site putovnica.net renvoie 403." },
    // ---------- Méditerranée orientale : Chypre ----------
    { a: 'continental', b: 'cyprus', routeKey: 'tasucuGirne', name: 'Taşucu ↔ Girne (Kyrenia)',
      operator: 'Akgünler Denizcilik (et Filo Denizcilik)', durationH: 6, distanceKm: 120,
      priceStatus: 'variable', priceByClass: N,
      source: 'https://www.feribotseferleri.com.tr/en/guides/tasucu-girne-arabali-feribot-ucret-evrak-2026', date: D,
      note: "Ferry-voitures classique ~5-6 h, toute l'année (4 jours/semaine hors saison, quotidien l'été) ; prix « DYNAMIC », aucune grille standard publiée. Girne est au nord de Chypre, lieux présents dans communes-cy.txt (région Keryneia). Retenue car la plus courte et la plus fréquente pour la paire. ALTERNATIVE À GRILLE FIXE, même paire : Limassol ↔ Le Pirée (Scandro Holding, AF Marina, saisonnière 29 mai-1er septembre 2026, ~31 h, ~22 allers-retours), grille officielle https://scandroholding.com/wp-content/uploads/2026/04/PRICELIST-2026-ENG.pdf : véhicule ≤5 m 134,05 €, camping-car ≤5 m 140,63 €, moto 92,92 €, siège « Airbus » adulte 41,08 € (aller simple, taxes comprises)." },
    // ---------- Grèce : liaisons entre îles déjà modélisées ----------
    { a: 'crete', b: 'santorini', routeKey: 'heraklionSantorini', name: 'Heraklion ↔ Athinios (Santorin)',
      operator: 'Seajets, Minoan Lines, Blue Star Ferries', durationH: 2, distanceKm: 119,
      priceStatus: 'variable', priceByClass: N,
      source: 'https://www.ferryhopper.com/en/ferry-routes/direct/heraklion-to-santorini', date: D,
      note: "Toute l'année, jusqu'à 3/jour ; véhicules acceptés (voitures et motos sur les rapides, camping-cars sur les conventionnels). Tarifs selon compagnie, navire et date. Durée 1 h 30 (rapide) à 4 h 30." },
    { a: 'crete', b: 'karpathos', routeKey: 'sitiaKarpathos', name: 'Sitia ↔ Pigadia (Karpathos)',
      operator: 'ANEK Superfast – Blue Star Ferries (Prevelis)', durationH: 3.5, distanceKm: 106,
      priceStatus: 'variable', priceByClass: N,
      source: 'https://www.directferries.com/sitia_karpathos_ferry.htm', date: D,
      note: "Ro-pax toute l'année via Kasos (Crète – Kasos – Karpathos – Chalki – Rhodes). Durée la plus rapide ~3 h 30. Pas de grille officielle lue." },
    { a: 'karpathos', b: 'rhodes', routeKey: 'karpathosRhodes', name: 'Pigadia (Karpathos) ↔ Rhodes',
      operator: 'ANEK Superfast – Blue Star Ferries (Prevelis)', durationH: 5, distanceKm: 139,
      priceStatus: 'variable', priceByClass: N,
      source: 'https://karpathosinfo.com/karpathos-ferries/', date: D,
      note: "Même ligne ro-pax (Karpathos relié toute l'année à Chalki et Rhodes). Durée ~5 h avec escales : ordre de grandeur." },
    { a: 'crete', b: 'kythira', routeKey: 'kissamosKythira', name: 'Kissamos ↔ Diakofti (Cythère)',
      operator: 'Seajets (Gythio – Kythira – Antikythira – Kissamos), Aqua Jewel', durationH: 3.75, distanceKm: 96,
      priceStatus: 'variable', priceByClass: N,
      source: 'https://www.kithera.gr/en/routes-kythira/ferry-itineraries-kythira/', date: D,
      note: "Ferry-voitures ~3 h 45 (Aqua Jewel, hebdomadaire) ; Seajets 3 fois/semaine. Le site local cite 57 € la voiture, mais aucune grille de l'opérateur lue : variable." },
    { a: 'kos', b: 'rhodes', routeKey: 'kosRhodes', name: 'Kos ↔ Rhodes',
      operator: 'Blue Star Ferries (Blue Star Patmos, Blue Star 2, Blue Star Chios)', durationH: 3.5, distanceKm: 97,
      priceStatus: 'variable', priceByClass: N,
      source: 'https://www.ferries.gr/bluestarferries/dodekanese/', date: D,
      note: "Ligne Le Pirée – Dodécanèse, ro-pax pour véhicules. Durée ~3 h 30 : ordre de grandeur." },
    { a: 'kalymnos', b: 'kos', routeKey: 'mastichariPothia', name: 'Mastichari (Kos) ↔ Pothia (Kalymnos)',
      operator: 'ANE Kalymnou (Olympios Apollon, Olympios Zeus)', durationH: 0.75, distanceKm: 13,
      priceStatus: 'variable', priceByClass: N,
      source: 'https://www.ferryscanner.com/en/ferry-routes/ferry-mastihari-kos-kalymnos', date: D,
      note: "Ferry passagers et voitures toute l'année, ~45 min. Pas de grille officielle lue." },
    { a: 'kalymnos', b: 'leros', routeKey: 'kalymnosLeros', name: 'Pothia (Kalymnos) ↔ Lakki (Leros)',
      operator: 'Blue Star Ferries ; ANE Kalymnou (Nisos Kalymnos)', durationH: 1.25, distanceKm: 23,
      priceStatus: 'variable', priceByClass: N,
      source: 'https://www.ferries.gr/en/ferry-companies/anekalymnou/route/kalymnos-leros-lipsi-patmos-arki/', date: D,
      note: "Ro-pax transportant véhicules. Durée ~1 h 15 : ordre de grandeur." },
    { a: 'leros', b: 'patmos', routeKey: 'lerosPatmos', name: 'Lakki (Leros) ↔ Skala (Patmos)',
      operator: 'Blue Star Ferries ; ANE Kalymnou (Nisos Kalymnos)', durationH: 1, distanceKm: 35,
      priceStatus: 'variable', priceByClass: N,
      source: 'https://www.ferries.gr/bluestarferries/dodekanese/', date: D,
      note: "Même ligne Le Pirée – Patmos – Leros – Kalymnos – Kos – Rhodes. Durée ~1 h : ordre de grandeur." },
    { a: 'patmos', b: 'samos', routeKey: 'patmosPythagorio', name: 'Skala (Patmos) ↔ Pythagorio (Samos)',
      operator: 'ANE Kalymnou (Nisos Kalymnos)', durationH: 4, distanceKm: 54,
      priceStatus: 'variable', priceByClass: N,
      source: 'https://www.ferryscanner.com/en/ferry-companies/ane-kalymnou', date: D,
      note: "Ferry conventionnel passagers et véhicules toute l'année, Kalymnos – Leros – Lipsi – Patmos – Arki – Agathonisi – Pythagorio. Durée ~4 h avec escales : ordre de grandeur." },
    { a: 'ikaria', b: 'samos', routeKey: 'evdilosKarlovasi', name: 'Evdilos (Ikaria) ↔ Karlovasi (Samos)',
      operator: 'Blue Star Ferries', durationH: 1.2, distanceKm: 49,
      priceStatus: 'variable', priceByClass: N,
      source: 'https://www.ferryhopper.com/en/ferry-routes/direct/ikaria-samos', date: D,
      note: "Toute l'année (5/semaine hors saison, 17 en été) ; billets voiture et moto ; 1 h 12. Prix économiques cités par les comparateurs (voiture 24,50 €) mais pas de grille officielle lue." },
    { a: 'chios', b: 'samos', routeKey: 'vathyChios', name: 'Vathy (Samos) ↔ Chios',
      operator: 'Blue Star Ferries (Blue Star Myconos)', durationH: 2.75, distanceKm: 100,
      priceStatus: 'variable', priceByClass: N,
      source: 'https://www.ferries.gr/en/ferry-companies/bluestar/route/piraeus-samos-chios-mytilene-lemnos-thessaloniki/', date: D,
      note: "Ligne ro-pax Le Pirée – Syros – Mykonos – Ikaria – Samos – Chios – Mytilène – Lemnos – Kavala – Thessalonique. Durée ~2 h 45 : ordre de grandeur." },
    { a: 'chios', b: 'lesvos', routeKey: 'chiosMytilene', name: 'Chios ↔ Mytilène (Lesbos)',
      operator: 'Blue Star Ferries / Superfast', durationH: 3, distanceKm: 89,
      priceStatus: 'variable', priceByClass: N,
      source: 'https://www.ferryhopper.com/en/ferry-routes/direct/lesvos-chios', date: D,
      note: "Ferries conventionnels toute l'année, véhicules acceptés (« car tickets from €21 »), ~3 h." },
    { a: 'lesvos', b: 'limnos', routeKey: 'mytileneMyrina', name: 'Mytilène (Lesbos) ↔ Myrina (Lemnos)',
      operator: 'Blue Star Ferries, Seajets', durationH: 2.83, distanceKm: 154,
      priceStatus: 'variable', priceByClass: N,
      source: 'https://www.ferryscanner.com/en/ferry-routes/ferry-limnos-lesvos-mytilene-all-ports', date: D,
      note: "Toute l'année, ~3 départs/semaine, billets voiture et moto ; ~2 h 50. Lemnos était jusqu'ici une île reconnue sans aucune liaison." },
    { a: 'continental', b: 'limnos', routeKey: 'kavalaMyrina', name: 'Kavala ↔ Myrina (Lemnos)',
      operator: 'Blue Star Ferries, Seajets (ferries conventionnels)', durationH: 4, distanceKm: 130,
      priceStatus: 'variable', priceByClass: N,
      source: 'https://www.ferryhopper.com/en/ferry-routes/direct/kavala-lemnos', date: D,
      note: "Toute l'année (1-2/jour en été, jusqu'à 3/semaine en basse saison), 3-4 h, voitures dès ~50 € selon comparateur. Le README notait l'absence de véhicules sur la ligne directe du Pirée ; la ligne de Kavala, elle, les prend." },
    { a: 'ikaria', b: 'mykonos', routeKey: 'evdilosMykonos', name: 'Evdilos (Ikaria) ↔ Mykonos',
      operator: 'Blue Star Ferries (Blue Star Myconos)', durationH: 2.1, distanceKm: 78,
      priceStatus: 'variable', priceByClass: N,
      source: 'https://www.ferryscanner.com/en/ferry-vessels/imo9208679', date: D,
      note: "Ro-pax rapide, ~2 h 05 ; 4/semaine l'été, ~1 l'hiver." },
    { a: 'mykonos', b: 'syros', routeKey: 'syrosMykonos', name: 'Syros ↔ Mykonos',
      operator: 'Blue Star Ferries (Blue Star Myconos, Blue Star Naxos)', durationH: 1.25, distanceKm: 34,
      priceStatus: 'variable', priceByClass: N,
      source: 'https://www.ferries.gr/en/ferry-companies/bluestar/route/piraeus-samos-chios-mytilene-lemnos-thessaloniki/', date: D,
      note: "Ro-pax transportant véhicules. Durée ~1 h 15 : ordre de grandeur." },
    { a: 'mykonos', b: 'tinos', routeKey: 'tinosMykonos', name: 'Tinos ↔ Mykonos',
      operator: 'Fast Ferries, Golden Star Ferries, Blue Star Ferries', durationH: 0.5, distanceKm: 17,
      priceStatus: 'variable', priceByClass: N,
      source: 'https://fastferries.com.gr/en/routes/', date: D,
      note: "Ligne Rafina – Andros – Tinos – Mykonos, 1-3/jour ; Ekaterini P. (240 voitures), Fast Ferries Andros (280 voitures). ~30 min." },
    { a: 'andros', b: 'tinos', routeKey: 'gavrioTinos', name: 'Gavrio (Andros) ↔ Tinos',
      operator: 'Fast Ferries, Golden Star Ferries', durationH: 1.25, distanceKm: 54,
      priceStatus: 'variable', priceByClass: N,
      source: 'https://fastferries.com.gr/en/routes/', date: D,
      note: "Même ligne Rafina – Andros – Tinos – Mykonos, toute l'année. Durée ~1 h 15 : ordre de grandeur." },
    { a: 'syros', b: 'tinos', routeKey: 'syrosTinos', name: 'Syros ↔ Tinos',
      operator: 'Blue Star Ferries (Blue Star Naxos)', durationH: 0.6, distanceKm: 22,
      priceStatus: 'variable', priceByClass: N,
      source: 'https://www.ferries.gr/bluestarferries/cyclades/naxos/island/naxos-syros-tinos-ferries.htm', date: D,
      note: "Ro-pax ; comparateurs : voiture 21 €, moto 4 €, camping-car 25 €, mais pas de grille officielle lue. ~35 min." },
    { a: 'paros', b: 'syros', routeKey: 'syrosParos', name: 'Syros ↔ Parikia (Paros)',
      operator: 'Blue Star Ferries', durationH: 1.5, distanceKm: 43,
      priceStatus: 'variable', priceByClass: N,
      source: 'https://www.ferries.gr/en/ferry-companies/bluestar/route/piraeus-syros-paros-naxos-ios-santorini-anafi/', date: D,
      note: "Ligne Le Pirée – Syros – Paros – Naxos – Ios – Santorin – Anafi. Durée ~1 h 30 : ordre de grandeur." },
    { a: 'naxos', b: 'paros', routeKey: 'parosNaxos', name: 'Parikia (Paros) ↔ Naxos',
      operator: 'Blue Star Ferries (et Seajets)', durationH: 1, distanceKm: 20,
      priceStatus: 'variable', priceByClass: N,
      source: 'https://www.ferries.gr/en/ferry-companies/bluestar/route/piraeus-syros-paros-naxos-ios-santorini-anafi/', date: D,
      note: "Même ligne ro-pax. ~1 h : ordre de grandeur." },
    { a: 'ios', b: 'naxos', routeKey: 'naxosIos', name: 'Naxos ↔ Ios',
      operator: 'Blue Star Ferries', durationH: 1.67, distanceKm: 44,
      priceStatus: 'variable', priceByClass: N,
      source: 'https://www.ferries.gr/en/ferry-companies/bluestar/route/piraeus-syros-paros-naxos-ios-santorini-anafi/', date: D,
      note: "Même ligne ro-pax. ~1 h 40 : ordre de grandeur." },
    { a: 'ios', b: 'santorini', routeKey: 'iosSantorini', name: 'Ios ↔ Athinios (Santorin)',
      operator: 'Blue Star Ferries', durationH: 1.33, distanceKm: 40,
      priceStatus: 'variable', priceByClass: N,
      source: 'https://www.ferries.gr/en/ferry-companies/bluestar/route/piraeus-syros-paros-naxos-ios-santorini-anafi/', date: D,
      note: "Même ligne ro-pax. ~1 h 20 : ordre de grandeur." },
    { a: 'amorgos', b: 'naxos', routeKey: 'naxosKatapola', name: 'Naxos ↔ Katapola (Amorgos)',
      operator: 'Blue Star Ferries, Seajets', durationH: 2.5, distanceKm: 53,
      priceStatus: 'variable', priceByClass: N,
      source: 'https://en.netferry.com/ferries/from/naxos/katapola-amorgos', date: D,
      note: "Toute l'année (~30/semaine l'été, ~7 l'hiver), traversées acceptant les véhicules ; 1 h 10 (rapide) à ~3 h (conventionnel via les Petites Cyclades)." },
    { a: 'skiathos', b: 'skopelos', routeKey: 'skiathosSkopelos', name: 'Skiathos ↔ Skopelos',
      operator: 'Seajets (ferries à pont ouvert au départ de Volos)', durationH: 1, distanceKm: 21,
      priceStatus: 'variable', priceByClass: N,
      source: 'https://www.ferryhopper.com/en/ferries/greece/skopelos', date: D,
      note: "Ligne Volos – Skiathos – Skopelos – Alonissos, véhicules acceptés. Durée ~1 h : ordre de grandeur." },
    { a: 'alonissos', b: 'skopelos', routeKey: 'skopelosAlonissos', name: 'Skopelos ↔ Patitiri (Alonissos)',
      operator: 'Seajets', durationH: 0.5, distanceKm: 12,
      priceStatus: 'variable', priceByClass: N,
      source: 'https://www.greeka.com/sporades/alonissos/ferries/', date: D,
      note: "Même ligne Volos – Sporades, voitures et motos. ~30 min : ordre de grandeur." },
    { a: 'aegina', b: 'poros', routeKey: 'aeginaPoros', name: 'Égine ↔ Póros',
      operator: 'Saronic Ferries (Achaeos, Phivos, Apollon Hellas…)', durationH: 1.75, distanceKm: 27,
      priceStatus: 'variable', priceByClass: N,
      source: 'https://www.ferries.gr/en/ferry-companies/saronic-ferries/route/piraeus-aegina-agistri-methana-poros/', date: D,
      note: "Ligne Le Pirée – Égine – Méthana – Póros toute l'année, 90 à 140 véhicules par navire ; véhicule accompagné « 28 à 42 € » selon un guide, pas de grille officielle lue. ~1 h 45 via Méthana : ordre de grandeur." },
    { a: 'ithaca', b: 'kefalonia', routeKey: 'samiPisaetos', name: 'Sami (Céphalonie) ↔ Pisaetos (Ithaque)',
      operator: 'Levante Ferries, Ionion Pelagos', durationH: 0.5, distanceKm: 12,
      priceStatus: 'variable', priceByClass: N,
      source: 'https://ionionpelagos.com/en/ferry-schedules/kefaloni%CE%B1-ithaca-ferry-schedules/', date: D,
      note: "Navires pour voitures, motos, camping-cars et camions ; 20-30 min ; ~12 traversées/semaine l'été." },
    { a: 'kefalonia', b: 'zakynthos', routeKey: 'pessadaAgiosNikolaos', name: 'Pessada (Céphalonie) ↔ Agios Nikolaos (Zante)',
      operator: 'Ionian Pelagos / Ioniansea Ferries', durationH: 1.25, distanceKm: 25,
      priceStatus: 'variable', priceByClass: N,
      source: 'https://ionionpelagos.com/en/ferry-schedules/kefalonia-zakynthos/', date: D,
      note: "Saisonnière (12/06/2026-20/09/2026), 3/jour, pont-garage (voitures dès ~38 €, motos ~15 € selon guide) ; ~1 h 15." },
    // ---------- France métropolitaine ----------
    { a: 'belleIle', b: 'continental', routeKey: 'quiberonLePalais', name: 'Quiberon ↔ Le Palais (Belle-Île)',
      operator: 'BreizhGo Océane (Région Bretagne) — navires Bangor et Vindilis', durationH: 0.83, distanceKm: 14,
      priceStatus: 'unknown', priceByClass: N,
      source: 'https://www.belle-ile.com/organiser/venir-en-bateau-une-ile-plusieurs-ports-de-depart/au-depart-de-quiberon/depart-pour-belle-ile-en-mer-toute-l-annee/', date: D,
      note: "Toute l'année (5 A/R en hiver, 20+ en juillet-août), deux navires « spécialement conçus » pour voitures et deux-roues ; ~50 min. Grille officielle (oceane.breizhgo.bzh/tarifs-vehicules-aller-retour/) derrière anti-robot (HTTP 403, non contourné). L'office de tourisme ne donne qu'une fourchette « 197 € à 486,40 € aller-retour » selon type et longueur, hors passagers : insuffisant pour une grille par classe." },
    { a: 'continental', b: 'groix', routeKey: 'lorientPortTudy', name: 'Lorient ↔ Port-Tudy (Groix)',
      operator: 'BreizhGo Océane (Breizh Nevez I)', durationH: 0.75, distanceKm: 13,
      priceStatus: 'unknown', priceByClass: N,
      source: 'https://www.lorientbretagnesudtourisme.fr/fr/immanquables/ile-de-groix/traversee-bateau/', date: D,
      note: "Tous les jours toute l'année, « passagers, vélos, voitures et autres véhicules », réservation conseillée (places limitées) ; ~45 min. Grille BreizhGo derrière anti-robot (HTTP 403, non contourné) ; aucune autre source officielle lisible." }
  ]
};
