// Groupe « oceanie » : Australie, Nouvelle-Zélande, Mélanésie, Pacifique, collectivités françaises du Pacifique et
// dépendances de la Guadeloupe. Recherches du 16 septembre 2026 (sites des opérateurs, offices de tourisme, presse).
// Taux InforEuro septembre 2026 : 1 EUR = 119.355 XPF.
// Distances : à vol d'oiseau entre les ports (sauf mention) ; durées : horaires publiés ou ordres de grandeur signalés.
module.exports = {
  landmassRules: {
    AU: [
      { key: 'magneticIsland', match: { near: [{ name: 'Arcadia (Magnetic Island)', lat: -19.1488, lon: 146.8660, km: 3 }] },
        note: "Magnetic Island : seul lieu du fichier communes-au.txt sur l'île = Arcadia (vérifié : aucun autre lieu entre 19,10-19,22° S et 146,78-146,90° E). Règle à placer AVANT la règle '*' qui isole aujourd'hui Arcadia. Townsville reste en 'australia'." }
    ]
  },
  ferries: [
    // ------------------------------------------------------------ Australie
    { a: 'australia', b: 'tasmania', routeKey: 'geelongDevonport', "durationEstimated": true, name: 'Geelong ↔ Devonport',
      operator: 'Spirit of Tasmania (TT-Line, État de Tasmanie)', durationH: 10.5, distanceKm: 382,
      priceStatus: 'variable',
      priceByClass: { 1: null, 2: null, 5: null, foot: null },
      source: 'https://spiritoftasmania.getanchor.io/sailing-fares/vehicles-and-bicycles.html', date: '2026-09-16',
      note: "Voitures, 4x4, motos, camping-cars et caravanes acceptés (page Vehicles & Bicycles de l'opérateur). Tarifs « from $179 each way » en basse saison, variables selon la demande, la saison et le créneau (« Fares are subject to change without notice ») ; aucune grille fixe. Durée 9,5 à 11,5 h (RACV, guide 2026). Nouveaux navires Spirit IV et V à partir du 31/10/2026 (pas de passagers du 23 au 30/10/2026 : interruption ponctuelle, ligne maintenue)." },
    { a: 'australia', b: 'kangarooIsland', routeKey: 'capeJervisPenneshaw', "durationEstimated": true, name: 'Cape Jervis ↔ Penneshaw',
      operator: 'SeaLink Kangaroo Island', durationH: 0.75, distanceKm: 16,
      priceStatus: 'variable',
      priceByClass: { 1: null, 2: null, 5: null, foot: null },
      source: 'https://southaustralia.com/products/kangaroo-island/transport/kangaroo-island-sealink-ferry', date: '2026-09-16',
      note: "« passenger and vehicle ferry service », 45 min, 16 km (South Australian Tourism Commission). Page tarifs SeaLink (sealink.com.au) inaccessible (HTTP 403 / vérification anti-robot, non contournée) ; d'après les extraits de recherche, voiture ≤ 5 m « from $118 one way » et « variable pricing may apply to fares based on passenger demand and time of travel » : tarif variable." },
    { a: 'tasmania', b: 'bruny', routeKey: 'ketteringRobertsPoint', name: 'Kettering ↔ Roberts Point (Bruny Island)',
      operator: 'SeaLink Bruny Island', durationH: 0.33, distanceKm: 4,
      priceStatus: 'unknown',
      priceByClass: { 1: null, 2: null, 5: null, foot: null },
      source: 'https://www.sealink.com.au/bruny-island/ferry-information/bruny-island-ferry-fares/', date: '2026-09-16',
      note: "Bac véhicules (voitures, véhicules 6-10 m et > 10 m) de 20 min. Pages de SeaLink et de Transport Tasmania (transport.tas.gov.au) en HTTP 403 (anti-robot, non contourné) : grille officielle non lisible. Sources secondaires : ~50 à 56 AUD l'aller-retour par voiture passagers inclus, surcharge carburant temporaire 2026 — non reprises faute de lecture de la grille officielle. Distance ~4 km : ordre de grandeur." },
    { a: 'australia', b: 'magneticIsland', routeKey: 'townsvilleNellyBay', "durationEstimated": true, name: 'Townsville ↔ Nelly Bay (Magnetic Island)',
      operator: 'Magnetic Island Ferries', durationH: 0.67, distanceKm: 11,
      priceStatus: 'unknown',
      priceByClass: { 1: null, 2: null, 5: null, foot: null },
      source: 'https://magneticislandferries.com.au/', date: '2026-09-16',
      note: "« the only vehicle ferry connecting Townsville to Magnetic Island », ~40 min, réservation véhicule obligatoire. La page tarifs (magneticislandferries.com.au/prices/) ne donne que les piétons (18,50 AUD aller adulte) et renvoie pour les véhicules au moteur de réservation : tarif véhicule non publié. Nécessite la règle landmassRules AU 'magneticIsland'." },
    { a: 'australia', b: 'moreton', routeKey: 'brisbaneTangalooma', name: 'Port of Brisbane (Lytton) ↔ Tangalooma Wrecks',
      operator: 'Micat (Moreton Island Adventures)', durationH: 1.5, distanceKm: 31,
      priceStatus: 'variable',
      priceByClass: { 1: null, 2: null, 5: null, foot: null },
      source: 'https://www.moretonislandadventures.com.au/frequently-asked-questions/', date: '2026-09-16',
      note: "Seul ferry à voitures pour Moreton (4x4 uniquement sur l'île, île de sable). FAQ de l'opérateur : « A vehicle price depends on the date you are looking to travel, the time of day, the length of your vehicle and/or trailer, and the number of people in the vehicle » : tarif variable. Traversée ~90 min (page Micat)." },
    { a: 'australia', b: 'northStradbroke', routeKey: 'clevelandDunwich', "durationEstimated": true, name: 'Cleveland ↔ Dunwich (North Stradbroke)',
      operator: 'SeaLink North Stradbroke Island', durationH: 0.83, distanceKm: 11,
      priceStatus: 'variable',
      priceByClass: { 1: null, 2: null, 5: null, foot: null },
      source: 'https://www.sealink.com.au/north-stradbroke-island/ferry-information/north-stradbroke-island-ferry-fares/', date: '2026-09-16',
      note: "Ferry véhicules ~50 min Cleveland (12 Emmett Drive) ↔ Dunwich (Junner Street). Site SeaLink en 403 (anti-robot) ; extraits de ses pages : « flexible fares for the vehicle ferry and flat rates for passenger fares », « Off-peak fares are subject to change based on demand » : tarif variable." },
    { a: 'australia', b: 'kgari', routeKey: 'inskipPointHookPoint', "durationEstimated": true, name: "Inskip Point ↔ Hook Point (K'gari)",
      operator: 'Manta Ray Fraser Island Barges', durationH: 0.17, distanceKm: 2,
      priceStatus: 'unknown',
      priceByClass: { 1: null, 2: null, 5: null, foot: null },
      source: 'https://mantarayfraserislandbarge.com.au/', date: '2026-09-16',
      note: "Barges véhicules (4x4) toutes les ~30 min, 10 min de traversée, 6 h-17 h, sans réservation. Site de l'opérateur en 403 (anti-robot, non contourné) : tarif illisible. Alternative SeaLink River Heads ↔ Kingfisher Bay/Wanggoolba Creek (site aussi en 403) non retenue (une liaison par paire : la plus courte et la plus fréquente). Attention : érosion des pistes d'accès à la plage d'Inskip du 25/03/2026 au 30/01/2027 (Parks Queensland), ligne toujours exploitée. Distance ~2 km : ordre de grandeur." },
    { a: 'australia', b: 'frenchIsland', routeKey: 'corinellaFrenchIsland', "durationEstimated": true, name: 'Corinella ↔ French Island (barge)',
      operator: 'French Island Barge', durationH: 0.25, distanceKm: 4,
      priceStatus: 'unknown',
      priceByClass: { 1: null, 2: null, 5: null, foot: null },
      source: 'https://www.figsfrenchisland.com.au/getting-here/', date: '2026-09-16',
      note: "Barge « accommodates two standard size cars or a larger truck », rotations environ toutes les demi-heures quelques heures autour de la pleine mer (frenchislandinfo.com). « Call for vehicle prices – bookings essential » : tarif non communiqué. Le ferry Western Port Ferries Stony Point ↔ Tankerton est passagers seulement. Durée et distance : ordres de grandeur." },
    { a: 'tasmania', b: 'flinders', routeKey: 'bridportLadyBarron', "durationEstimated": true, name: 'Bridport ↔ Lady Barron (Flinders Island)',
      operator: 'Bass Strait Freight (Furneaux Freight), Matthew Flinders III/IV', durationH: 7, distanceKm: 113,
      priceStatus: 'unknown',
      priceByClass: { 1: null, 2: null, 5: null, foot: null },
      source: 'https://bassstraitfreight.com.au/services/', date: '2026-09-16',
      note: "Roulier hebdomadaire (en général le mardi, port de Bridport à marée) : « Many of our passengers accompany their cars and campers on the trip to Flinders Island », ~7 h. Aucun tarif publié (contact téléphone/courriel). À VÉRIFIER par la session principale : la page indique « This service is only available until Oct 2026 » sans préciser la suite (fin du service passagers ou simple horizon d'horaires) ; à retirer si l'arrêt est confirmé." },
    { a: 'australia', b: 'curtisIsland', routeKey: 'gladstoneSouthend', "durationEstimated": true, name: 'Gladstone Marina ↔ South End (Curtis Island)',
      operator: 'Curtis Ferry Services', durationH: 0.75, distanceKm: 10,
      priceStatus: 'unknown',
      priceByClass: { 1: null, 2: null, 5: null, foot: null },
      source: 'https://www.curtisferryservices.com.au/ferry-timetables/', date: '2026-09-16',
      note: "« Regular vehicle and passenger service to the South End of Curtis Island » (barge : voiture, van, caravane, remorque), 1 à 2 départs les lun., mer., ven., sam., dim. Aucun tarif sur le site (réservation ou téléphone). Durée ~45 min et distance : ordres de grandeur." },
    // ------------------------------------------------------------ Nouvelle-Zélande
    { a: 'northIsland', b: 'southIsland', routeKey: 'wellingtonPicton', "durationEstimated": true, name: 'Wellington ↔ Picton',
      operator: 'Interislander (KiwiRail)', durationH: 3.5, distanceKm: 65,
      priceStatus: 'variable',
      priceByClass: { 1: null, 2: null, 5: null, foot: null },
      source: 'https://www.interislander.co.nz/book/cook-strait-ferry-fares-and-payment-options', date: '2026-09-16',
      note: "Voitures, camping-cars et motos acceptés. Aucune grille : prix affiché à la réservation, différent selon le départ (conditions : frais de modification « and any difference in the fare if the fares are higher for the sailing you are changing to »). Traversée ~3 h 30. Bluebridge (même paire, même type de tarification) non retenu : une liaison par paire. Distance à vol d'oiseau (route maritime ~92 km)." },
    { a: 'northIsland', b: 'waiheke', routeKey: 'halfMoonBayKennedyPoint', "durationEstimated": true, name: 'Half Moon Bay ↔ Kennedy Point (Waiheke)',
      operator: 'SeaLink New Zealand', durationH: 0.75, distanceKm: 17,
      priceStatus: 'variable',
      priceByClass: { 1: null, 2: null, 5: null, foot: null },
      source: 'https://www.sealink.co.nz/timetables-fares/waiheke/waiheke-half-moon-bay', date: '2026-09-16',
      note: "« the only drive-on/drive-off ferry service to Waiheke Island » (voitures, motos, vélos). La page horaires-tarifs ne publie aucun montant et renvoie au moteur de réservation (« car and driver from $159 one way » selon des extraits, prix variables selon la date). Durée 45-60 min : ordre de grandeur." },
    { a: 'northIsland', b: 'greatBarrier', routeKey: 'aucklandTryphena', "durationEstimated": true, name: 'Auckland (Wynyard Quarter) ↔ Tryphena (Great Barrier)',
      operator: 'SeaLink New Zealand', durationH: 4.5, distanceKm: 87,
      priceStatus: 'variable',
      priceByClass: { 1: null, 2: null, 5: null, foot: null },
      source: 'https://www.sealink.co.nz/travelling-with-us/terminals/tryphena-wharf', date: '2026-09-16',
      note: "Ferry voitures/passagers/fret (terminal « Car Ferry Terminal - Tryphena Wharf »). Aucune grille publiée : « car and driver from $459 one way » selon les extraits, prix dépendant des dates, du véhicule et du départ, surcharge carburant temporaire depuis le 1er mai 2026 : variable. Durée ~4 à 4,5 h : ordre de grandeur." },
    { a: 'southIsland', b: 'durville', routeKey: 'frenchPassKapowai', "durationEstimated": true, name: "French Pass ↔ Kapowai (D'Urville Island)",
      operator: "D'Urville Crossings", durationH: 0.25, distanceKm: 3,
      priceStatus: 'unknown',
      priceByClass: { 1: null, 2: null, 5: null, foot: null },
      source: 'https://durvillecrossings.co.nz/durville-island-car-barge.php', date: '2026-09-16',
      note: "Barge « for vehicles, trailers, motorbikes, small machinery, and passengers », ~15 min, 5 jours/semaine (dim., lun., mar., jeu., ven.), réservation obligatoire, véhicules ≤ 2,2 m de large. Aucun tarif publié (contact courriel/Facebook) : inconnu." },
    // ------------------------------------------------------------ Fidji
    { a: 'vitiLevu', b: 'vanuaLevu', routeKey: 'natoviNabouwalu', "durationEstimated": true, name: 'Natovi ↔ Nabouwalu',
      operator: 'Patterson Brothers Shipping (et Goundar Shipping)', durationH: 3.5, distanceKm: 74,
      priceStatus: 'unknown',
      priceByClass: { 1: null, 2: null, 5: null, foot: null },
      source: 'https://fijipocketguide.com/the-guide-to-travelling-in-fiji-by-ferry/', date: '2026-09-16',
      note: "Rouliers quotidiens Viti Levu ↔ Vanua Levu ; « vehicles can be transported on these ferries for an additional fee » (Fiji Pocket Guide, mis à jour le 27/02/2026). Pas de grille véhicules : l'autorisation de la FCCC fixe des tarifs passagers maximums mais les véhicules sont facturés au fret ; sites des compagnies non lisibles. Traversée 2,5 à 4,5 h." },
    { a: 'vitiLevu', b: 'ovalau', routeKey: 'natoviBuresala', name: 'Natovi ↔ Buresala (Ovalau)',
      operator: 'Patterson Brothers Shipping', durationH: 0.83, distanceKm: 27,
      priceStatus: 'unknown',
      priceByClass: { 1: null, 2: null, 5: null, foot: null },
      source: 'https://fijipocketguide.com/how-to-take-the-ferry-to-the-lomaiviti-islands/', date: '2026-09-16',
      note: "Roulier quotidien (départ Natovi 16 h 00, arrivée Buresala 16 h 50), service bus + ferry depuis Suva ; véhicules acceptés (Fiji Pocket Guide, levukafiji.com). Véhicules facturés au fret, sans grille publiée. 14e audit du 19/09/2026 : distance non publiée de 27 km, 1,6 fois l'orthodromie entre les ports de lib/ferry-ports.js (16,4 km) ; route réelle non mesurable hors ligne (îlots et chenaux plus fins que la grille lib/land-grid.bin, ~10 km ; ports approchés par le centre des localités) : ordre de grandeur gardé, à vérifier." },
    { a: 'vanuaLevu', b: 'taveuni', routeKey: 'natuvuTaveuni', "durationEstimated": true, name: 'Natuvu (Buca Bay) ↔ Taveuni',
      operator: 'Goundar Shipping', durationH: 1.75, distanceKm: 21,
      priceStatus: 'unknown',
      priceByClass: { 1: null, 2: null, 5: null, foot: null },
      source: 'https://fijipocketguide.com/how-to-take-the-ferry-to-taveuni/', date: '2026-09-16',
      note: "Goundar exploite des « cargo, vehicle and passenger ferries » (Lomaiviti Princess, Lady Daya), liaison quotidienne Natuvu ↔ Taveuni en 90-120 min ; le Taveuni Princess (passagers) ne prend pas de véhicules. Aucun tarif véhicule publié ; horaires changés à bref délai (vérifier la page Facebook de Goundar)." },
    // ------------------------------------------------------------ Tonga
    { a: 'tongatapu', b: 'eua', routeKey: 'nukualofaEua', "durationEstimated": true, name: "Nuku'alofa ↔ 'Ohonua ('Eua)",
      operator: "ESTC ('Eua Shipping), Tofa Ramsay Shipping, Malau Shipping", durationH: 2.25, distanceKm: 35,
      priceStatus: 'unknown',
      priceByClass: { 1: null, 2: null, 5: null, foot: null },
      source: 'https://tongapocketguide.com/the-guide-to-travelling-in-tonga-by-ferry', date: '2026-09-16',
      note: "3 à 4 ferries par jour du lundi au samedi, 2 h à 2 h 30 ; véhicules transportables (la plupart des loueurs l'interdisent) — Tonga Pocket Guide mis à jour le 07/07/2026. Aucun tarif véhicule publié." },
    { a: 'tongatapu', b: 'lifukaFoa', routeKey: 'nukualofaPangai', "durationEstimated": true, name: "Nuku'alofa ↔ Pangai (Ha'apai)",
      operator: "Friendly Islands Shipping Agency (MV 'Otuanga'ofa), Tofa Ramsay Shipping", durationH: 13.5, distanceKm: 172,
      priceStatus: 'unknown',
      priceByClass: { 1: null, 2: null, 5: null, foot: null },
      source: "https://en.wikipedia.org/wiki/MV_'Otuanga'ofa", date: '2026-09-16',
      note: "MV 'Otuanga'ofa : roulier (« Ferry (RORO) ») Nuku'alofa – Pangai – Neiafu, en service en 2026 (Kaniva Tonga, février 2026) ; ~2 départs/semaine par opérateur, 13-14 h jusqu'à Ha'apai (Tonga Pocket Guide). Véhicules facturés au fret (résidents citant 900 TOP pour une voiture d'occasion vers Ha'apai, Parlement des Tonga), sans grille publiée." },
    { a: 'lifukaFoa', b: 'vavau', routeKey: 'pangaiNeiafu', "durationEstimated": true, name: "Pangai (Ha'apai) ↔ Neiafu (Vava'u)",
      operator: "Friendly Islands Shipping Agency (MV 'Otuanga'ofa), Tofa Ramsay Shipping", durationH: 8.5, distanceKm: 134,
      priceStatus: 'unknown',
      priceByClass: { 1: null, 2: null, 5: null, foot: null },
      source: 'https://tongapocketguide.com/the-guide-to-travelling-in-tonga-by-ferry', date: '2026-09-16',
      note: "Même rotation que Nuku'alofa ↔ Pangai (7 à 10 h entre Ha'apai et Vava'u) ; véhicules acceptés vers Vava'u (Tonga Pocket Guide). Tongatapu ↔ Vava'u se fait par Ha'apai : pas de liaison directe distincte modélisée. Tarif véhicule non publié." },
    // ------------------------------------------------------------ Nouvelle-Calédonie (grille officielle fixe trouvée)
    { a: 'grandeTerreNC', b: 'ileDesPins', routeKey: 'noumeaIleDesPins', "priceCovers": "vehicle", "coversSource": "grille Betico : conducteur non inclus (billet passager séparé)", name: 'Nouméa ↔ Kuto (Île des Pins)',
      operator: 'Betico (Betico 2)', durationH: 2.5, distanceKm: 112,
      priceByClass: { 1: 527.84, 2: 754.05, 5: 159.19, foot: 68.70 },
      currency: 'XPF', original: { car: 63000, van: 90000, moto: 19000, foot: 8200 },
      source: 'https://www.betico.nc/tarifs', date: '2026-09-16',
      note: "« The ship can accommodate up to 355 passengers and, to a lesser extent, freight and vehicles » (betico.nc). Grille « Véhicules, remorques et engins roulants », tarifs Fret Public, « Aller simple en F », « Applicable pour des voyages à partir du 01 Janvier 2025 » (toujours en ligne en septembre 2026) : Île des Pins et inter-îles — voiture < 4 m 50 000 F, 4-4,5 m 63 000 F (classe 1), 4,5-5 m 76 000 F, 5-6 m max 90 000 F (classe 2), moto < 125 cm3 11 000 F, ≥ 125 cm3 19 000 F (classe 5). Franchise assurance obligatoire 2 500 F (moto 1 500 F) et frais de dossier non ajoutés ; conducteur non inclus (billet passager séparé). Passager adulte Standard 8 200 F. 2h30 (betico.nc). Capacité véhicules limitée : réserver." },
    { a: 'grandeTerreNC', b: 'mare', routeKey: 'noumeaTadine', "priceCovers": "vehicle", "coversSource": "grille Betico : conducteur non inclus (billet passager séparé)", name: 'Nouméa ↔ Tadine (Maré)',
      operator: 'Betico (Betico 2)', durationH: 4, distanceKm: 169,
      priceByClass: { 1: 636.76, 2: 854.59, 5: 184.32, foot: 90.49 },
      currency: 'XPF', original: { car: 76000, van: 102000, moto: 22000, foot: 10800 },
      source: 'https://www.betico.nc/tarifs', date: '2026-09-16',
      note: "Même grille Betico (Fret Public, aller simple, depuis le 01/01/2025), colonne Nouméa ↔ Lifou, Maré ou Ouvéa : voiture < 4 m 63 000 F, 4-4,5 m 76 000 F (classe 1), 4,5-5 m 90 000 F, 5-6 m max 102 000 F (classe 2), moto < 125 cm3 13 000 F, ≥ 125 cm3 22 000 F (classe 5). Passager adulte Standard 10 800 F. Franchise assurance 2 500 F et frais de dossier non ajoutés. 4 h (betico.nc)." },
    { a: 'grandeTerreNC', b: 'lifou', routeKey: 'noumeaWe', "priceCovers": "vehicle", "coversSource": "grille Betico : conducteur non inclus (billet passager séparé)", name: 'Nouméa ↔ Wé (Lifou)',
      operator: 'Betico (Betico 2)', durationH: 5, distanceKm: 172,
      priceByClass: { 1: 636.76, 2: 854.59, 5: 184.32, foot: 90.49 },
      currency: 'XPF', original: { car: 76000, van: 102000, moto: 22000, foot: 10800 },
      source: 'https://www.betico.nc/tarifs', date: '2026-09-16',
      note: "Même grille et mêmes montants que Nouméa ↔ Maré (colonne Lifou, Maré ou Ouvéa). 5 h (betico.nc, rotation souvent via Maré)." },
    { a: 'mare', b: 'lifou', routeKey: 'tadineWe', "priceCovers": "vehicle", "coversSource": "grille Betico : conducteur non inclus (billet passager séparé)", name: 'Tadine (Maré) ↔ Wé (Lifou)',
      operator: 'Betico (Betico 2)', durationH: 2, distanceKm: 95,
      priceByClass: { 1: 527.84, 2: 754.05, 5: 159.19, foot: 68.70 },
      currency: 'XPF', original: { car: 63000, van: 90000, moto: 19000, foot: 8200 },
      source: 'https://www.betico.nc/tarifs', date: '2026-09-16',
      note: "Grille Betico colonne « Île des Pins & inter-îles (Lifou-Maré) » : mêmes montants que Nouméa ↔ Île des Pins. Passager inter-îles Standard 8 200 F. 2 h (betico.nc)." }
  ]
};
