// Groupe afrique : Afrique, Moyen-Orient / golfe Persique, Russie — lignes de ferry EXISTANTES transportant des
// véhicules, SANS grille tarifaire officielle fixe lisible (consigne CONSIGNE-FERRIES-SANS-TARIF.md, 16 sept. 2026).
// Toutes les clés de masse utilisées existent déjà (build-island-rules.js --keys) : aucune landmassRules proposée.
module.exports = {
  landmassRules: {},
  ferries: [
    // ── Océan Indien ────────────────────────────────────────────────────────────────────────────────────────
    { a: 'mayotteGrandeTerre', b: 'mayottePetiteTerre', routeKey: 'mamoudzouDzaoudzi', "durationEstimated": true, name: 'Mamoudzou ↔ Dzaoudzi',
      operator: 'Département de Mayotte — Direction/Service des transports maritimes (STM), barges et amphidrome',
      durationH: 0.25, distanceKm: 3,
      priceStatus: 'unknown',
      priceByClass: { 1: null, 2: null, 5: null, foot: null },
      source: 'https://la1ere.franceinfo.fr/mayotte/un-nouveau-tarif-pour-les-tickets-de-barge-a-partir-du-mois-de-mai-1687304.html (STM : amphidrome réservé aux véhicules légers et poids lourds, barge piétons + véhicules légers + deux-roues ; voir aussi https://la1ere.franceinfo.fr/mayotte/mayotte-le-billet-combine-bus-barge-passe-a-quatre-euros-aller-retour-a-partir-du-1er-juin-2026-1705849.html)',
      date: '2026-09-16',
      note: "Aucune délibération ni grille officielle consultable. La presse annonce pour mai 2026 piéton 1 €, deux-roues 3 €, véhicule 7 €, mais un article ultérieur situe le passage du piéton de 0,75 à 1 € en août 2026 (calendrier contradictoire) et une ancienne grille (2014) donnait 15 € la voiture : montants non retenus. Durée ~15 min et distance ~3 km entre gares maritimes : ordres de grandeur." },
    { a: 'continental', b: 'unguja', routeKey: 'darEsSalaamZanzibar', "durationEstimated": true, name: 'Dar es Salaam ↔ Zanzibar',
      operator: 'Azam Marine (ro-ro Azam Sea Link 1 et 2)', durationH: 4, distanceKm: 74,
      priceStatus: 'unknown',
      priceByClass: { 1: null, 2: null, 5: null, foot: null },
      source: 'https://bakhresa.com/azam-marine/ (« Our Ro-Ro vessels transport passengers and cargo to and from Dar es Salaam, Zanzibar, Pemba and Tanga » ; véhicules explicitement pris en charge)',
      date: '2026-09-16',
      note: "La page tarifaire officielle (https://azammarine.com/rates/) ne liste que les passagers des navires rapides ; véhicules sur devis au bureau. Durée : ordre de grandeur pour un ro-ro lent (les rapides font ~2 h), non publiée ; distance orthodromique entre ports." },
    { a: 'pemba', b: 'unguja', routeKey: 'zanzibarMkoani', "durationEstimated": true, name: 'Zanzibar ↔ Mkoani (Pemba)',
      operator: 'Azam Marine (ro-ro Azam Sea Link 1 et 2)', durationH: 6, distanceKm: 100,
      priceStatus: 'unknown',
      priceByClass: { 1: null, 2: null, 5: null, foot: null },
      source: 'https://bakhresa.com/azam-marine/ (ro-ro passagers + véhicules Dar/Zanzibar/Pemba/Tanga) ; https://www.marineradar.com/vessel/mmsi-677070700/azam-sealink-1 (AZAM SEALINK 1 relevé en route Zanzibar → Mkoani, sept. 2026)',
      date: '2026-09-16',
      note: "Aucun tarif véhicule publié. Attention : les agrégateurs (Direct Ferries) indiquent « pas de voiture » car ils ne vendent que les rapides (Zan Fast Ferries) ; seul le ro-ro Sea Link prend les véhicules. Durée : ordre de grandeur, non publiée ; distance orthodromique." },
    { a: 'continental', b: 'nosyBe', routeKey: 'ankifyHellVille', "durationEstimated": true, name: 'Ankify ↔ Hell-Ville (Nosy Be)',
      operator: 'Armateurs privés de bacs/barges (ex. Toky Bac 2)', durationH: 2.5, distanceKm: 17,
      priceStatus: 'variable',
      priceByClass: { 1: null, 2: null, 5: null, foot: null },
      source: 'https://fr.allafrica.com/stories/202608270372.html (27 août 2026 : bacs Ankify-Nosy Be, 4x4 200 000 Ar, minibus 400 000 Ar, Sprinter 500 000 Ar) ; https://normada.com/178-traversee-vers-nosy-be/1532-toky-bac-2.html',
      date: '2026-09-16',
      note: "Tarifs fixés librement par les transporteurs, la presse parle de « forte spéculation » en période d'affluence (août 2026) : variable. Barge véhicules ~2 h 30 ou plus ; distance orthodromique Ankify-Hell-Ville." },
    { a: 'mauritius', b: 'rodrigues', routeKey: 'portLouisPortMathurin', name: 'Port Louis ↔ Port Mathurin',
      operator: 'Mauritius Shipping Corporation Ltd (m/s Mauritius Trochetia, MV Peros Banhos)', durationH: 36, distanceKm: 620,
      priceStatus: 'unknown',
      priceByClass: { 1: null, 2: null, 5: null, foot: null },
      source: 'https://www.msclmu.com/services/marine-services/ (3 à 4 voyages par mois vers Rodrigues, passagers et fret ; « Cargo Services: … Vehicles » ; ~36 h aller, ~24 h retour)',
      date: '2026-09-16',
      note: "Navire mixte passagers (108 couchettes) / fret : le véhicule voyage en fret, sur devis, sans grille publiée ; cabines également sans tarif lisible sur le site. Durée publiée par l'opérateur (sens Port Louis → Rodrigues) ; distance orthodromique." },
    // ── Lacs d'Afrique de l'Est ────────────────────────────────────────────────────────────────────────────────
    { a: 'continental', b: 'ukerewe', routeKey: 'kisoryaRugezi', "durationEstimated": true, name: 'Kisorya ↔ Rugezi (Ukerewe)',
      operator: 'TEMESA (bac d’État, MV Ujenzi ; MV Ukerewe de 22 véhicules en cours de mise en service)', durationH: 0.25, distanceKm: 2,
      priceStatus: 'unknown',
      priceByClass: { 1: null, 2: null, 5: null, foot: null },
      source: 'https://www.temesa.go.tz/news/the-way-water-transport-has-become-a-solution-in-the-lake-zone (23 oct. 2025 : bac Kisorya-Rugezi, 800 passagers et 22 petits véhicules)',
      date: '2026-09-16',
      note: "Tarifs TEMESA réglementés mais aucune grille 2026 trouvée en ligne. Boîte 'ukerewe' d'ISLAND_BOXES resserrée (lon max 33,205, avant 33,35) : Kisorya (continent, 33,2146 E / -2,1105) n'y tombe plus. Durée/distance : ordre de grandeur du détroit de Rugezi." },
    { a: 'continental', b: 'ssese', routeKey: 'bukakataLuku', name: 'Bukakata ↔ Luku (Bugala)',
      operator: 'Kalangala Infrastructure Services (MV Pearl, MV Ssese)', durationH: 0.5, distanceKm: 7,
      priceStatus: 'unknown',
      priceByClass: { 1: null, 2: null, 5: null, foot: null },
      source: 'https://www.kis.co.ug/pages/view-page/Ferry-Services (deux ferries « roll-on, roll-off passengers and vehicles », traversée de 30 min)',
      date: '2026-09-16',
      note: "Aucun tarif publié par l'opérateur ; la gratuité de la traversée arrivait à échéance en juillet 2026 (voir README) sans grille de remplacement trouvée. Durée publiée (30 min) ; distance : ordre de grandeur." },
    { a: 'continental', b: 'mfangano', routeKey: 'mbitaMfangano', "durationEstimated": true, name: 'Mbita ↔ Mfangano',
      operator: 'Mbita Ferry Services', durationH: 1.5, distanceKm: 16,
      priceStatus: 'unknown',
      priceByClass: { 1: null, 2: null, 5: null, foot: null },
      source: 'https://mbitaferryservices.com/about-mbita-ferry/ (lignes Mbita-Mfangano et Mbita-Luanda Kotieno ; transporte motos, véhicules personnels, camions, tuk-tuks) ; https://eastleighvoice.co.ke/news/230621/mfangano-island-residents-petition-senate-for-state-run-ferry-service (oct. 2025 : ligne exploitée par Mbita Ferry Services)',
      date: '2026-09-16',
      note: "Le site de l'opérateur ne publie aucun tarif véhicule (« pricing varying by item type ») ; la grille trouvée sur des sites tiers n'est pas datée et est contredite par la presse (piéton 250 KSh). Durée : ordre de grandeur ; distance orthodromique Mbita-Sena. 14e audit du 19/09/2026 : distance dite « orthodromique » mais de 20 km, alors que l'orthodromie entre les ports de la liaison (lib/ferry-ports.js) vaut 16,4 km : distance recalculée, 16 km (minimum de la route réelle)." },
    { a: 'continental', b: 'likoma', routeKey: 'nkhataBayLikoma', "durationEstimated": true, name: 'Nkhata Bay ↔ Likoma',
      operator: 'Malawi Shipping Company (MV Chambo ; MV Ilala sur la ligne Monkey Bay-Chilumba)', durationH: 5, distanceKm: 70,
      priceStatus: 'unknown',
      priceByClass: { 1: null, 2: null, 5: null, foot: null },
      source: 'https://www.malawitourism.com/transport/ilala-malawi-shipping-company/ (Chambo : 80 passagers, 10 t de fret « including vehicles which can board using the mount at the front », service Likoma-Nkhata Bay) ; https://en.wikipedia.org/wiki/MV_Chambo (retour en service en 2024)',
      date: '2026-09-16',
      note: "Grilles de l'opérateur en PDF passagers seulement, aucun tarif véhicule. Petite unité (quelques véhicules au plus) et horaires très irréguliers. Durée : ordre de grandeur ; distance orthodromique. Chizumulu non reliée : aucune preuve de transport de véhicule." },
    // ── Golfe de Guinée ────────────────────────────────────────────────────────────────────────────────────────
    { a: 'bioko', b: 'continental', routeKey: 'malaboBata', "durationEstimated": true, name: 'Malabo ↔ Bata',
      operator: 'SEMAPORT S.L. / San Valentín (ferry San Valentín 3)', durationH: 12, distanceKm: 235,
      priceStatus: 'unknown',
      priceByClass: { 1: null, 2: null, 5: null, foot: null },
      source: 'https://www.revistaequato.com/el-ferry-san-valentin-3-suspende-temporalmente-la-ruta-malabo-bata-2/ (arrêt technique du 22 mai au 30 juin 2026, reprise ensuite) ; https://www.puentedemando.com/el-ferry-san-valentin-3-ex-la-galera-en-las-palmas/ (883 passagers, 110 voitures)',
      date: '2026-09-16',
      note: "Aucun tarif véhicule publié ; seuls des prix passagers de presse (≥ 35 000 XAF). Départ hebdomadaire (Malabo le vendredi, arrivée à Bata le samedi) : durée d'une nuit, ordre de grandeur ; distance orthodromique." },
    // ── Golfe Persique / mer Rouge ────────────────────────────────────────────────────────────────────────────
    { a: 'continental', b: 'qeshm', routeKey: 'bandarPolLaft', name: 'Bandar Pol ↔ Laft (Qeshm)',
      operator: 'Armateurs privés de landing crafts (zone franche de Qeshm)', durationH: 0.5, distanceKm: 10,
      priceStatus: 'unknown',
      priceByClass: { 1: null, 2: null, 5: null, foot: null },
      source: 'https://www.sharghdaily.com/بخش-اقتصادی-12/1091407-تردد-در-بنادر-مسافری-قشم-عادی-پایدار-است (1er mars 2026 : ligne Laft-Pol en service 24 h/24 par landing crafts porte-véhicules) ; http://mana.ir/fa/news/83282 (85 landing crafts et navires passagers sur Pol-Laft)',
      date: '2026-09-16',
      note: "Tarifs révisés plusieurs fois par an par l'autorité portuaire, aucune grille 2026 lisible. Traversée annoncée 20-30 min ; distance : ordre de grandeur. Interruptions météo ponctuelles (sept. 2026 : Shahid Haghani-Qeshm fermée, Pol-Laft indiquée comme alternative)." },
    { a: 'continental', b: 'kish', routeKey: 'charakKish', "durationEstimated": true, name: 'Charak ↔ Kish',
      operator: 'Organisation des ports de Kish (landing crafts porte-véhicules)', durationH: 2, distanceKm: 32,
      priceStatus: 'unknown',
      priceByClass: { 1: null, 2: null, 5: null, foot: null },
      source: 'https://www.iscanews.ir/news/1316564 (9 shahrivar 1405 = 31 août 2026 : vente en ligne des billets des landing crafts Charak-Kish, 122 traversées et 1 437 véhicules la semaine précédente)',
      date: '2026-09-16',
      note: "Billets vendus sur ticket.kishports.com (non consulté, aucune grille publique trouvée). Distance publiée ~32 km ; durée : ordre de grandeur pour un landing craft." },
    { a: 'continental', b: 'hormuz', routeKey: 'bandarAbbasHormuz', "durationEstimated": true, name: 'Bandar Abbas ↔ Hormuz',
      operator: 'Landing crafts depuis la jetée Shahid Haghani (ou Bandar Pol)', durationH: 0.75, distanceKm: 22,
      priceStatus: 'unknown',
      priceByClass: { 1: null, 2: null, 5: null, foot: null },
      source: 'https://sepris.com/mag/traveling-to-hormoz-with-personal-car/ (voiture embarquée sur landing craft à la jetée Shahid Haghani, ~45 min) ; https://www.sobhesahel.com/news/124572 (landing crafts autorisés à la jetée Shahid Haghani)',
      date: '2026-09-16',
      note: "Source d'existence plus faible (guide de voyage + presse locale), aucune grille tarifaire. Trafic interrompu par la météo mi-septembre 2026 « jusqu'à nouvel ordre » (suspension ponctuelle, pas un arrêt de ligne). Durée ~45 min publiée par le guide ; distance orthodromique." },
    { a: 'continental', b: 'farasan', routeKey: 'jazanFarasan', "durationEstimated": true, name: 'Jazan ↔ Farasan',
      operator: 'Transport General Authority (TGA) — projet des ferries Jazan-Farasan', durationH: 1.5, distanceKm: 50,
      priceStatus: 'unknown',
      priceByClass: { 1: null, 2: null, 5: null, foot: null },
      source: 'https://www.spa.gov.sa/en/N2163485 (TGA, 1er semestre 2024 : 250 000 passagers et 48 037 véhicules, service gratuit, ferries de 650 passagers et 60 voitures)',
      date: '2026-09-16',
      note: "Gratuité officielle (passagers et voitures, réservation obligatoire) confirmée seulement jusqu'en 2024 ; aucune confirmation 2026 trouvée, d'où 'unknown' plutôt qu'un prix 0. Durée et distance : ordres de grandeur." },
    { a: 'continental', b: 'failaka', routeKey: 'rasAlArdFailaka', "durationEstimated": true, name: 'Ras Al Ard ↔ Failaka',
      operator: 'Joan Al Kuwait ; Global Seas International (Um Al Khair)', durationH: 1, distanceKm: 26,
      priceStatus: 'unknown',
      priceByClass: { 1: null, 2: null, 5: null, foot: null },
      source: 'https://kuwaitalez.com/2448/جدول-رحلات-جزيرة-فيلكا/ (programme 2025 : transport de voitures depuis Ras Al Ard, Salmiya)',
      date: '2026-09-16',
      note: "Source d'existence faible (site d'information kowéïtien, 2025) : ni opérateur ni autorité consultés, activité 2026 non confirmée — à écarter si la session principale exige une source officielle. Montants relayés (voiture 20 KD Um Al Khair, voiture + conducteur 29 KD Joan) non officiels, non retenus. Durée/distance : ordres de grandeur." }
  ]
};
