// Ports de ferry du lot 3 (voir scripts/build-ferry-ports.js) : villes portuaires réellement desservies sur chaque rive.
// Quand la localité du terminal n'existe pas dans les données de lieux, la localité la plus proche du terminal sur la
// bonne masse terrestre est retenue (near = position approximative du terminal, pour lever les homonymies).
module.exports = [
  { key: 'greatBritain|lewisHarris', source: 'https://assets.calmac.co.uk/media/ws0j33hu/ullapool-stornoway-s26.pdf (Ullapool ↔ Stornoway)',
    ports: { greatBritain: [{ cc: 'GB', place: 'Ullapool' }], lewisHarris: [{ cc: 'GB', place: 'Stornoway' }] } },
  { key: 'greatBritain|uist', source: 'https://assets.calmac.co.uk/media/sdkjo22t/uig-lochmaddy-s26.pdf (Uig ↔ Lochmaddy)',
    ports: { greatBritain: [{ cc: 'GB', place: 'Uig', near: [57.585, -6.36] }], uist: [{ cc: 'GB', place: 'Lochmaddy' }] } },
  { key: 'lewisHarris|uist', source: 'https://assets.calmac.co.uk/media/5xmboukn/berneray-leverburgh-s26.pdf (Berneray ↔ Leverburgh)',
    ports: { lewisHarris: [{ cc: 'GB', place: 'Leverburgh' }], uist: [{ cc: 'GB', place: 'Borve', near: [57.703, -7.18] }] } },
  { key: 'barra|uist', source: 'https://assets.calmac.co.uk/media/wtvcanyh/ardmhor-eriskay-s26.pdf (Ardmhor (Barra) ↔ Eriskay) ; https://en.wikipedia.org/wiki/Ceann_a%27_Gh%C3%A0raidh (terminal d’Eriskay à Ceann a’ Ghàraidh)',
    ports: { barra: [{ cc: 'GB', place: 'Bayherivagh', near: [57.009, -7.404] }], uist: [{ cc: 'GB', place: 'Coilleag', near: [57.0706, -7.3078] }] } },
  { key: 'barra|greatBritain', source: 'https://assets.calmac.co.uk/media/jcijzce4/oban-castlebay-s26.pdf (Oban ↔ Castlebay)',
    ports: { barra: [{ cc: 'GB', place: 'Castlebay' }], greatBritain: [{ cc: 'GB', place: 'Oban' }] } },
  { key: 'greatBritain|isleOfWight', source: 'https://www.wightlink.co.uk/tickets/vehicle-tickets (Portsmouth ↔ Fishbourne)',
    ports: { greatBritain: [{ cc: 'GB', place: 'Portsmouth', near: [50.8, -1.09] }], isleOfWight: [{ cc: 'GB', place: 'Fishbourne' }] } },
  { key: 'hoy|orkney', source: 'https://www.orkneyferries.co.uk/documents/south-and-inner-isles-2026-27 (Houton ↔ Lyness)',
    ports: { hoy: [{ cc: 'GB', place: 'Lyness' }], orkney: [{ cc: 'GB', place: 'Houton' }] } },
  { key: 'orkney|rousay', source: 'https://www.orkneyferries.co.uk/documents/south-and-inner-isles-2026-27 (Tingwall ↔ Rousay)',
    ports: { orkney: [{ cc: 'GB', place: 'Tingwall' }], rousay: [{ cc: 'GB', place: 'Brinian' }] } },
  { key: 'orkney|shapinsay', source: 'https://www.orkneyferries.co.uk/documents/south-and-inner-isles-2026-27 (Kirkwall ↔ Shapinsay)',
    ports: { orkney: [{ cc: 'GB', place: 'Kirkwall' }], shapinsay: [{ cc: 'GB', place: 'Balfour' }] } },
  { key: 'orkney|westray', source: 'https://www.orkneyferries.co.uk/documents/north-isles-fares-26-27 (Kirkwall ↔ Rapness (Westray))',
    ports: { orkney: [{ cc: 'GB', place: 'Kirkwall' }], westray: [{ cc: 'GB', place: 'Rapness' }] } },
  { key: 'eday|orkney', source: 'https://www.orkneyferries.co.uk/documents/north-isles-fares-26-27 (Kirkwall ↔ Eday)',
    ports: { eday: [{ cc: 'GB', place: 'Veness' }], orkney: [{ cc: 'GB', place: 'Kirkwall' }] } },
  { key: 'orkney|sanday', source: 'https://www.orkneyferries.co.uk/documents/north-isles-fares-26-27 (Kirkwall ↔ Loth (Sanday))',
    ports: { orkney: [{ cc: 'GB', place: 'Kirkwall' }], sanday: [{ cc: 'GB', place: 'Stove' }] } },
  { key: 'orkney|stronsay', source: 'https://www.orkneyferries.co.uk/documents/north-isles-fares-26-27 (Kirkwall ↔ Whitehall (Stronsay))',
    ports: { orkney: [{ cc: 'GB', place: 'Kirkwall' }], stronsay: [{ cc: 'GB', place: 'Whitehall', near: [59.143, -2.598] }] } },
  { key: 'bressay|shetland', source: 'https://www.shetland.gov.uk/downloads/file/2963/ferry-fares (Lerwick ↔ Bressay)',
    ports: { bressay: [{ cc: 'GB', place: 'Heogan' }], shetland: [{ cc: 'GB', place: 'Lerwick' }] } },
  { key: 'shetland|yell', source: 'https://www.shetland.gov.uk/downloads/file/2963/ferry-fares (Toft ↔ Ulsta)',
    ports: { shetland: [{ cc: 'GB', place: 'Brough', near: [60.466, -1.207] }], yell: [{ cc: 'GB', place: 'Ulsta' }] } },
  { key: 'unst|yell', source: 'https://www.shetland.gov.uk/downloads/file/2963/ferry-fares (Gutcher ↔ Belmont)',
    ports: { unst: [{ cc: 'GB', place: 'Belmont', near: [60.685, -0.97] }], yell: [{ cc: 'GB', place: 'Gutcher' }] } },
  { key: 'fetlar|yell', source: 'https://www.shetland.gov.uk/downloads/file/2963/ferry-fares (Gutcher ↔ Hamars Ness (Fetlar))',
    ports: { fetlar: [{ cc: 'GB', place: 'Brough Lodge' }], yell: [{ cc: 'GB', place: 'Gutcher' }] } },
  { key: 'papaStour|shetland', source: 'https://www.shetland.gov.uk/downloads/file/2963/ferry-fares (West Burrafirth ↔ Papa Stour)',
    ports: { papaStour: [{ cc: 'GB', place: 'Biggings' }], shetland: [{ cc: 'GB', place: 'West Burrafirth' }] } },
  { key: 'iceland|vestmannaeyjar', source: 'https://herjolfur.is/en/prices (Landeyjahöfn ↔ Vestmannaeyjar)',
    ports: { iceland: [{ cc: 'IS', place: 'Hvolsvöllur' }], vestmannaeyjar: [{ cc: 'IS', place: 'Vestmannaeyjar' }] } },
  { key: 'grimsey|iceland', source: 'https://www.vegagerdin.is/en/the-transportation-system/public-transport/ferries/saefari-grimsey (Dalvík ↔ Grímsey)',
    ports: { grimsey: [{ cc: 'IS', place: 'Grímsey' }], iceland: [{ cc: 'IS', place: 'Dalvík' }] } },
  { key: 'faroe|kalsoy', source: 'https://www.ssl.fo/en/prices/prices-ferries (Klaksvík ↔ Syðradalur (Kalsoy))',
    ports: { faroe: [{ cc: 'FO', place: 'Klaksvík' }], kalsoy: [{ cc: 'FO', place: 'Syðradalur', near: [62.245, -6.668] }] } },
  { key: 'faroe|nolsoy', source: 'https://www.ssl.fo/en/prices/prices-ferries (Tórshavn ↔ Nólsoy)',
    ports: { faroe: [{ cc: 'FO', place: 'Tórshavn' }], nolsoy: [{ cc: 'FO', place: 'Nólsoy' }] } },
  { key: 'australia|raymondIsland', source: 'https://www.eastgippsland.vic.gov.au/roads-transport-and-infrastructure/raymond-island-ferry (Paynesville ↔ Raymond Island)',
    ports: { australia: [{ cc: 'AU', place: 'Paynesville' }], raymondIsland: [{ cc: 'AU', place: 'Raymond Island' }] } },
  { key: 'aeroe|continental', source: 'https://www.aeroe-ferry.dk/priser (Svendborg ↔ Ærøskøbing (Ærø))',
    ports: { aeroe: [{ cc: 'DK', place: 'Ærøskøbing' }], continental: [{ cc: 'DK', place: 'Svendborg' }] } },
  { key: 'continental|samsoe', source: 'https://www.tilsamsoe.dk/priser-ruten-hou-samso/ (Hou ↔ Sælvig (Samsø))',
    ports: { continental: [{ cc: 'DK', place: 'Hov', near: [55.912, 10.259] }], samsoe: [{ cc: 'DK', place: 'Sælvig' }] } },
  { key: 'continental|laesoe', source: 'https://www.laesoe-line.dk/files/downloads/Fartplan%20og%20prisliste%20L%C3%A6s%C3%B8f%C3%A6rgen%202026.pdf (Frederikshavn ↔ Vesterø Havn (Læsø))',
    ports: { continental: [{ cc: 'DK', place: 'Frederikshavn' }], laesoe: [{ cc: 'DK', place: 'Vesterø Havn' }] } },
  { key: 'continental|fanoe', source: 'https://www.fanoelinjen.dk/priser (Esbjerg ↔ Nordby (Fanø))',
    ports: { continental: [{ cc: 'DK', place: 'Esbjerg' }], fanoe: [{ cc: 'DK', place: 'Nordby', near: [55.445, 8.4] }] } },
  { key: 'anholt|continental', source: 'https://www.anholtfergen.dk/priser/ (Grenaa ↔ Anholt)',
    ports: { anholt: [{ cc: 'DK', place: 'Anholt' }], continental: [{ cc: 'DK', place: 'Grenaa' }] } },
  { key: 'continental|sejeroe', source: 'https://www.kalundborg.dk/service-and-selvbetjening/trafik-veje-and-groenne-omraader/trafik/sejeroebugtens-faerger/billetpriser-sejeroefaergen (Havnsø ↔ Sejerø)',
    ports: { continental: [{ cc: 'DK', place: 'Havnsø', near: [55.75, 11.33] }], sejeroe: [{ cc: 'DK', place: 'Sejerby' }] } },
  { key: 'continental|furDk', source: 'https://furfaerge.dk/media/uinhhje2/takstblad-2026.pdf (Branden ↔ Fur)',
    ports: { continental: [{ cc: 'DK', place: 'Branden' }], furDk: [{ cc: 'DK', place: 'Nederby' }] } },
  { key: 'continental|fejoe', source: 'https://lollandfaergefart.lolland.dk/om-lolland-faergefart/priser (Kragenæs ↔ Fejø)',
    ports: { continental: [{ cc: 'DK', place: 'Kragenæs' }], fejoe: [{ cc: 'DK', place: 'Vesterby' }] } },
  { key: 'continental|femoe', source: 'https://lollandfaergefart.lolland.dk/om-lolland-faergefart/priser (Kragenæs ↔ Femø)',
    ports: { continental: [{ cc: 'DK', place: 'Kragenæs' }], femoe: [{ cc: 'DK', place: 'Sønderby' }] } },
  { key: 'askoe|continental', source: 'https://lollandfaergefart.lolland.dk/om-lolland-faergefart/priser (Bandholm ↔ Askø)',
    ports: { askoe: [{ cc: 'DK', place: 'Askø By' }], continental: [{ cc: 'DK', place: 'Bandholm' }] } },
  { key: 'continental|endelave', source: 'https://mf-endelave.dk/priseroginformation/priser2026 (Snaptun ↔ Endelave)',
    ports: { continental: [{ cc: 'DK', place: 'Snaptun' }], endelave: [{ cc: 'DK', place: 'Endelave By' }] } },
  { key: 'continental|oroe', source: 'https://holbaek.dk/service-og-selvbetjening/personlige-forhold/betaling-opkraevning-og-takster/takster/oroe-faergen (Holbæk ↔ Orø)',
    ports: { continental: [{ cc: 'DK', place: 'Holbæk', near: [55.72, 11.715] }], oroe: [{ cc: 'DK', place: 'Brønde' }] } },
  { key: 'continental|venoe', source: 'https://venoefaergefart.dk/en/ferry-service-prices/ (Kleppen ↔ Venø)',
    ports: { continental: [{ cc: 'DK', place: 'Bremdal' }], venoe: [{ cc: 'DK', place: 'Venø By' }] } },
  { key: 'agersoe|continental', source: 'https://aofaerger.slagelse.dk/da/priser/priser-for-agersoe-faergen-2026-pr-1-maj/ (Stigsnæs ↔ Agersø)',
    ports: { agersoe: [{ cc: 'DK', place: 'Agersø By' }], continental: [{ cc: 'DK', place: 'Stigsnæs' }] } },
  { key: 'continental|omoe', source: 'https://aofaerger.slagelse.dk/da/priser/priser-for-omoe-faergen-2026-pr-1-maj/ (Stigsnæs ↔ Omø)',
    ports: { continental: [{ cc: 'DK', place: 'Stigsnæs' }], omoe: [{ cc: 'DK', place: 'Omø By' }] } },
  { key: 'continental|egholm', source: 'https://www.aalborg.dk/mit-liv/trafik-og-parkering/trafik-og-veje/faerger-og-broer/egholmfaergen/ (Aalborg ↔ Egholm)',
    ports: { continental: [{ cc: 'DK', place: 'Aalborg' }], egholm: [{ cc: 'DK', place: 'Egholm' }] } },
  { key: 'continental|strynoe', source: 'https://langelandkommune.dk/p/Stryn%C3%B8-Rudk%C3%B8bing-f%C3%A6rgefart-Sejlplan-og-priser-06.01.2025.pdf (Rudkøbing ↔ Strynø)',
    ports: { continental: [{ cc: 'DK', place: 'Rudkøbing' }], strynoe: [{ cc: 'DK', place: 'Strynø By' }] } },
  { key: 'avernakoe|continental', source: 'https://oefaergen.fmk.dk/priser/priser/ (Faaborg ↔ Avernakø)',
    ports: { avernakoe: [{ cc: 'DK', place: 'Avernak By' }], continental: [{ cc: 'DK', place: 'Faaborg' }] } },
  { key: 'continental|lyoe', source: 'https://oefaergen.fmk.dk/priser/priser/ (Faaborg ↔ Lyø)',
    ports: { continental: [{ cc: 'DK', place: 'Faaborg' }], lyoe: [{ cc: 'DK', place: 'Lyø By' }] } },
  { key: 'continental|drejoe', source: 'https://www.svendborghavn.dk/da/faerger/billetpriser/ (Svendborg ↔ Drejø (via Skarø))',
    ports: { continental: [{ cc: 'DK', place: 'Svendborg' }], drejoe: [{ cc: 'DK', place: 'Drejø' }] } },
  { key: 'continental|skaroe', source: 'https://www.svendborghavn.dk/da/faerger/billetpriser/ (Svendborg ↔ Skarø)',
    ports: { continental: [{ cc: 'DK', place: 'Svendborg' }], skaroe: [{ cc: 'DK', place: 'Skarø By' }] } },
  { key: 'continental|hjarnoe', source: 'https://xn--hjarnfrgefart-8fb2y.dk/priser/ (Snaptun ↔ Hjarnø)',
    ports: { continental: [{ cc: 'DK', place: 'Snaptun' }], hjarnoe: [{ cc: 'DK', place: 'Hjarnø By' }] } },
  { key: 'baagoe|continental', source: 'https://www.assenshavn.dk/assens-baagoe-faergen/priser-baagoefaergen (Assens ↔ Bågø)',
    ports: { baagoe: [{ cc: 'DK', place: 'Østerklint' }], continental: [{ cc: 'DK', place: 'Assens', near: [55.27, 9.89] }] } },
  { key: 'barsoe|continental', source: 'https://aabenraa.dk/media/r03dszw1/takster-2026.pdf (Barsø Landing ↔ Barsø)',
    ports: { barsoe: [{ cc: 'DK', place: 'Barsø By' }], continental: [{ cc: 'DK', place: 'Brøde' }] } },
  { key: 'continental|sylt', source: 'https://www.syltshuttle.de/syltshuttle-de/fahrkarten/tarif_2023-2049320 (Niebüll ↔ Westerland (Sylt Shuttle))',
    ports: { continental: [{ cc: 'DE', place: 'Niebüll' }], sylt: [{ cc: 'DE', place: 'Westerland' }] } },
  { key: 'continental|foehr', source: 'https://www.faehre.de/faehrverkehr/preise/fahrzeuge (Dagebüll ↔ Wyk auf Föhr)',
    ports: { continental: [{ cc: 'DE', place: 'Dagebüll' }], foehr: [{ cc: 'DE', place: 'Wyk auf Föhr' }] } },
  { key: 'amrum|continental', source: 'https://www.faehre.de/faehrverkehr/preise/fahrzeuge (Dagebüll ↔ Wittdün (Amrum))',
    ports: { amrum: [{ cc: 'DE', place: 'Wittdün' }], continental: [{ cc: 'DE', place: 'Dagebüll' }] } },
  { key: 'amrum|foehr', source: 'https://www.faehre.de/faehrverkehr/preise/fahrzeuge (Wyk (Föhr) ↔ Wittdün (Amrum))',
    ports: { amrum: [{ cc: 'DE', place: 'Wittdün' }], foehr: [{ cc: 'DE', place: 'Wyk auf Föhr' }] } },
  { key: 'continental|pellworm', source: 'https://www.faehre-pellworm.de/faehrfahrten/fahrpreise (Strucklahnungshörn ↔ Pellworm)',
    ports: { continental: [{ cc: 'DE', place: 'Mitteldeich', near: [54.498, 8.807] }], pellworm: [{ cc: 'DE', place: 'Pellworm' }] } },
  { key: 'borkum|continental', source: 'https://www.ag-ems.de/tarife/ (Emden ↔ Borkum)',
    ports: { borkum: [{ cc: 'DE', place: 'Borkum' }], continental: [{ cc: 'DE', place: 'Emden', near: [53.36, 7.2] }] } },
  { key: 'continental|norderney', source: 'https://www.reederei-frisia.de/ (Norddeich ↔ Norderney)',
    ports: { continental: [{ cc: 'DE', place: 'Norddeich', near: [53.616, 7.161] }], norderney: [{ cc: 'DE', place: 'Norderney' }] } },
  { key: 'continental|saaremaa', source: 'https://www.praamid.ee/hinnad-ja-soodustused/ (Virtsu ↔ Kuivastu (Muhu/Saaremaa))',
    ports: { continental: [{ cc: 'EE', place: 'Virtsu', near: [58.575, 23.51] }], saaremaa: [{ cc: 'EE', place: 'Kuivastu' }] } },
  { key: 'continental|hiiumaa', source: 'https://www.praamid.ee/hinnad-ja-soodustused/ (Rohuküla ↔ Heltermaa (Hiiumaa))',
    ports: { continental: [{ cc: 'EE', place: 'Rohuküla', near: [58.906, 23.424] }], hiiumaa: [{ cc: 'EE', place: 'Heltermaa' }] } },
  { key: 'hiiumaa|saaremaa', source: 'https://www.riigiteataja.ee/akt/126042025008 (Sõru (Hiiumaa) ↔ Triigi (Saaremaa))',
    ports: { hiiumaa: [{ cc: 'EE', place: 'Sõru' }], saaremaa: [{ cc: 'EE', place: 'Triigi' }] } },
  { key: 'continental|vormsi', source: 'https://veeteed.com/ (Rohuküla ↔ Sviby (Vormsi))',
    ports: { continental: [{ cc: 'EE', place: 'Rohuküla', near: [58.906, 23.424] }], vormsi: [{ cc: 'EE', place: 'Sviby' }] } },
  { key: 'continental|kihnu', source: 'https://veeteed.com/ (Munalaid ↔ Kihnu)',
    ports: { continental: [{ cc: 'EE', place: 'Lao' }], kihnu: [{ cc: 'EE', place: 'Sääre' }] } },
  { key: 'continental|ruhnu', source: 'https://ruhnu.ee/vald-uudised-ja-kontakt/valla-info/transport-saarele/ (Pärnu ↔ Ruhnu)',
    ports: { continental: [{ cc: 'EE', place: 'Pärnu' }], ruhnu: [{ cc: 'EE', place: 'Ruhnu' }] } },
  { key: 'continental|neringa', source: 'https://www.keltas.lt/kainorastis/ (Klaipėda ↔ Smiltynė (isthme de Courlande))',
    ports: { continental: [{ cc: 'LT', place: 'Klaipėda' }], neringa: [{ cc: 'LT', place: 'Smiltynė' }] } },
  { key: 'continental|tysnes', source: 'https://www.vegvesen.no/globalassets/fag/trafikk/ferje/pris---autopass-regulativ---fullpris---01.01.2026.pdf (Halhjem ↔ Våge (Tysnes))',
    ports: { continental: [{ cc: 'NO', place: 'Haljem' }], tysnes: [{ cc: 'NO', place: 'Våge' }] } },
  { key: 'austevoll|continental', source: 'https://www.vegvesen.no/globalassets/fag/trafikk/ferje/pris---autopass-regulativ---fullpris---01.01.2026.pdf (Krokeide ↔ Hufthamar (Austevoll))',
    ports: { austevoll: [{ cc: 'NO', place: 'Hufthammar' }], continental: [{ cc: 'NO', place: 'Krokeide' }] } },
  { key: 'continental|huglo', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Jektevik ↔ Nordhuglo (Huglo))',
    ports: { continental: [{ cc: 'NO', place: 'Agdestein' }], huglo: [{ cc: 'NO', place: 'Nordhuglo' }] } },
  { key: 'continental|varaldsoy', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Gjermundshamn ↔ Varaldsøy)',
    ports: { continental: [{ cc: 'NO', place: 'Gjermundshamn' }], varaldsoy: [{ cc: 'NO', place: 'Skjelnes' }] } },
  { key: 'continental|fjelberg', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Sydnes ↔ Fjelberg)',
    ports: { continental: [{ cc: 'NO', place: 'Sundnes', near: [59.733, 5.738] }], fjelberg: [{ cc: 'NO', place: 'Fjelberg' }] } },
  { key: 'continental|kvitsoy', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Mekjarvik ↔ Kvitsøy)',
    ports: { continental: [{ cc: 'NO', place: 'Sande', near: [59.019, 5.621] }], kvitsoy: [{ cc: 'NO', place: 'Ydstebøhamn' }] } },
  { key: 'continental|utsira', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Haugesund ↔ Utsira)',
    ports: { continental: [{ cc: 'NO', place: 'Haugesund' }], utsira: [{ cc: 'NO', place: 'Utsira' }] } },
  { key: 'continental|ombo', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Ryfylkeferjen (Ombo)) ; https://havspor.no/en/stopp/eidssund-ferjekai (Fogn–Judaberg–Helgøy, escale Eidssund) ; https://havspor.no/en/stopp/nesvik-ferjekai (Hjelmeland–Nesvik–Skipavik)',
    ports: { continental: [{ cc: 'NO', place: 'Judaberg' }, { cc: 'NO', place: 'Nesvik' }, { cc: 'NO', place: 'Hjelmelandsvågen' }], ombo: [{ cc: 'NO', place: 'Eidssund' }, { cc: 'NO', place: 'Skor', near: [59.253, 6.095] }] } },
  { key: 'continental|hidra', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Launes ↔ Kvellandstrand (Hidra))',
    ports: { continental: [{ cc: 'NO', place: 'Myran', near: [58.237, 6.612] }], hidra: [{ cc: 'NO', place: 'Bukstad' }] } },
  { key: 'andabeloy|continental', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Abelnes ↔ Andabeløy)',
    ports: { andabeloy: [{ cc: 'NO', place: 'Andabeløy' }], continental: [{ cc: 'NO', place: 'Abelnes' }] } },
  { key: 'continental|skatoy', source: 'https://www.farte.no/reise/billetter-og-priser/fergebilletter/ (Kragerø ↔ Skåtøy)',
    ports: { continental: [{ cc: 'NO', place: 'Kragerø' }], skatoy: [{ cc: 'NO', place: 'Skåtøy' }] } },
  { key: 'continental|sandoyaPorsgrunn', source: 'https://www.farte.no/reise/billetter-og-priser/fergebilletter/ (Brevik ↔ Sandøya)',
    ports: { continental: [{ cc: 'NO', place: 'Brevik', near: [59.05, 9.7] }], sandoyaPorsgrunn: [{ cc: 'NO', place: 'Sandøya' }] } },
  { key: 'continental|fedje', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Sævrøy ↔ Fedje)',
    ports: { continental: [{ cc: 'NO', place: 'Rebnor' }], fedje: [{ cc: 'NO', place: 'Fedje' }] } },
  { key: 'continental|leroy', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Klokkarvik ↔ Lerøy)',
    ports: { continental: [{ cc: 'NO', place: 'Klokkarvik' }], leroy: [{ cc: 'NO', place: 'Lerøyna' }] } },
  // Rive « hisaroy » : quai OpenStreetMap seul depuis le 18e audit du 21/09/2026. Le seul lieu publié de l'île,
  // Nyhamar, portait une coordonnée bouchon (61,0000 ; 5,0000 — deux entiers exacts, voir isPlaceholderCoord dans
  // scripts/communes-corrections.js) et a été écarté avec les 138 autres ; l'île n'a plus aucun lieu dans les données.
  // Le terminal est relevé sur OpenStreetMap plutôt qu'inventé : nœud 4334643364 « Hisarøy », amenity=ferry_terminal,
  // à 2,4 km d'Eivindvik, rangé sur la rive « hisaroy » par landmassOf. La liaison reste donc sourcée de bout en bout,
  // même si aucune étape ne peut s'y arrêter tant que l'île n'a pas de lieu publié.
  { key: 'continental|hisaroy', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Mjånes ↔ Hisarøy)',
    ports: { continental: [{ cc: 'NO', place: 'Eivindvik' }],
             hisaroy: [{ cc: 'NO', name: 'Hisarøy', quay: { osm: 'node/4334643364', lat: 60.9973276, lon: 5.0172346 } }] } },
  { key: 'continental|solund', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Rutledal ↔ Krakhella (Solund))',
    ports: { continental: [{ cc: 'NO', place: 'Rutledal' }], solund: [{ cc: 'NO', place: 'Kråkhella' }] } },
  { key: 'continental|losna', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Rysjedalsvika/Rutledal ↔ Losna)',
    ports: { continental: [{ cc: 'NO', place: 'Sågnes' }, { cc: 'NO', place: 'Rutledal' }], losna: [{ cc: 'NO', place: 'Losnegard' }] } },
  { key: 'continental|vaerlandet', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Askvoll ↔ Værlandet)',
    ports: { continental: [{ cc: 'NO', place: 'Askvoll' }], vaerlandet: [{ cc: 'NO', place: 'Vikja' }] } },
  { key: 'atloy|continental', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Askvoll ↔ Gjervik (Atløy))',
    ports: { atloy: [{ cc: 'NO', place: 'Gjerdvik' }], continental: [{ cc: 'NO', place: 'Askvoll' }] } },
  { key: 'continental|husevagoy', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Måløy ↔ Husevågøy)',
    ports: { continental: [{ cc: 'NO', place: 'Måløy', near: [61.935, 5.11] }], husevagoy: [{ cc: 'NO', place: 'Tytingevågen' }] } },
  { key: 'barmoya|continental', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Barmsund ↔ Barmen)',
    ports: { barmoya: [{ cc: 'NO', place: 'Barmen Ytre' }], continental: [{ cc: 'NO', place: 'Gulestein' }] } },
  { key: 'continental|sandsoya', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Larsnes ↔ Voksa (Sandsøya)) ; https://havspor.no/en/stopp/voksa-ferjekai (Larsnes–Åram–Voksa–Kvamsøya)',
    ports: { continental: [{ cc: 'NO', place: 'Larsnes' }], sandsoya: [{ cc: 'NO', place: 'Sandshamn' }] } },
  { key: 'continental|sekken', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Molde ↔ Sekken)',
    ports: { continental: [{ cc: 'NO', place: 'Molde', near: [62.74, 7.16] }], sekken: [{ cc: 'NO', place: 'Skogvik' }] } },
  { key: 'continental|midsund', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Brattvåg ↔ Dryna (Midsund))',
    ports: { continental: [{ cc: 'NO', place: 'Brattvåg' }], midsund: [{ cc: 'NO', place: 'Dryna' }] } },
  { key: 'continental|gossa', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Hollingsholmen ↔ Aukra (Gossa))',
    ports: { continental: [{ cc: 'NO', place: 'Jendem' }], gossa: [{ cc: 'NO', place: 'Aukra' }] } },
  { key: 'continental|storfosna', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Garten ↔ Storfosna)',
    ports: { continental: [{ cc: 'NO', place: 'Garten' }], storfosna: [{ cc: 'NO', place: 'Nordlandet' }] } },
  { key: 'continental|leksa', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Garten ↔ Leksa)',
    ports: { continental: [{ cc: 'NO', place: 'Garten' }], leksa: [{ cc: 'NO', place: 'Sørleksa' }] } },
  { key: 'continental|sulaFroya', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Dyrøy ↔ Sula (Frøya))',
    ports: { continental: [{ cc: 'NO', place: 'Setra', near: [63.799, 8.681] }], sulaFroya: [{ cc: 'NO', place: 'Sula' }] } },
  { key: 'continental|mausund', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Dyrøy ↔ Mausund)',
    ports: { continental: [{ cc: 'NO', place: 'Setra', near: [63.799, 8.681] }], mausund: [{ cc: 'NO', place: 'Mausund' }] } },
  { key: 'continental|sorburoya', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Dyrøy ↔ Sørburøy)',
    ports: { continental: [{ cc: 'NO', place: 'Setra', near: [63.799, 8.681] }], sorburoya: [{ cc: 'NO', place: 'Sørburøy' }] } },
  { key: 'continental|ytteroya', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Levanger ↔ Hokstad (Ytterøya))',
    ports: { continental: [{ cc: 'NO', place: 'Levanger' }], ytteroya: [{ cc: 'NO', place: 'Hokstad' }] } },
  { key: 'continental|joa', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Ølhammeren ↔ Seierstad (Jøa))',
    ports: { continental: [{ cc: 'NO', place: 'Holvik', near: [64.636, 11.36] }], joa: [{ cc: 'NO', place: 'Dun' }] } },
  { key: 'continental|leka', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Gutvik ↔ Skei (Leka))',
    ports: { continental: [{ cc: 'NO', place: 'Gutvik' }], leka: [{ cc: 'NO', place: 'Huseby' }] } },
  { key: 'continental|torget', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Brønnøysund ↔ Sauren/Stortorgnes (Torget))',
    ports: { continental: [{ cc: 'NO', place: 'Brønnøysund' }], torget: [{ cc: 'NO', place: 'Tofte' }] } },
  { key: 'continental|donna', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Sandnessjøen ↔ Dønna)',
    ports: { continental: [{ cc: 'NO', place: 'Sandnessjøen' }], donna: [{ cc: 'NO', place: 'Dalsvåg' }] } },
  { key: 'continental|lokta', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Sandnessjøen ↔ Løkta)',
    ports: { continental: [{ cc: 'NO', place: 'Sandnessjøen' }], lokta: [{ cc: 'NO', place: 'Breidvik', near: [66.142, 12.697] }] } },
  { key: 'continental|vandve', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Solfjellsjøen ↔ Vandve)',
    ports: { continental: [{ cc: 'NO', place: 'Solfjellsjøen' }], vandve: [{ cc: 'NO', place: 'Store Vandve' }] } },
  { key: 'continental|hugla', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Nesna ↔ Hugla)',
    ports: { continental: [{ cc: 'NO', place: 'Nesna' }], hugla: [{ cc: 'NO', place: 'Nordbustad' }] } },
  { key: 'continental|tomma', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Nesna ↔ Tomma)',
    ports: { continental: [{ cc: 'NO', place: 'Nesna' }], tomma: [{ cc: 'NO', place: 'Skeivstad' }] } },
  { key: 'continental|onoy', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Stokkvågen ↔ Onøy)',
    ports: { continental: [{ cc: 'NO', place: 'Stokkvågen' }], onoy: [{ cc: 'NO', place: 'Demmahågen' }] } },
  { key: 'continental|lovund', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Stokkvågen ↔ Lovund)',
    ports: { continental: [{ cc: 'NO', place: 'Stokkvågen' }], lovund: [{ cc: 'NO', place: 'Lovund' }] } },
  { key: 'continental|traena', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Stokkvågen ↔ Træna)',
    ports: { continental: [{ cc: 'NO', place: 'Stokkvågen' }], traena: [{ cc: 'NO', place: 'Husøya' }] } },
  { key: 'continental|nesoyaRodoy', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Kilboghamn ↔ Nordnesøy)',
    ports: { continental: [{ cc: 'NO', place: 'Kilboghamn' }], nesoyaRodoy: [{ cc: 'NO', place: 'Nordnesøy' }] } },
  { key: 'continental|meloya', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Ørnes ↔ Meløysund)',
    ports: { continental: [{ cc: 'NO', place: 'Ørnes', near: [66.87, 13.7] }], meloya: [{ cc: 'NO', place: 'Fagervik', near: [66.831, 13.555] }] } },
  { key: 'bolga|continental', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Ørnes ↔ Bolga)',
    ports: { bolga: [{ cc: 'NO', place: 'Bolga' }], continental: [{ cc: 'NO', place: 'Ørnes', near: [66.87, 13.7] }] } },
  { key: 'continental|stott', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Ørnes ↔ Støtt)',
    ports: { continental: [{ cc: 'NO', place: 'Ørnes', near: [66.87, 13.7] }], stott: [{ cc: 'NO', place: 'Støtt' }] } },
  { key: 'arnoyGildeskal|continental', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Sund ↔ Sørarnøy)',
    ports: { arnoyGildeskal: [{ cc: 'NO', place: 'Sør-Arnøy' }], continental: [{ cc: 'NO', place: 'Sund', near: [67.073, 14.065] }] } },
  { key: 'continental|vaeroy', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Bodø ↔ Værøy)',
    ports: { continental: [{ cc: 'NO', place: 'Bodø' }], vaeroy: [{ cc: 'NO', place: 'Kvalnes' }] } },
  { key: 'continental|rost', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Bodø ↔ Røst)',
    ports: { continental: [{ cc: 'NO', place: 'Bodø' }], rost: [{ cc: 'NO', place: 'Røst' }] } },
  { key: 'continental|vengsoya', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Bellvik ↔ Vengsøy)',
    ports: { continental: [{ cc: 'NO', place: 'Bellvika' }], vengsoya: [{ cc: 'NO', place: 'Vengsøya', near: [69.837, 18.587] }] } },
  { key: 'continental|rebbenesoya', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Mikkelvik ↔ Bromnes (Rebbenesøy))',
    ports: { continental: [{ cc: 'NO', place: 'Hornet', near: [70.061, 19.039] }], rebbenesoya: [{ cc: 'NO', place: 'Løksfjord' }] } },
  { key: 'continental|karlsoy', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Hansnes ↔ Karlsøy)',
    ports: { continental: [{ cc: 'NO', place: 'Hansnes' }], karlsoy: [{ cc: 'NO', place: 'Karlsøy' }] } },
  { key: 'continental|vannoya', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Hansnes ↔ Vannøy)',
    ports: { continental: [{ cc: 'NO', place: 'Hansnes' }], vannoya: [{ cc: 'NO', place: 'Lanasøren' }] } },
  { key: 'continental|reinoya', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Hansnes ↔ Stakkvik (Reinøy))',
    ports: { continental: [{ cc: 'NO', place: 'Hansnes' }], reinoya: [{ cc: 'NO', place: 'Stakkvik' }] } },
  // Deux liaisons dont la rive de départ était mal définie (continent au lieu de Saaremaa et de Gossa), corrigées dans
  // scripts/iles/iles-baltique.js. Quais situés d'après OpenStreetMap (Småge ferjekai 62,807 N 6,768 E ; Finnøya ferjekai
  // 62,804 N 6,509 E) : localités retenues Horrem (0,7 km) et Finnøy (0,6 km).
  { key: 'abruka|saaremaa', source: 'https://www.saaremaavald.ee/uhistransport (Roomassaare ↔ Abruka)',
    ports: { saaremaa: [{ cc: 'EE', place: 'Roomassaare' }], abruka: [{ cc: 'EE', place: 'Abruka' }] } },
  { key: 'finnoyaAlesund|gossa', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Småge ↔ Finnøya)',
    ports: { gossa: [{ cc: 'NO', place: 'Horrem' }], finnoyaAlesund: [{ cc: 'NO', place: 'Finnøy' }] } },
];
