// Ports de ferry du lot 3 (voir scripts/build-ferry-ports.js) : villes portuaires réellement desservies sur chaque rive.
// Quand la localité du terminal n'existe pas dans les données de lieux, la localité la plus proche du terminal sur la
// bonne masse terrestre est retenue (near = position approximative du terminal, pour lever les homonymies).
module.exports = [
  { key: 'greatBritain|lewisHarris', source: 'https://assets.calmac.co.uk/media/ws0j33hu/ullapool-stornoway-s26.pdf (Ullapool ↔ Stornoway)',
    ports: { greatBritain: [{ cc: 'GB', place: 'Ullapool' }], lewisHarris: [{ cc: 'GB', place: 'Stornoway' }] } },
  { key: 'greatBritain|uist', source: 'https://assets.calmac.co.uk/media/sdkjo22t/uig-lochmaddy-s26.pdf (Uig ↔ Lochmaddy)',
    ports: { greatBritain: [{ cc: 'GB', place: 'Uig', near: [57.585, -6.36] }], uist: [{ cc: 'GB', place: 'Lochmaddy' }] } },
  { key: 'lewisHarris|uist', source: 'https://assets.calmac.co.uk/media/5xmboukn/berneray-leverburgh-s26.pdf (Berneray ↔ Leverburgh)',
    ports: { lewisHarris: [{ cc: 'GB', place: 'Leverburgh' }], uist: [{ cc: 'GB', place: 'Borve', near: [57.703, -7.18] }] } },
  { key: 'barra|uist', source: 'https://assets.calmac.co.uk/media/wtvcanyh/ardmhor-eriskay-s26.pdf (Ardmhor (Barra) ↔ Eriskay) ; https://en.wikipedia.org/wiki/Ceann_a%27_Gh%C3%A0raidh (terminal d’Eriskay à Ceann a’ Ghàraidh)',
    ports: { barra: [{ cc: 'GB', place: 'Bayherivagh', near: [57.009, -7.404] }], uist: [{ cc: 'GB', place: 'Coilleag', near: [57.0706, -7.3078] }] } },
  { key: 'barra|greatBritain', source: 'https://assets.calmac.co.uk/media/jcijzce4/oban-castlebay-s26.pdf (Oban ↔ Castlebay)',
    ports: { barra: [{ cc: 'GB', place: 'Castlebay' }], greatBritain: [{ cc: 'GB', place: 'Oban' }] } },
  { key: 'greatBritain|isleOfWight', source: 'https://www.wightlink.co.uk/tickets/vehicle-tickets (Portsmouth ↔ Fishbourne)',
    ports: { greatBritain: [{ cc: 'GB', place: 'Portsmouth', near: [50.8, -1.09] }], isleOfWight: [{ cc: 'GB', place: 'Fishbourne' }] } },
  { key: 'hoy|orkney', source: 'https://www.orkneyferries.co.uk/documents/south-and-inner-isles-2026-27 (Houton ↔ Lyness)',
    ports: { hoy: [{ cc: 'GB', place: 'Lyness' }], orkney: [{ cc: 'GB', place: 'Houton' }] } },
  { key: 'orkney|rousay', source: 'https://www.orkneyferries.co.uk/documents/south-and-inner-isles-2026-27 (Tingwall ↔ Rousay)',
    ports: { orkney: [{ cc: 'GB', place: 'Tingwall' }], rousay: [{ cc: 'GB', place: 'Brinian' }] } },
  { key: 'orkney|shapinsay', source: 'https://www.orkneyferries.co.uk/documents/south-and-inner-isles-2026-27 (Kirkwall ↔ Shapinsay)',
    ports: { orkney: [{ cc: 'GB', place: 'Kirkwall' }], shapinsay: [{ cc: 'GB', place: 'Balfour' }] } },
  { key: 'orkney|westray', source: 'https://www.orkneyferries.co.uk/documents/north-isles-fares-26-27 (Kirkwall ↔ Rapness (Westray))',
    ports: { orkney: [{ cc: 'GB', place: 'Kirkwall' }], westray: [{ cc: 'GB', place: 'Rapness' }] } },
  { key: 'eday|orkney', source: 'https://www.orkneyferries.co.uk/documents/north-isles-fares-26-27 (Kirkwall ↔ Eday)',
    ports: { eday: [{ cc: 'GB', place: 'Veness' }], orkney: [{ cc: 'GB', place: 'Kirkwall' }] } },
  { key: 'orkney|sanday', source: 'https://www.orkneyferries.co.uk/documents/north-isles-fares-26-27 (Kirkwall ↔ Loth (Sanday))',
    ports: { orkney: [{ cc: 'GB', place: 'Kirkwall' }], sanday: [{ cc: 'GB', place: 'Stove' }] } },
  { key: 'orkney|stronsay', source: 'https://www.orkneyferries.co.uk/documents/north-isles-fares-26-27 (Kirkwall ↔ Whitehall (Stronsay))',
    ports: { orkney: [{ cc: 'GB', place: 'Kirkwall' }], stronsay: [{ cc: 'GB', place: 'Whitehall', near: [59.143, -2.598] }] } },
  { key: 'bressay|shetland', source: 'https://www.shetland.gov.uk/downloads/file/2963/ferry-fares (Lerwick ↔ Bressay)',
    ports: { bressay: [{ cc: 'GB', place: 'Heogan' }], shetland: [{ cc: 'GB', place: 'Lerwick' }] } },
  { key: 'shetland|yell', source: 'https://www.shetland.gov.uk/downloads/file/2963/ferry-fares (Toft ↔ Ulsta)',
    ports: { shetland: [{ cc: 'GB', place: 'Brough', near: [60.466, -1.207] }], yell: [{ cc: 'GB', place: 'Ulsta' }] } },
  { key: 'unst|yell', source: 'https://www.shetland.gov.uk/downloads/file/2963/ferry-fares (Gutcher ↔ Belmont)',
    ports: { unst: [{ cc: 'GB', place: 'Belmont', near: [60.685, -0.97] }], yell: [{ cc: 'GB', place: 'Gutcher' }] } },
  { key: 'fetlar|yell', source: 'https://www.shetland.gov.uk/downloads/file/2963/ferry-fares (Gutcher ↔ Hamars Ness (Fetlar))',
    ports: { fetlar: [{ cc: 'GB', place: 'Brough Lodge' }], yell: [{ cc: 'GB', place: 'Gutcher' }] } },
  { key: 'papaStour|shetland', source: 'https://www.shetland.gov.uk/downloads/file/2963/ferry-fares (West Burrafirth ↔ Papa Stour)',
    ports: { papaStour: [{ cc: 'GB', place: 'Biggings' }], shetland: [{ cc: 'GB', place: 'West Burrafirth' }] } },
  { key: 'iceland|vestmannaeyjar', source: 'https://herjolfur.is/en/prices (Landeyjahöfn ↔ Vestmannaeyjar)',
    ports: { iceland: [{ cc: 'IS', place: 'Hvolsvöllur' }], vestmannaeyjar: [{ cc: 'IS', place: 'Vestmannaeyjar' }] } },
  { key: 'grimsey|iceland', source: 'https://www.vegagerdin.is/en/the-transportation-system/public-transport/ferries/saefari-grimsey (Dalvík ↔ Grímsey)',
    ports: { grimsey: [{ cc: 'IS', place: 'Grímsey' }], iceland: [{ cc: 'IS', place: 'Dalvík' }] } },
  // Le terminal continental est à Árskógssandur, qui n'est pas publié sous ce nom : le lieu publié est
  // « Litli-Árskógssandur », le village du terminal, à 3,9 km de Hrísey.
  { key: 'hrisey|iceland', source: 'https://www.vegagerdin.is/en/the-transportation-system/public-transport/ferries/saevar-hrisey (Árskógssandur ↔ Hrísey)',
    ports: { hrisey: [{ cc: 'IS', place: 'Hrísey' }], iceland: [{ cc: 'IS', place: 'Litli-Árskógssandur' }] } },
  // Îles Sous-le-Vent (Apetahi Express) : les ports sont les chefs-lieux publiés — Fare, Vaitape et les quais de Taha'a
  // ne figurent pas dans les données, l'île elle-même y tient lieu de point d'embarquement.
  { key: 'huahine|tahiti', source: 'https://tuateaferries.com/en/fares/ (Papeete ↔ Fare (Huahine))',
    ports: { huahine: [{ cc: 'FR', place: 'Huahine' }], tahiti: [{ cc: 'FR', place: 'Papeete' }] } },
  { key: 'huahine|raiatea', source: 'https://tuateaferries.com/en/fares/ (Fare (Huahine) ↔ Uturoa (Raiatea))',
    ports: { huahine: [{ cc: 'FR', place: 'Huahine' }], raiatea: [{ cc: 'FR', place: 'Uturoa' }] } },
  { key: 'raiatea|tahaa', source: 'https://tuateaferries.com/en/fares/ (Uturoa (Raiatea) ↔ Taha\'a)',
    ports: { raiatea: [{ cc: 'FR', place: 'Uturoa' }], tahaa: [{ cc: 'FR', place: 'Tahaa' }] } },
  { key: 'boraBora|tahaa', source: 'https://tuateaferries.com/en/fares/ (Taha\'a ↔ Vaitape (Bora-Bora))',
    ports: { boraBora: [{ cc: 'FR', place: 'Bora-Bora' }], tahaa: [{ cc: 'FR', place: 'Tahaa' }] } },
  // Golfe de Naples : lignes de PASSAGERS, les seules ouvertes toute l'année aux non-résidents.
  { key: 'continental|procida', source: 'https://mobile.caremar.it/it/tariffe/ (Napoli ↔ Procida)',
    ports: { continental: [{ cc: 'IT', place: 'Napoli' }], procida: [{ cc: 'IT', place: 'Procida' }] } },
  { key: 'capri|continental', source: 'https://mobile.caremar.it/it/tariffe/ (Napoli ↔ Capri)',
    ports: { capri: [{ cc: 'IT', place: 'Capri' }], continental: [{ cc: 'IT', place: 'Napoli' }] } },
  { key: 'faroe|kalsoy', source: 'https://www.ssl.fo/en/prices/prices-ferries (Klaksvík ↔ Syðradalur (Kalsoy))',
    ports: { faroe: [{ cc: 'FO', place: 'Klaksvík' }], kalsoy: [{ cc: 'FO', place: 'Syðradalur', near: [62.245, -6.668] }] } },
  { key: 'faroe|nolsoy', source: 'https://www.ssl.fo/en/prices/prices-ferries (Tórshavn ↔ Nólsoy)',
    ports: { faroe: [{ cc: 'FO', place: 'Tórshavn' }], nolsoy: [{ cc: 'FO', place: 'Nólsoy' }] } },
  { key: 'australia|raymondIsland', source: 'https://www.eastgippsland.vic.gov.au/roads-transport-and-infrastructure/raymond-island-ferry (Paynesville ↔ Raymond Island)',
    ports: { australia: [{ cc: 'AU', place: 'Paynesville' }], raymondIsland: [{ cc: 'AU', place: 'Raymond Island' }] } },
  { key: 'aeroe|continental', source: 'https://www.aeroe-ferry.dk/priser (Svendborg ↔ Ærøskøbing (Ærø))',
    ports: { aeroe: [{ cc: 'DK', place: 'Ærøskøbing' }], continental: [{ cc: 'DK', place: 'Svendborg' }] } },
  { key: 'continental|samsoe', source: 'https://www.tilsamsoe.dk/priser-ruten-hou-samso/ (Hou ↔ Sælvig (Samsø))',
    ports: { continental: [{ cc: 'DK', place: 'Hov', near: [55.912, 10.259] }], samsoe: [{ cc: 'DK', place: 'Sælvig' }] } },
  { key: 'continental|laesoe', source: 'https://www.laesoe-line.dk/files/downloads/Fartplan%20og%20prisliste%20L%C3%A6s%C3%B8f%C3%A6rgen%202026.pdf (Frederikshavn ↔ Vesterø Havn (Læsø))',
    ports: { continental: [{ cc: 'DK', place: 'Frederikshavn' }], laesoe: [{ cc: 'DK', place: 'Vesterø Havn' }] } },
  { key: 'continental|fanoe', source: 'https://www.fanoelinjen.dk/priser (Esbjerg ↔ Nordby (Fanø))',
    ports: { continental: [{ cc: 'DK', place: 'Esbjerg' }], fanoe: [{ cc: 'DK', place: 'Nordby', near: [55.445, 8.4] }] } },
  { key: 'anholt|continental', source: 'https://www.anholtfergen.dk/priser/ (Grenaa ↔ Anholt)',
    ports: { anholt: [{ cc: 'DK', place: 'Anholt' }], continental: [{ cc: 'DK', place: 'Grenaa' }] } },
  { key: 'continental|sejeroe', source: 'https://www.kalundborg.dk/service-and-selvbetjening/trafik-veje-and-groenne-omraader/trafik/sejeroebugtens-faerger/billetpriser-sejeroefaergen (Havnsø ↔ Sejerø)',
    ports: { continental: [{ cc: 'DK', place: 'Havnsø', near: [55.75, 11.33] }], sejeroe: [{ cc: 'DK', place: 'Sejerby' }] } },
  { key: 'continental|furDk', source: 'https://furfaerge.dk/media/uinhhje2/takstblad-2026.pdf (Branden ↔ Fur)',
    ports: { continental: [{ cc: 'DK', place: 'Branden' }], furDk: [{ cc: 'DK', place: 'Nederby' }] } },
  { key: 'continental|fejoe', source: 'https://lollandfaergefart.lolland.dk/om-lolland-faergefart/priser (Kragenæs ↔ Fejø)',
    ports: { continental: [{ cc: 'DK', place: 'Kragenæs' }], fejoe: [{ cc: 'DK', place: 'Vesterby' }] } },
  { key: 'continental|femoe', source: 'https://lollandfaergefart.lolland.dk/om-lolland-faergefart/priser (Kragenæs ↔ Femø)',
    ports: { continental: [{ cc: 'DK', place: 'Kragenæs' }], femoe: [{ cc: 'DK', place: 'Sønderby' }] } },
  { key: 'askoe|continental', source: 'https://lollandfaergefart.lolland.dk/om-lolland-faergefart/priser (Bandholm ↔ Askø)',
    ports: { askoe: [{ cc: 'DK', place: 'Askø By' }], continental: [{ cc: 'DK', place: 'Bandholm' }] } },
  { key: 'continental|endelave', source: 'https://mf-endelave.dk/priseroginformation/priser2026 (Snaptun ↔ Endelave)',
    ports: { continental: [{ cc: 'DK', place: 'Snaptun' }], endelave: [{ cc: 'DK', place: 'Endelave By' }] } },
  { key: 'continental|oroe', source: 'https://holbaek.dk/service-og-selvbetjening/personlige-forhold/betaling-opkraevning-og-takster/takster/oroe-faergen (Holbæk ↔ Orø)',
    ports: { continental: [{ cc: 'DK', place: 'Holbæk', near: [55.72, 11.715] }], oroe: [{ cc: 'DK', place: 'Brønde' }] } },
  { key: 'continental|venoe', source: 'https://venoefaergefart.dk/en/ferry-service-prices/ (Kleppen ↔ Venø)',
    ports: { continental: [{ cc: 'DK', place: 'Bremdal' }], venoe: [{ cc: 'DK', place: 'Venø By' }] } },
  { key: 'agersoe|continental', source: 'https://aofaerger.slagelse.dk/da/priser/priser-for-agersoe-faergen-2026-pr-1-maj/ (Stigsnæs ↔ Agersø)',
    ports: { agersoe: [{ cc: 'DK', place: 'Agersø By' }], continental: [{ cc: 'DK', place: 'Stigsnæs' }] } },
  { key: 'continental|omoe', source: 'https://aofaerger.slagelse.dk/da/priser/priser-for-omoe-faergen-2026-pr-1-maj/ (Stigsnæs ↔ Omø)',
    ports: { continental: [{ cc: 'DK', place: 'Stigsnæs' }], omoe: [{ cc: 'DK', place: 'Omø By' }] } },
  { key: 'continental|egholm', source: 'https://www.aalborg.dk/mit-liv/trafik-og-parkering/trafik-og-veje/faerger-og-broer/egholmfaergen/ (Aalborg ↔ Egholm)',
    ports: { continental: [{ cc: 'DK', place: 'Aalborg' }], egholm: [{ cc: 'DK', place: 'Egholm' }] } },
  { key: 'continental|strynoe', source: 'https://langelandkommune.dk/p/Stryn%C3%B8-Rudk%C3%B8bing-f%C3%A6rgefart-Sejlplan-og-priser-06.01.2025.pdf (Rudkøbing ↔ Strynø)',
    ports: { continental: [{ cc: 'DK', place: 'Rudkøbing' }], strynoe: [{ cc: 'DK', place: 'Strynø By' }] } },
  { key: 'avernakoe|continental', source: 'https://oefaergen.fmk.dk/priser/priser/ (Faaborg ↔ Avernakø)',
    ports: { avernakoe: [{ cc: 'DK', place: 'Avernak By' }], continental: [{ cc: 'DK', place: 'Faaborg' }] } },
  { key: 'continental|lyoe', source: 'https://oefaergen.fmk.dk/priser/priser/ (Faaborg ↔ Lyø)',
    ports: { continental: [{ cc: 'DK', place: 'Faaborg' }], lyoe: [{ cc: 'DK', place: 'Lyø By' }] } },
  { key: 'continental|drejoe', source: 'https://www.svendborghavn.dk/da/faerger/billetpriser/ (Svendborg ↔ Drejø (via Skarø))',
    ports: { continental: [{ cc: 'DK', place: 'Svendborg' }], drejoe: [{ cc: 'DK', place: 'Drejø' }] } },
  { key: 'continental|skaroe', source: 'https://www.svendborghavn.dk/da/faerger/billetpriser/ (Svendborg ↔ Skarø)',
    ports: { continental: [{ cc: 'DK', place: 'Svendborg' }], skaroe: [{ cc: 'DK', place: 'Skarø By' }] } },
  { key: 'continental|hjarnoe', source: 'https://xn--hjarnfrgefart-8fb2y.dk/priser/ (Snaptun ↔ Hjarnø)',
    ports: { continental: [{ cc: 'DK', place: 'Snaptun' }], hjarnoe: [{ cc: 'DK', place: 'Hjarnø By' }] } },
  { key: 'baagoe|continental', source: 'https://www.assenshavn.dk/assens-baagoe-faergen/priser-baagoefaergen (Assens ↔ Bågø)',
    ports: { baagoe: [{ cc: 'DK', place: 'Østerklint' }], continental: [{ cc: 'DK', place: 'Assens', near: [55.27, 9.89] }] } },
  { key: 'barsoe|continental', source: 'https://aabenraa.dk/media/r03dszw1/takster-2026.pdf (Barsø Landing ↔ Barsø)',
    ports: { barsoe: [{ cc: 'DK', place: 'Barsø By' }], continental: [{ cc: 'DK', place: 'Brøde' }] } },
  { key: 'continental|sylt', source: 'https://www.syltshuttle.de/syltshuttle-de/fahrkarten/tarif_2023-2049320 (Niebüll ↔ Westerland (Sylt Shuttle))',
    ports: { continental: [{ cc: 'DE', place: 'Niebüll' }], sylt: [{ cc: 'DE', place: 'Westerland' }] } },
  { key: 'continental|foehr', source: 'https://www.faehre.de/faehrverkehr/preise/fahrzeuge (Dagebüll ↔ Wyk auf Föhr)',
    ports: { continental: [{ cc: 'DE', place: 'Dagebüll' }], foehr: [{ cc: 'DE', place: 'Wyk auf Föhr' }] } },
  { key: 'amrum|continental', source: 'https://www.faehre.de/faehrverkehr/preise/fahrzeuge (Dagebüll ↔ Wittdün (Amrum))',
    ports: { amrum: [{ cc: 'DE', place: 'Wittdün' }], continental: [{ cc: 'DE', place: 'Dagebüll' }] } },
  { key: 'amrum|foehr', source: 'https://www.faehre.de/faehrverkehr/preise/fahrzeuge (Wyk (Föhr) ↔ Wittdün (Amrum))',
    ports: { amrum: [{ cc: 'DE', place: 'Wittdün' }], foehr: [{ cc: 'DE', place: 'Wyk auf Föhr' }] } },
  { key: 'continental|pellworm', source: 'https://www.faehre-pellworm.de/faehrfahrten/fahrpreise (Strucklahnungshörn ↔ Pellworm)',
    ports: { continental: [{ cc: 'DE', place: 'Mitteldeich', near: [54.498, 8.807] }], pellworm: [{ cc: 'DE', place: 'Pellworm' }] } },
  { key: 'borkum|continental', source: 'https://www.ag-ems.de/tarife/ (Emden ↔ Borkum)',
    ports: { borkum: [{ cc: 'DE', place: 'Borkum' }], continental: [{ cc: 'DE', place: 'Emden', near: [53.36, 7.2] }] } },
  { key: 'continental|norderney', source: 'https://www.reederei-frisia.de/ (Norddeich ↔ Norderney)',
    ports: { continental: [{ cc: 'DE', place: 'Norddeich', near: [53.616, 7.161] }], norderney: [{ cc: 'DE', place: 'Norderney' }] } },
  { key: 'continental|saaremaa', source: 'https://www.praamid.ee/hinnad-ja-soodustused/ (Virtsu ↔ Kuivastu (Muhu/Saaremaa))',
    ports: { continental: [{ cc: 'EE', place: 'Virtsu', near: [58.575, 23.51] }], saaremaa: [{ cc: 'EE', place: 'Kuivastu' }] } },
  { key: 'continental|hiiumaa', source: 'https://www.praamid.ee/hinnad-ja-soodustused/ (Rohuküla ↔ Heltermaa (Hiiumaa))',
    ports: { continental: [{ cc: 'EE', place: 'Rohuküla', near: [58.906, 23.424] }], hiiumaa: [{ cc: 'EE', place: 'Heltermaa' }] } },
  { key: 'hiiumaa|saaremaa', source: 'https://www.riigiteataja.ee/akt/126042025008 (Sõru (Hiiumaa) ↔ Triigi (Saaremaa))',
    ports: { hiiumaa: [{ cc: 'EE', place: 'Sõru' }], saaremaa: [{ cc: 'EE', place: 'Triigi' }] } },
  { key: 'continental|vormsi', source: 'https://veeteed.com/ (Rohuküla ↔ Sviby (Vormsi))',
    ports: { continental: [{ cc: 'EE', place: 'Rohuküla', near: [58.906, 23.424] }], vormsi: [{ cc: 'EE', place: 'Sviby' }] } },
  { key: 'continental|kihnu', source: 'https://veeteed.com/ (Munalaid ↔ Kihnu)',
    ports: { continental: [{ cc: 'EE', place: 'Lao' }], kihnu: [{ cc: 'EE', place: 'Sääre' }] } },
  { key: 'continental|ruhnu', source: 'https://ruhnu.ee/vald-uudised-ja-kontakt/valla-info/transport-saarele/ (Pärnu ↔ Ruhnu)',
    ports: { continental: [{ cc: 'EE', place: 'Pärnu' }], ruhnu: [{ cc: 'EE', place: 'Ruhnu' }] } },
  { key: 'continental|neringa', source: 'https://www.keltas.lt/kainorastis/ (Klaipėda ↔ Smiltynė (isthme de Courlande))',
    ports: { continental: [{ cc: 'LT', place: 'Klaipėda' }], neringa: [{ cc: 'LT', place: 'Smiltynė' }] } },
  { key: 'continental|tysnes', source: 'https://www.vegvesen.no/globalassets/fag/trafikk/ferje/pris---autopass-regulativ---fullpris---01.01.2026.pdf (Halhjem ↔ Våge (Tysnes))',
    ports: { continental: [{ cc: 'NO', place: 'Haljem' }], tysnes: [{ cc: 'NO', place: 'Våge' }] } },
  { key: 'austevoll|continental', source: 'https://www.vegvesen.no/globalassets/fag/trafikk/ferje/pris---autopass-regulativ---fullpris---01.01.2026.pdf (Krokeide ↔ Hufthamar (Austevoll))',
    ports: { austevoll: [{ cc: 'NO', place: 'Hufthammar' }], continental: [{ cc: 'NO', place: 'Krokeide' }] } },
  { key: 'continental|huglo', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Jektevik ↔ Nordhuglo (Huglo))',
    ports: { continental: [{ cc: 'NO', place: 'Agdestein' }], huglo: [{ cc: 'NO', place: 'Nordhuglo' }] } },
  { key: 'continental|varaldsoy', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Gjermundshamn ↔ Varaldsøy)',
    ports: { continental: [{ cc: 'NO', place: 'Gjermundshamn' }], varaldsoy: [{ cc: 'NO', place: 'Skjelnes' }] } },
  { key: 'continental|fjelberg', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Sydnes ↔ Fjelberg)',
    ports: { continental: [{ cc: 'NO', place: 'Sundnes', near: [59.733, 5.738] }], fjelberg: [{ cc: 'NO', place: 'Fjelberg' }] } },
  { key: 'continental|kvitsoy', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Mekjarvik ↔ Kvitsøy)',
    ports: { continental: [{ cc: 'NO', place: 'Sande', near: [59.019, 5.621] }], kvitsoy: [{ cc: 'NO', place: 'Ydstebøhamn' }] } },
  { key: 'continental|utsira', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Haugesund ↔ Utsira)',
    ports: { continental: [{ cc: 'NO', place: 'Haugesund' }], utsira: [{ cc: 'NO', place: 'Utsira' }] } },
  { key: 'continental|ombo', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Ryfylkeferjen (Ombo)) ; https://havspor.no/en/stopp/eidssund-ferjekai (Fogn–Judaberg–Helgøy, escale Eidssund) ; https://havspor.no/en/stopp/nesvik-ferjekai (Hjelmeland–Nesvik–Skipavik)',
    ports: { continental: [{ cc: 'NO', place: 'Judaberg' }, { cc: 'NO', place: 'Nesvik' }, { cc: 'NO', place: 'Hjelmelandsvågen' }], ombo: [{ cc: 'NO', place: 'Eidssund' }, { cc: 'NO', place: 'Skor', near: [59.253, 6.095] }] } },
  { key: 'continental|hidra', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Launes ↔ Kvellandstrand (Hidra))',
    ports: { continental: [{ cc: 'NO', place: 'Myran', near: [58.237, 6.612] }], hidra: [{ cc: 'NO', place: 'Bukstad' }] } },
  { key: 'andabeloy|continental', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Abelnes ↔ Andabeløy)',
    ports: { andabeloy: [{ cc: 'NO', place: 'Andabeløy' }], continental: [{ cc: 'NO', place: 'Abelnes' }] } },
  { key: 'continental|skatoy', source: 'https://www.farte.no/reise/billetter-og-priser/fergebilletter/ (Kragerø ↔ Skåtøy)',
    ports: { continental: [{ cc: 'NO', place: 'Kragerø' }], skatoy: [{ cc: 'NO', place: 'Skåtøy' }] } },
  { key: 'continental|sandoyaPorsgrunn', source: 'https://www.farte.no/reise/billetter-og-priser/fergebilletter/ (Brevik ↔ Sandøya)',
    ports: { continental: [{ cc: 'NO', place: 'Brevik', near: [59.05, 9.7] }], sandoyaPorsgrunn: [{ cc: 'NO', place: 'Sandøya' }] } },
  { key: 'continental|fedje', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Sævrøy ↔ Fedje)',
    ports: { continental: [{ cc: 'NO', place: 'Rebnor' }], fedje: [{ cc: 'NO', place: 'Fedje' }] } },
  { key: 'continental|leroy', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Klokkarvik ↔ Lerøy)',
    ports: { continental: [{ cc: 'NO', place: 'Klokkarvik' }], leroy: [{ cc: 'NO', place: 'Lerøyna' }] } },
  // Rive « hisaroy » : quai OpenStreetMap relevé au 18e audit du 21/09/2026. Le seul lieu publié de l'île, Nyhamar,
  // avait alors été écarté par la règle des coordonnées à deux entiers (61,0000 ; 5,0000), privant la liaison de son
  // port ; le terminal a donc été relevé sur OpenStreetMap plutôt qu'inventé : nœud 4334643364 « Hisarøy »,
  // amenity=ferry_terminal, à 2,4 km d'Eivindvik, rangé sur la rive « hisaroy » par landmassOf.
  // 19e audit du 21/09/2026 : Nyhamar est restitué (corroboré par le code postal 5966, voir PLACEHOLDER_COORD_OK),
  // l'île est donc de nouveau atteignable. Le quai reste : il situe le terminal, là où le lieu ne donne que le centre
  // de la localité à une coordonnée arrondie au degré.
  { key: 'continental|hisaroy', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Mjånes ↔ Hisarøy)',
    ports: { continental: [{ cc: 'NO', place: 'Eivindvik' }],
             hisaroy: [{ cc: 'NO', name: 'Hisarøy', quay: { osm: 'node/4334643364', lat: 60.9973276, lon: 5.0172346 } }] } },
  { key: 'continental|solund', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Rutledal ↔ Krakhella (Solund))',
    ports: { continental: [{ cc: 'NO', place: 'Rutledal' }], solund: [{ cc: 'NO', place: 'Kråkhella' }] } },
  { key: 'continental|losna', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Rysjedalsvika/Rutledal ↔ Losna)',
    ports: { continental: [{ cc: 'NO', place: 'Sågnes' }, { cc: 'NO', place: 'Rutledal' }], losna: [{ cc: 'NO', place: 'Losnegard' }] } },
  { key: 'continental|vaerlandet', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Askvoll ↔ Værlandet)',
    ports: { continental: [{ cc: 'NO', place: 'Askvoll' }], vaerlandet: [{ cc: 'NO', place: 'Vikja' }] } },
  { key: 'atloy|continental', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Askvoll ↔ Gjervik (Atløy))',
    ports: { atloy: [{ cc: 'NO', place: 'Gjerdvik' }], continental: [{ cc: 'NO', place: 'Askvoll' }] } },
  { key: 'continental|husevagoy', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Måløy ↔ Husevågøy)',
    ports: { continental: [{ cc: 'NO', place: 'Måløy', near: [61.935, 5.11] }], husevagoy: [{ cc: 'NO', place: 'Tytingevågen' }] } },
  { key: 'barmoya|continental', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Barmsund ↔ Barmen)',
    ports: { barmoya: [{ cc: 'NO', place: 'Barmen Ytre' }], continental: [{ cc: 'NO', place: 'Gulestein' }] } },
  { key: 'continental|sandsoya', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Larsnes ↔ Voksa (Sandsøya)) ; https://havspor.no/en/stopp/voksa-ferjekai (Larsnes–Åram–Voksa–Kvamsøya)',
    ports: { continental: [{ cc: 'NO', place: 'Larsnes' }], sandsoya: [{ cc: 'NO', place: 'Sandshamn' }] } },
  { key: 'continental|sekken', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Molde ↔ Sekken)',
    ports: { continental: [{ cc: 'NO', place: 'Molde', near: [62.74, 7.16] }], sekken: [{ cc: 'NO', place: 'Skogvik' }] } },
  { key: 'continental|midsund', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Brattvåg ↔ Dryna (Midsund))',
    ports: { continental: [{ cc: 'NO', place: 'Brattvåg' }], midsund: [{ cc: 'NO', place: 'Dryna' }] } },
  { key: 'continental|gossa', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Hollingsholmen ↔ Aukra (Gossa))',
    ports: { continental: [{ cc: 'NO', place: 'Jendem' }], gossa: [{ cc: 'NO', place: 'Aukra' }] } },
  { key: 'continental|storfosna', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Garten ↔ Storfosna)',
    ports: { continental: [{ cc: 'NO', place: 'Garten' }], storfosna: [{ cc: 'NO', place: 'Nordlandet' }] } },
  { key: 'continental|leksa', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Garten ↔ Leksa)',
    ports: { continental: [{ cc: 'NO', place: 'Garten' }], leksa: [{ cc: 'NO', place: 'Sørleksa' }] } },
  { key: 'continental|sulaFroya', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Dyrøy ↔ Sula (Frøya))',
    ports: { continental: [{ cc: 'NO', place: 'Setra', near: [63.799, 8.681] }], sulaFroya: [{ cc: 'NO', place: 'Sula' }] } },
  { key: 'continental|mausund', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Dyrøy ↔ Mausund)',
    ports: { continental: [{ cc: 'NO', place: 'Setra', near: [63.799, 8.681] }], mausund: [{ cc: 'NO', place: 'Mausund' }] } },
  { key: 'continental|sorburoya', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Dyrøy ↔ Sørburøy)',
    ports: { continental: [{ cc: 'NO', place: 'Setra', near: [63.799, 8.681] }], sorburoya: [{ cc: 'NO', place: 'Sørburøy' }] } },
  { key: 'continental|ytteroya', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Levanger ↔ Hokstad (Ytterøya))',
    ports: { continental: [{ cc: 'NO', place: 'Levanger' }], ytteroya: [{ cc: 'NO', place: 'Hokstad' }] } },
  { key: 'continental|joa', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Ølhammeren ↔ Seierstad (Jøa))',
    ports: { continental: [{ cc: 'NO', place: 'Holvik', near: [64.636, 11.36] }], joa: [{ cc: 'NO', place: 'Dun' }] } },
  { key: 'continental|leka', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Gutvik ↔ Skei (Leka))',
    ports: { continental: [{ cc: 'NO', place: 'Gutvik' }], leka: [{ cc: 'NO', place: 'Huseby' }] } },
  { key: 'continental|torget', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Brønnøysund ↔ Sauren/Stortorgnes (Torget))',
    ports: { continental: [{ cc: 'NO', place: 'Brønnøysund' }], torget: [{ cc: 'NO', place: 'Tofte' }] } },
  { key: 'continental|donna', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Sandnessjøen ↔ Dønna)',
    ports: { continental: [{ cc: 'NO', place: 'Sandnessjøen' }], donna: [{ cc: 'NO', place: 'Dalsvåg' }] } },
  { key: 'continental|lokta', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Sandnessjøen ↔ Løkta)',
    ports: { continental: [{ cc: 'NO', place: 'Sandnessjøen' }], lokta: [{ cc: 'NO', place: 'Breidvik', near: [66.142, 12.697] }] } },
  { key: 'continental|vandve', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Solfjellsjøen ↔ Vandve)',
    ports: { continental: [{ cc: 'NO', place: 'Solfjellsjøen' }], vandve: [{ cc: 'NO', place: 'Store Vandve' }] } },
  { key: 'continental|hugla', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Nesna ↔ Hugla)',
    ports: { continental: [{ cc: 'NO', place: 'Nesna' }], hugla: [{ cc: 'NO', place: 'Nordbustad' }] } },
  { key: 'continental|tomma', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Nesna ↔ Tomma)',
    ports: { continental: [{ cc: 'NO', place: 'Nesna' }], tomma: [{ cc: 'NO', place: 'Skeivstad' }] } },
  { key: 'continental|onoy', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Stokkvågen ↔ Onøy)',
    ports: { continental: [{ cc: 'NO', place: 'Stokkvågen' }], onoy: [{ cc: 'NO', place: 'Demmahågen' }] } },
  { key: 'continental|lovund', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Stokkvågen ↔ Lovund)',
    ports: { continental: [{ cc: 'NO', place: 'Stokkvågen' }], lovund: [{ cc: 'NO', place: 'Lovund' }] } },
  { key: 'continental|traena', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Stokkvågen ↔ Træna)',
    ports: { continental: [{ cc: 'NO', place: 'Stokkvågen' }], traena: [{ cc: 'NO', place: 'Husøya' }] } },
  { key: 'continental|nesoyaRodoy', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Kilboghamn ↔ Nordnesøy)',
    ports: { continental: [{ cc: 'NO', place: 'Kilboghamn' }], nesoyaRodoy: [{ cc: 'NO', place: 'Nordnesøy' }] } },
  { key: 'continental|meloya', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Ørnes ↔ Meløysund)',
    ports: { continental: [{ cc: 'NO', place: 'Ørnes', near: [66.87, 13.7] }], meloya: [{ cc: 'NO', place: 'Fagervik', near: [66.831, 13.555] }] } },
  { key: 'bolga|continental', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Ørnes ↔ Bolga)',
    ports: { bolga: [{ cc: 'NO', place: 'Bolga' }], continental: [{ cc: 'NO', place: 'Ørnes', near: [66.87, 13.7] }] } },
  { key: 'continental|stott', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Ørnes ↔ Støtt)',
    ports: { continental: [{ cc: 'NO', place: 'Ørnes', near: [66.87, 13.7] }], stott: [{ cc: 'NO', place: 'Støtt' }] } },
  { key: 'arnoyGildeskal|continental', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Sund ↔ Sørarnøy)',
    ports: { arnoyGildeskal: [{ cc: 'NO', place: 'Sør-Arnøy' }], continental: [{ cc: 'NO', place: 'Sund', near: [67.073, 14.065] }] } },
  { key: 'continental|vaeroy', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Bodø ↔ Værøy)',
    ports: { continental: [{ cc: 'NO', place: 'Bodø' }], vaeroy: [{ cc: 'NO', place: 'Kvalnes' }] } },
  { key: 'continental|rost', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Bodø ↔ Røst)',
    ports: { continental: [{ cc: 'NO', place: 'Bodø' }], rost: [{ cc: 'NO', place: 'Røst' }] } },
  { key: 'continental|vengsoya', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Bellvik ↔ Vengsøy)',
    ports: { continental: [{ cc: 'NO', place: 'Bellvika' }], vengsoya: [{ cc: 'NO', place: 'Vengsøya', near: [69.837, 18.587] }] } },
  { key: 'continental|rebbenesoya', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Mikkelvik ↔ Bromnes (Rebbenesøy))',
    ports: { continental: [{ cc: 'NO', place: 'Hornet', near: [70.061, 19.039] }], rebbenesoya: [{ cc: 'NO', place: 'Løksfjord' }] } },
  { key: 'continental|karlsoy', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Hansnes ↔ Karlsøy)',
    ports: { continental: [{ cc: 'NO', place: 'Hansnes' }], karlsoy: [{ cc: 'NO', place: 'Karlsøy' }] } },
  { key: 'continental|vannoya', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Hansnes ↔ Vannøy)',
    ports: { continental: [{ cc: 'NO', place: 'Hansnes' }], vannoya: [{ cc: 'NO', place: 'Lanasøren' }] } },
  { key: 'continental|reinoya', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Hansnes ↔ Stakkvik (Reinøy))',
    ports: { continental: [{ cc: 'NO', place: 'Hansnes' }], reinoya: [{ cc: 'NO', place: 'Stakkvik' }] } },
  // Deux liaisons dont la rive de départ était mal définie (continent au lieu de Saaremaa et de Gossa), corrigées dans
  // scripts/iles/iles-baltique.js. Quais situés d'après OpenStreetMap (Småge ferjekai 62,807 N 6,768 E ; Finnøya ferjekai
  // 62,804 N 6,509 E) : localités retenues Horrem (0,7 km) et Finnøy (0,6 km).
  { key: 'abruka|saaremaa', source: 'https://www.saaremaavald.ee/uhistransport (Roomassaare ↔ Abruka)',
    ports: { saaremaa: [{ cc: 'EE', place: 'Roomassaare' }], abruka: [{ cc: 'EE', place: 'Abruka' }] } },
  { key: 'finnoyaAlesund|gossa', source: 'https://autopassferje.no/en/free-ferries-from-july-1st-2022/ (Småge ↔ Finnøya)',
    ports: { gossa: [{ cc: 'NO', place: 'Horrem' }], finnoyaAlesund: [{ cc: 'NO', place: 'Finnøy' }] } },
  // Six liaisons de passagers ajoutées le 23/09/2026 : quand le quai n'est pas publié sous son nom, le lieu retenu est
  // la localité la plus proche du terminal sur la bonne rive (near = position du quai, pour lever les homonymes).
  { key: 'guadeloupe|marieGalante', source: 'https://www.frs-express.com/en/timetable-rates/marie-galante-departing-from-pointe-a-pitre-timetables-f (Pointe-à-Pitre (Bergevin) ↔ Grand-Bourg)',
    ports: { guadeloupe: [{ cc: 'FR', place: 'Pointe-à-Pitre' }], marieGalante: [{ cc: 'FR', place: 'Grand-Bourg' }] } },
  { key: 'ambergrisCaye|northAmerica', source: 'https://belizewatertaxi.com/destinations/san-pedro/ (Belize City ↔ San Pedro)',
    ports: { ambergrisCaye: [{ cc: 'BZ', place: 'San Pedro', near: [17.916, -87.966] }], northAmerica: [{ cc: 'BZ', place: 'Belize City' }] } },
  { key: 'buyukada|continental', source: 'https://sehirhatlari.istanbul/en/timetables/domestic-trips/adalar-princes-islands-lines/kabatas-adalar-177 (İstanbul ↔ Büyükada)',
    ports: { buyukada: [{ cc: 'TR', place: 'Adalar' }], continental: [{ cc: 'TR', place: 'İstanbul' }] } },
  // Le quai de Boracay est à Cagban, dans le barangay Manoc-Manoc : c'est le lieu publié le plus proche du terminal.
  { key: 'boracay|panay', source: 'https://www.boracayipass.ph/ (Caticlan Seaport ↔ Cagban Seaport)',
    ports: { boracay: [{ cc: 'PH', place: 'Manoc-Manoc' }], panay: [{ cc: 'PH', place: 'Caticlan' }] } },
  { key: 'continental|phuQuy', source: 'https://online.superdong.com.vn/Home/ScheduleBoat (Phan Thiết ↔ Phú Quý)',
    ports: { continental: [{ cc: 'VN', place: 'Phan Thiết' }], phuQuy: [{ cc: 'VN', place: 'Phú Quý', near: [10.5166, 108.9329] }] } },
  // Le terminal de Sa Kỳ n'est pas publié sous ce nom : Châu Bình est le lieu publié le plus proche du quai (1,9 km).
  { key: 'continental|lySon', source: 'https://cangsaky.com.vn/ (Sa Kỳ ↔ Bến Đình (Lý Sơn))',
    ports: { continental: [{ cc: 'VN', place: 'Châu Bình', near: [15.2417, 108.8842] }], lySon: [{ cc: 'VN', place: 'Lý Sơn' }] } },
  // Ligne internationale FRS Express des Îles (Guadeloupe – Dominique – Martinique – Sainte-Lucie).
  // Le terminal de Castries n'est pas publié sous son nom : Castries même est le lieu le plus proche (2,7 km).
  { key: 'guadeloupe|martinique', source: 'https://www.frs-express.com/en/timetable-rates/martinique-timetables-fares (Pointe-à-Pitre (Bergevin) ↔ Fort-de-France)',
    ports: { guadeloupe: [{ cc: 'FR', place: 'Pointe-à-Pitre' }], martinique: [{ cc: 'FR', place: 'Fort-de-France' }] } },
  { key: 'dominica|guadeloupe', source: 'https://www.frs-express.com/en/timetable-rates/dominica-timetables-fares (Pointe-à-Pitre (Bergevin) ↔ Roseau)',
    ports: { dominica: [{ cc: 'DM', place: 'Roseau' }], guadeloupe: [{ cc: 'FR', place: 'Pointe-à-Pitre' }] } },
  { key: 'dominica|martinique', source: 'https://www.frs-express.com/en/timetable-rates/dominica-timetables-fares (Fort-de-France ↔ Roseau)',
    ports: { dominica: [{ cc: 'DM', place: 'Roseau' }], martinique: [{ cc: 'FR', place: 'Fort-de-France' }] } },
  { key: 'martinique|saintLucia', source: 'https://www.frs-express.com/en/timetable-rates/saint-lucia-timetables-fares (Fort-de-France ↔ Castries)',
    ports: { martinique: [{ cc: 'FR', place: 'Fort-de-France' }], saintLucia: [{ cc: 'LC', place: 'Castries' }] } },
  // Bahamas : les trois escales du Bo Hengy III sont publiées sous leur nom (Dunmore Town pour Harbour Island).
  { key: 'newProvidence|spanishWells', source: 'https://bahamasferries.com/your-travel/ (Nassau ↔ Spanish Wells)',
    ports: { newProvidence: [{ cc: 'BS', place: 'Nassau', near: [25.0582, -77.3431] }], spanishWells: [{ cc: 'BS', place: 'Spanish Wells' }] } },
  { key: 'harbourIsland|spanishWells', source: 'https://bahamasferries.com/your-travel/ (Spanish Wells ↔ Harbour Island)',
    ports: { harbourIsland: [{ cc: 'BS', place: 'Dunmore Town' }], spanishWells: [{ cc: 'BS', place: 'Spanish Wells' }] } },
  { key: 'harbourIsland|newProvidence', source: 'https://bahamasferries.com/your-travel/ (Nassau ↔ Harbour Island)',
    ports: { harbourIsland: [{ cc: 'BS', place: 'Dunmore Town' }], newProvidence: [{ cc: 'BS', place: 'Nassau', near: [25.0582, -77.3431] }] } },
  { key: 'lanai|maui', source: "https://go-lanai.com/ (Mā’alaea ↔ Mānele)",
    ports: { lanai: [{ cc: 'US', place: 'Lanai City' }], maui: [{ cc: 'US', place: 'Mā‘alaea' }] } },
  { key: 'antigua|barbuda', source: 'https://seabridgeferries.com/ (Antigua ↔ Barbuda)',
    ports: { antigua: [{ cc: 'AG', place: 'Saint John’s' }], barbuda: [{ cc: 'AG', place: 'Codrington' }] } },
  { key: 'saintCroix|saintThomasVI', source: 'https://qe4ferry.com/services/ (Gallows Bay ↔ Blyden Terminal)',
    ports: { saintCroix: [{ cc: 'VI', place: 'Christiansted' }], saintThomasVI: [{ cc: 'VI', place: 'Charlotte Amalie' }] } },
  { key: 'grandBahama|northAmerica', source: 'https://www.baleariacaribbean.com/en/fort-lauderdale-grand-bahama (Port Everglades ↔ Freeport)',
    ports: { grandBahama: [{ cc: 'BS', place: 'Freeport', near: [26.5333, -78.7] }], northAmerica: [{ cc: 'US', place: 'Fort Lauderdale' }] } },
  // Le quai de Marigot n'est pas publié : St. Peters est le lieu publié le plus proche (2,2 km).
  { key: 'anguilla|saintMartinFR', source: 'https://www.portdemarigot.com/en/gare (Marigot ↔ Blowing Point)',
    ports: { anguilla: [{ cc: 'AI', place: 'Blowing Point Village' }], saintMartinFR: [{ cc: 'SX', place: 'St. Peters', near: [18.0689, -63.0833] }] } },
  // Le quai de Trần Đề n'est pas publié : Kinh Ba est le lieu publié le plus proche (0,8 km).
  { key: 'conDao|continental', source: 'https://online.superdong.com.vn/Home/ScheduleBoat (Sóc Trăng ↔ Côn Đảo)',
    ports: { conDao: [{ cc: 'VN', place: 'Côn Đảo' }], continental: [{ cc: 'VN', place: 'Kinh Ba', near: [9.5167, 106.2] }] } },
  { key: 'efate|santo', source: 'https://www.vanuatu.travel/en/big-sista (Port-Vila ↔ Luganville)',
    ports: { efate: [{ cc: 'VU', place: 'Port-Vila' }], santo: [{ cc: 'VU', place: 'Luganville' }] } },
  // Le quai de Heaving Down Rock (pointe est de Providenciales) n'est pas publié : The Bight Settlements est le
  // lieu publié le plus proche sur cette rive, à 18 km.
  { key: 'northMiddleCaicos|providenciales', source: 'https://caribbeancruisin.com/tci-ferry-schedule/ (Heaving Down Rock ↔ Sandy Point)',
    ports: { northMiddleCaicos: [{ cc: 'TC', place: 'Sandy Point', near: [21.9393, -72.038] }], providenciales: [{ cc: 'TC', place: 'The Bight Settlements' }] } },
  { key: 'saintThomasVI|tortola', source: 'https://www.roadtownfastferry.com/ (Charlotte Amalie ↔ Road Town)',
    ports: { saintThomasVI: [{ cc: 'VI', place: 'Charlotte Amalie' }], tortola: [{ cc: 'VG', place: 'Road Town' }] } },
  { key: 'greatBritain|scillyStMarys', source: "https://www.islesofscilly-travel.co.uk/ferry/route/ (Penzance ↔ St Mary's)",
    ports: { greatBritain: [{ cc: 'GB', place: 'Penzance' }], scillyStMarys: [{ cc: 'GB', place: 'Hugh Town' }] } },
  { key: 'continental|juist', source: 'https://www.inselfaehre.de/juist (Norddeich-Mole ↔ Juist)',
    ports: { continental: [{ cc: 'DE', place: 'Norddeich', near: [53.6135, 7.1604] }], juist: [{ cc: 'DE', place: 'Juist' }] } },
  // Îles des Princes : chaque île n'a qu'un lieu publié (Heybeliada, Burgaz, Kınalı).
  { key: 'continental|heybeliada', source: 'https://sehirhatlari.istanbul/en/timetables/domestic-trips/adalar-princes-islands-lines/kabatas-adalar-177 (İstanbul ↔ Heybeliada)',
    ports: { continental: [{ cc: 'TR', place: 'İstanbul' }], heybeliada: [{ cc: 'TR', place: 'Heybeliada' }] } },
  { key: 'burgazada|continental', source: 'https://sehirhatlari.istanbul/en/timetables/domestic-trips/adalar-princes-islands-lines/kabatas-adalar-177 (İstanbul ↔ Burgazada)',
    ports: { burgazada: [{ cc: 'TR', place: 'Burgaz', near: [40.8826, 29.065] }], continental: [{ cc: 'TR', place: 'İstanbul' }] } },
  { key: 'continental|kinaliada', source: 'https://sehirhatlari.istanbul/en/timetables/domestic-trips/adalar-princes-islands-lines/kabatas-adalar-177 (İstanbul ↔ Kınalıada)',
    ports: { continental: [{ cc: 'TR', place: 'İstanbul' }], kinaliada: [{ cc: 'TR', place: 'Kınalı', near: [40.9071, 29.055] }] } },
  { key: 'tortola|virginGorda', source: 'https://www.speedysbvi.com/ferry-rates (Road Town ↔ Spanish Town)',
    ports: { tortola: [{ cc: 'VG', place: 'Road Town' }], virginGorda: [{ cc: 'VG', place: 'Spanish Town' }] } },
  { key: 'guanaja|roatan', source: 'https://www.roatanferry.com/schedule-fares/ (Roatán ↔ Guanaja)',
    ports: { guanaja: [{ cc: 'HN', place: 'Savannah Bight' }], roatan: [{ cc: 'HN', place: 'Coxen Hole' }] } },
  // Makana Ferry : Fort Bay est au sud de The Bottom, le lieu publié le plus proche sur Saba.
  { key: 'saba|saintMartinFR', source: 'https://www.sabaferry.com/makana (Fort Bay ↔ Bobby\'s Marina, Philipsburg)',
    ports: { saba: [{ cc: 'BQ', place: 'The Bottom' }], saintMartinFR: [{ cc: 'SX', place: 'Philipsburg' }] } },
  { key: 'saintMartinFR|sintEustatius', source: 'https://www.sabaferry.com/makana (Bobby\'s Marina ↔ Gallow\'s Bay)',
    ports: { saintMartinFR: [{ cc: 'SX', place: 'Philipsburg' }], sintEustatius: [{ cc: 'BQ', place: 'Oranjestad', near: [17.483, -62.9864] }] } },
  { key: 'saba|sintEustatius', source: 'https://www.sabaferry.com/makana (Fort Bay ↔ Gallow\'s Bay)',
    ports: { saba: [{ cc: 'BQ', place: 'The Bottom' }], sintEustatius: [{ cc: 'BQ', place: 'Oranjestad', near: [17.483, -62.9864] }] } },
  { key: 'guadeloupe|terreDeHaut', source: 'https://www.frs-express.com/en/timetable-rates/les-saintes-from-trois-rivieres-timetables-fares (Trois-Rivières ↔ Terre-de-Haut)',
    ports: { guadeloupe: [{ cc: 'FR', place: 'Trois-Rivières', near: [15.9931, -61.6493] }], terreDeHaut: [{ cc: 'FR', place: 'Terre-de-Haut' }] } },
  { key: 'guadeloupe|terreDeBas', source: 'https://www.frs-express.com/en/timetable-rates/les-saintes-from-trois-rivieres-timetables-fares (Trois-Rivières ↔ Terre-de-Bas)',
    ports: { guadeloupe: [{ cc: 'FR', place: 'Trois-Rivières', near: [15.9931, -61.6493] }], terreDeBas: [{ cc: 'FR', place: 'Terre-de-Bas' }] } },
  { key: 'continental|wadden-vlieland', source: 'https://www.rederij-doeksen.nl/tarieven/tarieven-voor-personen (Harlingen ↔ Vlieland)',
    ports: { continental: [{ cc: 'NL', place: 'Harlingen' }], 'wadden-vlieland': [{ cc: 'NL', place: 'Oost-Vlieland' }] } },
  { key: 'continental|wadden-schiermonnikoog', source: 'https://www.wpd.nl/tarieven-schiermonnikoog (Lauwersoog ↔ Schiermonnikoog)',
    ports: { continental: [{ cc: 'NL', place: 'Lauwersoog' }], 'wadden-schiermonnikoog': [{ cc: 'NL', place: 'Schiermonnikoog' }] } },
  { key: 'continental|ouessant', source: 'https://pennarbed.breizhgo.bzh/tarifs (Le Conquet ↔ Ouessant)',
    ports: { continental: [{ cc: 'FR', place: 'Le Conquet' }], ouessant: [{ cc: 'FR', place: 'Ouessant' }] } },
  { key: 'continental|wangerooge', source: 'https://www.siw-wangerooge.de/siw-de (Harlesiel ↔ Wangerooge)',
    ports: { continental: [{ cc: 'DE', place: 'Harlesiel' }], wangerooge: [{ cc: 'DE', place: 'Nordseeheilbad Wangerooge' }] } },
  { key: 'continental|hiddensee', source: 'https://www.reederei-hiddensee.de/en/timetable/schaprode (Schaprode ↔ Vitte)',
    ports: { continental: [{ cc: 'DE', place: 'Schaprode' }], hiddensee: [{ cc: 'DE', place: 'Vitte', near: [54.5674, 13.1061] }] } },
  // Huit îles sans voitures ajoutées le 23/09/2026. Quand le quai n'est pas publié, le lieu retenu est la
  // localité la plus proche sur la bonne rive (l'Arcouest -> Ploubazlanec, la pointe de la Fumée -> Fouras).
  { key: 'continental|ileDArz', source: 'https://www.mairie-iledarz.fr/decouvrir-lile-darz/acces-et-traversee/ (Vannes ↔ Île-d\'Arz)',
    ports: { continental: [{ cc: 'FR', place: 'Vannes', near: [47.6577, -2.7485] }], ileDArz: [{ cc: 'FR', place: "Île-d'Arz" }] } },
  { key: 'batz|continental', source: 'https://www.vedettes-ile-de-batz.com/ (Roscoff ↔ Île-de-Batz)',
    ports: { batz: [{ cc: 'FR', place: 'Île-de-Batz' }], continental: [{ cc: 'FR', place: 'Roscoff' }] } },
  { key: 'brehat|continental', source: 'https://www.vedettesdebrehat.com/ (Arcouest ↔ Bréhat)',
    ports: { brehat: [{ cc: 'FR', place: 'Île-de-Bréhat' }], continental: [{ cc: 'FR', place: 'Ploubazlanec' }] } },
  { key: 'continental|houat', source: 'https://www.mairiedehouat.fr/comment-venir-sur-lile/ (Quiberon ↔ Houat)',
    ports: { continental: [{ cc: 'FR', place: 'Quiberon' }], houat: [{ cc: 'FR', place: "Île-d'Houat" }] } },
  { key: 'continental|molene', source: 'https://www.iroise-bretagne.bzh/ (Le Conquet ↔ Molène)',
    ports: { continental: [{ cc: 'FR', place: 'Le Conquet' }], molene: [{ cc: 'FR', place: 'Île-Molène' }] } },
  { key: 'continental|ileDAix', source: 'https://www.liaison-maritime-fouras-aix.com/horaires/ (Fouras ↔ Île-d\'Aix)',
    ports: { continental: [{ cc: 'FR', place: 'Fouras' }], ileDAix: [{ cc: 'FR', place: "Île-d'Aix" }] } },
  { key: 'guadeloupe|laDesirade', source: 'https://www.guadeloupeauthentique.com/ (Saint-François ↔ La Désirade)',
    ports: { guadeloupe: [{ cc: 'FR', place: 'Saint-François', near: [16.2784, -61.2539] }], laDesirade: [{ cc: 'FR', place: 'La Désirade' }] } },
  { key: 'laGraciosa|lanzarote', source: 'https://www.visitlagraciosa.com/en/ferry-lanzarote-la-graciosa/ (Órzola ↔ Caleta de Sebo)',
    ports: { laGraciosa: [{ cc: 'ES', place: 'Caleta de Sebo' }], lanzarote: [{ cc: 'ES', place: 'Órzola' }] } },
  // Lot de COUVERTURE du 23/09/2026 (voir scripts/iles/iles-couverture.js).
  { key: 'continental|prvic', source: 'https://www.jadrolinija.hr/en/travels (Šibenik ↔ Prvić Šepurine)',
    ports: { 'continental': [{ cc: 'HR', place: "Šibenik", near: [43.7350, 15.8952] }], 'prvic': [{ cc: 'HR', place: "Prvić Šepurine" }] } },
  { key: 'continental|zlarin', source: 'https://www.jadrolinija.hr/en/travels (Šibenik ↔ Zlarin)',
    ports: { 'continental': [{ cc: 'HR', place: "Šibenik", near: [43.7350, 15.8952] }], 'zlarin': [{ cc: 'HR', place: "Zlarin" }] } },
  { key: 'continental|kaprije', source: 'https://www.jadrolinija.hr/en/travels (Šibenik ↔ Kaprije)',
    ports: { 'continental': [{ cc: 'HR', place: "Šibenik", near: [43.7350, 15.8952] }], 'kaprije': [{ cc: 'HR', place: "Kaprije" }] } },
  { key: 'continental|krapanj', source: 'https://www.jadrolinija.hr/en/travels (Brodarica ↔ Krapanj)',
    ports: { 'continental': [{ cc: 'HR', place: "Brodarica", near: [43.6889, 15.8886] }], 'krapanj': [{ cc: 'HR', place: "Krapanj" }] } },
  { key: 'continental|vrgada', source: 'https://www.jadrolinija.hr/en/travels (Pakoštane ↔ Vrgada)',
    ports: { 'continental': [{ cc: 'HR', place: "Pakoštane" }], 'vrgada': [{ cc: 'HR', place: "Vrgada" }] } },
  { key: 'continental|silba', source: 'https://www.jadrolinija.hr/en/travels (Zadar ↔ Silba)',
    ports: { 'continental': [{ cc: 'HR', place: "Zadar" }], 'silba': [{ cc: 'HR', place: "Silba" }] } },
  { key: 'continental|lopud', source: 'https://www.jadrolinija.hr/en/travels (Dubrovnik ↔ Lopud)',
    ports: { 'continental': [{ cc: 'HR', place: "Dubrovnik" }], 'lopud': [{ cc: 'HR', place: "Lopud" }] } },
  { key: 'continental|kolocep', source: 'https://www.jadrolinija.hr/en/travels (Dubrovnik ↔ Koločep)',
    ports: { 'continental': [{ cc: 'HR', place: "Dubrovnik" }], 'kolocep': [{ cc: 'HR', place: "Koločep" }] } },
  { key: 'cres|susak', source: 'https://www.jadrolinija.hr/en/travels (Mali Lošinj ↔ Susak)',
    ports: { 'cres': [{ cc: 'HR', place: "Mali Lošinj" }], 'susak': [{ cc: 'HR', place: "Susak" }] } },
  { key: 'cres|unije', source: 'https://www.jadrolinija.hr/en/travels (Mali Lošinj ↔ Unije)',
    ports: { 'cres': [{ cc: 'HR', place: "Mali Lošinj" }], 'unije': [{ cc: 'HR', place: "Unije" }] } },
  { key: 'cres|ilovik', source: 'https://www.jadrolinija.hr/en/travels (Mali Lošinj ↔ Ilovik)',
    ports: { 'cres': [{ cc: 'HR', place: "Mali Lošinj" }], 'ilovik': [{ cc: 'HR', place: "Ilovik" }] } },
  { key: 'bisevo|vis', source: 'https://www.jadrolinija.hr/en/travels (Komiža ↔ Biševo)',
    ports: { 'bisevo': [{ cc: 'HR', place: "Biševo" }], 'vis': [{ cc: 'HR', place: "Komiža" }] } },
  { key: 'continental|spetses', source: 'https://en.wikipedia.org/wiki/Spetses (Kósta ↔ Spétses)',
    ports: { 'continental': [{ cc: 'GR', place: "Kósta" }], 'spetses': [{ cc: 'GR', place: "Spétses" }] } },
  { key: 'continental|hydra', source: 'https://en.wikipedia.org/wiki/Hydra_(island) (Ermióni ↔ Ýdra)',
    ports: { 'continental': [{ cc: 'GR', place: "Ermióni" }], 'hydra': [{ cc: 'GR', place: "Ýdra" }] } },
  { key: 'continental|kalamos', source: 'https://en.wikipedia.org/wiki/Kalamos_(island) (Mýtikas ↔ Kálamos)',
    ports: { 'continental': [{ cc: 'GR', place: "Mýtikas", near: [38.6667, 20.95] }], 'kalamos': [{ cc: 'GR', place: "Kálamos" }] } },
  { key: 'continental|kastos', source: 'https://en.wikipedia.org/wiki/Kastos (Mýtikas ↔ Kastós)',
    ports: { 'continental': [{ cc: 'GR', place: "Mýtikas", near: [38.6667, 20.95] }], 'kastos': [{ cc: 'GR', place: "Kastós" }] } },
  { key: 'kalymnos|telendos', source: 'https://en.wikipedia.org/wiki/Telendos (Myrtiés ↔ Télendos)',
    ports: { 'kalymnos': [{ cc: 'GR', place: "Myrtiés" }], 'telendos': [{ cc: 'GR', place: "Télendos" }] } },
  { key: 'iona|mull', source: 'https://www.calmac.co.uk/ (Fionnphort ↔ Iona)',
    ports: { 'iona': [{ cc: 'GB', place: "Isle of Iona" }], 'mull': [{ cc: 'GB', place: "Fionnphort" }] } },
  { key: 'eigg|greatBritain', source: 'https://www.calmac.co.uk/ (Mallaig ↔ Eigg)',
    ports: { 'eigg': [{ cc: 'GB', place: "Isle of Eigg" }], 'greatBritain': [{ cc: 'GB', place: "Mallaig" }] } },
  { key: 'greatBritain|rum', source: 'https://www.calmac.co.uk/ (Mallaig ↔ Rum)',
    ports: { 'greatBritain': [{ cc: 'GB', place: "Mallaig" }], 'rum': [{ cc: 'GB', place: "Isle of Rum" }] } },
  { key: 'scillyStMarys|scillyTresco', source: 'https://www.scillyboating.co.uk/ (Hugh Town ↔ Tresco)',
    ports: { 'scillyStMarys': [{ cc: 'GB', place: "Hugh Town" }], 'scillyTresco': [{ cc: 'GB', place: "Tresco" }] } },
  { key: 'scillyStMartins|scillyStMarys', source: "https://www.scillyboating.co.uk/ (Hugh Town ↔ St Martin’s)",
    ports: { 'scillyStMartins': [{ cc: 'GB', place: "St Martin's" }], 'scillyStMarys': [{ cc: 'GB', place: "Hugh Town" }] } },
  { key: 'scillyBryher|scillyStMarys', source: 'https://www.scillyboating.co.uk/ (Hugh Town ↔ Bryher)',
    ports: { 'scillyBryher': [{ cc: 'GB', place: "Bryher" }], 'scillyStMarys': [{ cc: 'GB', place: "Hugh Town" }] } },
  { key: 'scillyStAgnes|scillyStMarys', source: 'https://www.scillyboating.co.uk/ (Hugh Town ↔ St Agnes)',
    ports: { 'scillyStAgnes': [{ cc: 'GB', place: "St Agnes" }], 'scillyStMarys': [{ cc: 'GB', place: "Hugh Town" }] } },
  { key: 'continental|langeness', source: 'https://www.faehre.de/ (Schlüttsiel ↔ Langeneß)',
    ports: { 'continental': [{ cc: 'DE', place: "Schlüttsiel" }], 'langeness': [{ cc: 'DE', place: "Langeneß" }] } },
  { key: 'continental|hooge', source: 'https://www.faehre.de/ (Schlüttsiel ↔ Hooge)',
    ports: { 'continental': [{ cc: 'DE', place: "Schlüttsiel" }], 'hooge': [{ cc: 'DE', place: "Hooge" }] } },
  { key: 'baltrum|continental', source: 'https://www.baltrum-linie.de/ (Neßmersiel ↔ Baltrum)',
    ports: { 'baltrum': [{ cc: 'DE', place: "Baltrum" }], 'continental': [{ cc: 'DE', place: "Neßmersiel" }] } },
  { key: 'continental|sein', source: 'https://pennarbed.breizhgo.bzh/ (Audierne ↔ Île-de-Sein)',
    ports: { 'continental': [{ cc: 'FR', place: "Audierne" }], 'sein': [{ cc: 'FR', place: "Île-de-Sein" }] } },
  { key: 'continental|hoedic', source: 'https://www.compagnie-oceane.fr/ (Quiberon ↔ Hœdic)',
    ports: { 'continental': [{ cc: 'FR', place: "Quiberon" }], 'hoedic': [{ cc: 'FR', place: "Hœdic" }] } },
  { key: 'continental|monteIsola', source: 'https://www.navigazionelagoiseo.it/ (Sulzano ↔ Monte Isola)',
    ports: { 'continental': [{ cc: 'IT', place: "Sulzano" }], 'monteIsola': [{ cc: 'IT', place: "Siviano" }] } },
  { key: 'continental|tremiti', source: 'https://en.wikipedia.org/wiki/Tremiti_Islands (Termoli ↔ Isole Tremiti)',
    ports: { 'continental': [{ cc: 'IT', place: "Termoli" }], 'tremiti': [{ cc: 'IT', place: "Isole Tremiti" }] } },
  { key: 'sicily|stromboli', source: 'https://www.libertylines.it/ (Milazzo ↔ Stromboli)',
    ports: { 'sicily': [{ cc: 'IT', place: "Milazzo" }], 'stromboli': [{ cc: 'IT', place: "Stromboli" }] } },
  { key: 'panarea|sicily', source: 'https://www.libertylines.it/ (Milazzo ↔ Panarea)',
    ports: { 'panarea': [{ cc: 'IT', place: "Panarea" }], 'sicily': [{ cc: 'IT', place: "Milazzo" }] } },
  { key: 'faial|floresAzores', source: 'https://www.atlanticoline.pt/ (Horta ↔ Lajes das Flores)',
    ports: { 'faial': [{ cc: 'PT', place: "Horta" }], 'floresAzores': [{ cc: 'PT', place: "Lajes das Flores" }] } },
  { key: 'corvo|floresAzores', source: 'https://www.atlanticoline.pt/ (Lajes das Flores ↔ Vila do Corvo)',
    ports: { 'corvo': [{ cc: 'PT', place: "Vila do Corvo" }], 'floresAzores': [{ cc: 'PT', place: "Lajes das Flores" }] } },
  { key: 'continental|ven', source: 'https://www.ventrafiken.se/ (Landskrona ↔ Ven)',
    ports: { 'continental': [{ cc: 'SE', place: "Landskrona" }], 'ven': [{ cc: 'SE', place: "Tuna" }] } },
  { key: 'continental|prangli', source: 'https://en.wikipedia.org/wiki/Prangli (Leppneeme ↔ Prangli)',
    ports: { 'continental': [{ cc: 'EE', place: "Leppneeme" }], 'prangli': [{ cc: 'EE', place: "Kelnase" }] } },
  // Lot de COUVERTURE, passe 2 (hors Europe).
  { key: 'anjouan|grandeComore', source: 'https://en.wikipedia.org/wiki/Transport_in_the_Comoros (Moroni ↔ Mutsamudu)',
    ports: { 'anjouan': [{ cc: 'KM', place: "Moutsamoudou" }], 'grandeComore': [{ cc: 'KM', place: "Moroni" }] } },
  { key: 'anjouan|moheli', source: 'https://en.wikipedia.org/wiki/Transport_in_the_Comoros (Mutsamudu ↔ Fomboni)',
    ports: { 'anjouan': [{ cc: 'KM', place: "Moutsamoudou" }], 'moheli': [{ cc: 'KM', place: "Fomboni" }] } },
  { key: 'grandeComore|moheli', source: 'https://en.wikipedia.org/wiki/Transport_in_the_Comoros (Moroni ↔ Fomboni)',
    ports: { 'grandeComore': [{ cc: 'KM', place: "Moroni" }], 'moheli': [{ cc: 'KM', place: "Fomboni" }] } },
  { key: 'mahe|praslin', source: 'https://www.catcocos.com/ (Victoria (Mahé) ↔ Baie Sainte-Anne (Praslin))',
    ports: { 'mahe': [{ cc: 'SC', place: "Victoria" }], 'praslin': [{ cc: 'SC', place: "Baie Sainte Anne" }] } },
  { key: 'laDigue|praslin', source: 'https://www.catcocos.com/ (Praslin ↔ La Digue)',
    ports: { 'laDigue': [{ cc: 'SC', place: "La Digue" }], 'praslin': [{ cc: 'SC', place: "Baie Sainte Anne" }] } },
  { key: 'continental|lamu', source: 'https://en.wikipedia.org/wiki/Lamu (Mokowe ↔ Lamu)',
    ports: { 'continental': [{ cc: 'KE', place: "Mokowe" }], 'lamu': [{ cc: 'KE', place: "Lamu" }] } },
  { key: 'continental|sainteMarie', source: 'https://en.wikipedia.org/wiki/Nosy_Boraha (Soanierana-Ivongo ↔ Ambodifotatra)',
    ports: { 'continental': [{ cc: 'MG', place: "Soanierana Ivongo" }], 'sainteMarie': [{ cc: 'MG', place: "Ambodifotatra" }] } },
  { key: 'providencia|sanAndres', source: 'https://en.wikipedia.org/wiki/Providencia_Island (San Andrés ↔ Providencia)',
    ports: { 'providencia': [{ cc: 'CO', place: "Santa Isabel", near: [13.3781, -81.3736] }], 'sanAndres': [{ cc: 'CO', place: "San Andrés", near: [12.5786, -81.6997] }] } },
  { key: 'guadalcanal|malaita', source: 'https://en.wikipedia.org/wiki/Transport_in_Solomon_Islands (Honiara ↔ Auki)',
    ports: { 'guadalcanal': [{ cc: 'SB', place: "Honiara" }], 'malaita': [{ cc: 'SB', place: "Auki" }] } },
  { key: 'guadalcanal|isabel', source: 'https://en.wikipedia.org/wiki/Transport_in_Solomon_Islands (Honiara ↔ Buala)',
    ports: { 'guadalcanal': [{ cc: 'SB', place: "Honiara" }], 'isabel': [{ cc: 'SB', place: "Buala" }] } },
  { key: 'guadalcanal|makira', source: 'https://en.wikipedia.org/wiki/Transport_in_Solomon_Islands (Honiara ↔ Kirakira)',
    ports: { 'guadalcanal': [{ cc: 'SB', place: "Honiara" }], 'makira': [{ cc: 'SB', place: "Kirakira" }] } },
  { key: 'guadalcanal|newGeorgia', source: 'https://en.wikipedia.org/wiki/Transport_in_Solomon_Islands (Honiara ↔ Noro)',
    ports: { 'guadalcanal': [{ cc: 'SB', place: "Honiara" }], 'newGeorgia': [{ cc: 'SB', place: "Noro" }] } },
  { key: 'gizo|newGeorgia', source: 'https://en.wikipedia.org/wiki/Transport_in_Solomon_Islands (Noro ↔ Gizo)',
    ports: { 'gizo': [{ cc: 'SB', place: "Gizo" }], 'newGeorgia': [{ cc: 'SB', place: "Noro" }] } },
  { key: 'newBritain|newIreland', source: 'https://en.wikipedia.org/wiki/Transport_in_Papua_New_Guinea (Kokopo ↔ Kavieng)',
    ports: { 'newBritain': [{ cc: 'PG', place: "Kokopo", near: [-4.3432, 152.2687] }], 'newIreland': [{ cc: 'PG', place: "Kavieng", near: [-2.5744, 150.7967] }] } },
  { key: 'bougainville|newBritain', source: 'https://en.wikipedia.org/wiki/Transport_in_Papua_New_Guinea (Kokopo ↔ Arawa)',
    ports: { 'bougainville': [{ cc: 'PG', place: "Arawa", near: [-6.2298, 155.566] }], 'newBritain': [{ cc: 'PG', place: "Kokopo", near: [-4.3432, 152.2687] }] } },
  { key: 'buton|sulawesi', source: 'https://www.pelni.co.id/ (Baubau ↔ Kendari)',
    ports: { 'buton': [{ cc: 'ID', place: "Baubau", near: [-5.4633, 122.6024] }], 'sulawesi': [{ cc: 'ID', place: "Kendari", near: [-3.945, 122.4989] }] } },
  { key: 'bawean|java', source: 'https://en.wikipedia.org/wiki/Bawean (Gresik ↔ Sangkapura)',
    ports: { 'bawean': [{ cc: 'ID', place: "Sangkapura", near: [-5.8453, 112.6517] }], 'java': [{ cc: 'ID', place: "Gresik", near: [-7.1561, 112.6561] }] } },
  { key: 'sangihe|sulawesi', source: 'https://www.pelni.co.id/ (Manado ↔ Tahuna)',
    ports: { 'sangihe': [{ cc: 'ID', place: "Tahuna" }], 'sulawesi': [{ cc: 'ID', place: "Manado" }] } },
  { key: 'flores|lembata', source: 'https://en.wikipedia.org/wiki/Lembata (Larantuka ↔ Lewoleba)',
    ports: { 'flores': [{ cc: 'ID', place: "Larantuka", near: [-8.34, 122.9833] }], 'lembata': [{ cc: 'ID', place: "Lewoleba", near: [-8.3723, 123.418] }] } },
  { key: 'biak|newGuinea', source: 'https://www.pelni.co.id/ (Jayapura ↔ Biak)',
    ports: { 'biak': [{ cc: 'ID', place: "Biak", near: [-1.1767, 136.082] }], 'newGuinea': [{ cc: 'ID', place: "Jayapura", near: [-2.5337, 140.7181] }] } },
  { key: 'ambon|keiKecil', source: 'https://www.pelni.co.id/ (Ambon ↔ Tual)',
    ports: { 'ambon': [{ cc: 'ID', place: "Ambon", near: [-3.6954, 128.1814] }], 'keiKecil': [{ cc: 'ID', place: "Tual", near: [-5.6288, 132.7523] }] } },
  { key: 'newGuinea|yapen', source: 'https://www.pelni.co.id/ (Jayapura ↔ Serui)',
    ports: { 'newGuinea': [{ cc: 'ID', place: "Jayapura", near: [-2.5337, 140.7181] }], 'yapen': [{ cc: 'ID', place: "Serui", near: [-1.8833, 136.2333] }] } },
  { key: 'newGuinea|waigeo', source: 'https://en.wikipedia.org/wiki/Waigeo (Sorong ↔ Waisai)',
    ports: { 'newGuinea': [{ cc: 'ID', place: "Sorong", near: [-0.8762, 131.2558] }], 'waigeo': [{ cc: 'ID', place: "Waisai" }] } },
  { key: 'ambon|yamdena', source: 'https://www.pelni.co.id/ (Ambon ↔ Saumlaki)',
    ports: { 'ambon': [{ cc: 'ID', place: "Ambon", near: [-3.6954, 128.1814] }], 'yamdena': [{ cc: 'ID', place: "Saumlaki", near: [-7.9833, 131.3] }] } },
  { key: 'iriomote|ishigaki', source: 'https://en.wikipedia.org/wiki/Iriomote_Island (Ishigaki ↔ Shirahama (Iriomote))',
    ports: { 'iriomote': [{ cc: 'JP', place: "Shirahama", near: [24.3378, 123.7556] }], 'ishigaki': [{ cc: 'JP', place: "Ishigaki", near: [24.3448, 124.1572] }] } },
  { key: 'changshan|continental', source: 'https://en.wikipedia.org/wiki/Changhai_County (Dalian ↔ Changshan)',
    ports: { 'changshan': [{ cc: 'CN', place: "Dachang Shandao", near: [39.2756, 122.6] }], 'continental': [{ cc: 'CN', place: "Dalian", near: [38.914, 121.6147] }] } },
  { key: 'cheduba|continental', source: 'https://en.wikipedia.org/wiki/Manaung (Kyaukpyu ↔ Manaung)',
    ports: { 'cheduba': [{ cc: 'MM', place: "Manaung", near: [18.8548, 93.7291] }], 'continental': [{ cc: 'MM', place: "Kyaukpyu", near: [19.4269, 93.5497] }] } },
  { key: 'masbate|ticao', source: 'https://en.wikipedia.org/wiki/Ticao_Island (Masbate ↔ San Jacinto)',
    ports: { 'masbate': [{ cc: 'PH', place: "Masbate", near: [12.3714, 123.6194] }], 'ticao': [{ cc: 'PH', place: "San Jacinto", near: [12.5677, 123.7337] }] } },
  { key: 'busuanga|culion', source: 'https://en.wikipedia.org/wiki/Culion (Coron ↔ Culion)',
    ports: { 'busuanga': [{ cc: 'PH', place: "Coron" }], 'culion': [{ cc: 'PH', place: "Culion" }] } },
  { key: 'burias|luzon', source: 'https://en.wikipedia.org/wiki/Burias_Island (Pio Duran ↔ Claveria)',
    ports: { 'burias': [{ cc: 'PH', place: "Claveria", near: [12.9, 123.2167] }], 'luzon': [{ cc: 'PH', place: "Pio Duran", near: [13.0333, 123.45] }] } },
  { key: 'bongao|tawiTawi', source: 'https://en.wikipedia.org/wiki/Bongao (Bongao ↔ Languyan)',
    ports: { 'bongao': [{ cc: 'PH', place: "Bongao" }], 'tawiTawi': [{ cc: 'PH', place: "Languyan" }] } },
  { key: 'cuyo|palawan', source: 'https://en.wikipedia.org/wiki/Cuyo,_Palawan (Puerto Princesa ↔ Cuyo)',
    ports: { 'cuyo': [{ cc: 'PH', place: "Cuyo", near: [10.8556, 121.0086] }], 'palawan': [{ cc: 'PH', place: "Puerto Princesa", near: [9.7392, 118.7353] }] } },
  { key: 'dumaran|palawan', source: 'https://en.wikipedia.org/wiki/Dumaran (Roxas ↔ Dumaran)',
    ports: { 'dumaran': [{ cc: 'PH', place: "Osmeña", near: [10.5333, 119.7667] }], 'palawan': [{ cc: 'PH', place: "Roxas", near: [10.3103, 119.34] }] } },
  { key: 'gigantesNorte|panay', source: 'https://en.wikipedia.org/wiki/Gigantes_Islands (Estancia ↔ Gigantes Norte)',
    ports: { 'gigantesNorte': [{ cc: 'PH', place: "Granada", near: [11.63, 123.35] }], 'panay': [{ cc: 'PH', place: "Estancia", near: [11.45, 123.15] }] } },
  { key: 'gigantesSur|panay', source: 'https://en.wikipedia.org/wiki/Gigantes_Islands (Estancia ↔ Gigantes Sur)',
    ports: { 'gigantesSur': [{ cc: 'PH', place: "Lantangan", near: [11.59, 123.33] }], 'panay': [{ cc: 'PH', place: "Estancia", near: [11.45, 123.15] }] } },
  { key: 'eydhafushi|maleHulhumale', source: 'https://en.wikipedia.org/wiki/Transport_in_the_Maldives (Malé ↔ Eydhafushi)',
    ports: { 'eydhafushi': [{ cc: 'MV', place: "Eydhafushi" }], 'maleHulhumale': [{ cc: 'MV', place: "Male" }] } },
  { key: 'laDigue|mahe', source: 'https://www.catcocos.com/ (Victoria (Mahé) ↔ La Digue)',
    ports: { 'laDigue': [{ cc: 'SC', place: "La Digue" }], 'mahe': [{ cc: 'SC', place: "Victoria" }] } },
  { key: 'livingston|northAmerica', source: 'https://en.wikipedia.org/wiki/L%C3%ADvingston,_Guatemala (Puerto Barrios ↔ Lívingston)',
    ports: { 'livingston': [{ cc: 'GT', place: "Lívingston" }], 'northAmerica': [{ cc: 'GT', place: "Puerto Barrios" }] } },
  { key: 'holbox|northAmerica', source: 'https://en.wikipedia.org/wiki/Isla_Holbox (Chiquilá ↔ Isla Holbox)',
    ports: { 'holbox': [{ cc: 'MX', place: "Isla Holbox" }], 'northAmerica': [{ cc: 'MX', place: "Chiquilá" }] } },
  { key: 'culebra|puertoRico', source: 'https://en.wikipedia.org/wiki/Culebra,_Puerto_Rico (Ceiba ↔ Culebra)',
    ports: { 'culebra': [{ cc: 'PR', place: "Culebra" }], 'puertoRico': [{ cc: 'PR', place: "Ceiba", near: [18.26, -65.65] }] } },
  { key: 'kohChang|kohKood', source: 'https://en.wikipedia.org/wiki/Ko_Kut (Ko Chang ↔ Ko Kood)',
    ports: { 'kohChang': [{ cc: 'TH', place: "Ko Chang", near: [12.05, 102.3167] }], 'kohKood': [{ cc: 'TH', place: "Ko Kood", near: [11.65, 102.5333] }] } },
  { key: 'continental|pangkor', source: 'https://en.wikipedia.org/wiki/Pangkor_Island (Lumut ↔ Pangkor)',
    ports: { 'continental': [{ cc: 'MY', place: "Lumut" }], 'pangkor': [{ cc: 'MY', place: "Pangkor" }] } },
  // Lot de COUVERTURE, passe 3.
  { key: 'efate|malekula', source: 'https://en.wikipedia.org/wiki/Malakula (Port-Vila ↔ Norsup (Malekula))',
    ports: { 'efate': [{ cc: 'VU', place: "Port-Vila" }], 'malekula': [{ cc: 'VU', place: "Norsup" }] } },
  { key: 'efate|tanna', source: 'https://en.wikipedia.org/wiki/Tanna_Island (Port-Vila ↔ Isangel (Tanna))',
    ports: { 'efate': [{ cc: 'VU', place: "Port-Vila" }], 'tanna': [{ cc: 'VU', place: "Isangel" }] } },
  { key: 'ambrym|efate', source: 'https://en.wikipedia.org/wiki/Ambrym (Port-Vila ↔ Port-Vato (Ambrym))',
    ports: { 'ambrym': [{ cc: 'VU', place: "Port-Vato" }], 'efate': [{ cc: 'VU', place: "Port-Vila" }] } },
  { key: 'santo|vanuaLava', source: 'https://en.wikipedia.org/wiki/Vanua_Lava (Luganville ↔ Sola (Vanua Lava))',
    ports: { 'santo': [{ cc: 'VU', place: "Luganville" }], 'vanuaLava': [{ cc: 'VU', place: "Sola" }] } },
  { key: 'grandeTerreNC|ouvea', source: 'https://en.wikipedia.org/wiki/Ouv%C3%A9a,_New_Caledonia (Nouméa ↔ Ouvéa)',
    ports: { 'grandeTerreNC': [{ cc: 'FR', place: "Nouméa" }], 'ouvea': [{ cc: 'FR', place: "Ouvéa" }] } },
  { key: 'belep|grandeTerreNC', source: 'https://en.wikipedia.org/wiki/Belep (Nouméa ↔ Belep)',
    ports: { 'belep': [{ cc: 'FR', place: "Belep" }], 'grandeTerreNC': [{ cc: 'FR', place: "Nouméa" }] } },
  { key: 'sanCristobalGalapagos|santaCruzGalapagos', source: 'https://en.wikipedia.org/wiki/San_Crist%C3%B3bal_Island (Puerto Ayora ↔ Puerto Baquerizo Moreno)',
    ports: { 'sanCristobalGalapagos': [{ cc: 'EC', place: "Puerto Baquerizo Moreno" }], 'santaCruzGalapagos': [{ cc: 'EC', place: "Puerto Ayora" }] } },
  { key: 'isabelaGalapagos|santaCruzGalapagos', source: 'https://en.wikipedia.org/wiki/Isabela_Island_(Gal%C3%A1pagos) (Puerto Ayora ↔ Puerto Villamil)',
    ports: { 'isabelaGalapagos': [{ cc: 'EC', place: "Puerto Villamil" }], 'santaCruzGalapagos': [{ cc: 'EC', place: "Puerto Ayora" }] } },
  { key: 'eleuthera|newProvidence', source: 'https://bahamasferries.com/your-travel/ (Nassau ↔ Governor’s Harbour (Eleuthera))',
    ports: { 'eleuthera': [{ cc: 'BS', place: "Governor’s Harbour" }], 'newProvidence': [{ cc: 'BS', place: "Nassau" }] } },
  { key: 'greatExuma|newProvidence', source: 'https://bahamasferries.com/your-travel/ (Nassau ↔ George Town (Exuma))',
    ports: { 'greatExuma': [{ cc: 'BS', place: "George Town" }], 'newProvidence': [{ cc: 'BS', place: "Nassau" }] } },
  { key: 'abaco|newProvidence', source: 'https://bahamasferries.com/your-travel/ (Nassau ↔ Marsh Harbour (Abaco))',
    ports: { 'abaco': [{ cc: 'BS', place: "Marsh Harbour" }], 'newProvidence': [{ cc: 'BS', place: "Nassau" }] } },
  { key: 'newProvidence|northAndros', source: 'https://bahamasferries.com/your-travel/ (Nassau ↔ San Andros (Andros))',
    ports: { 'newProvidence': [{ cc: 'BS', place: "Nassau" }], 'northAndros': [{ cc: 'BS', place: "San Andros" }] } },
  { key: 'catIsland|newProvidence', source: 'https://bahamasferries.com/your-travel/ (Nassau ↔ Arthur’s Town (Cat Island))',
    ports: { 'catIsland': [{ cc: 'BS', place: "Arthur’s Town" }], 'newProvidence': [{ cc: 'BS', place: "Nassau" }] } },
  { key: 'longIslandBS|newProvidence', source: 'https://bahamasferries.com/your-travel/ (Nassau ↔ Clarence Town (Long Island))',
    ports: { 'longIslandBS': [{ cc: 'BS', place: "Clarence Town" }], 'newProvidence': [{ cc: 'BS', place: "Nassau" }] } },
  { key: 'newProvidence|sanSalvador', source: 'https://bahamasferries.com/your-travel/ (Nassau ↔ Cockburn Town (San Salvador))',
    ports: { 'newProvidence': [{ cc: 'BS', place: "Nassau" }], 'sanSalvador': [{ cc: 'BS', place: "Cockburn Town" }] } },
  { key: 'grandTurk|providenciales', source: 'https://en.wikipedia.org/wiki/Grand_Turk_Island (Providenciales ↔ Grand Turk)',
    ports: { 'grandTurk': [{ cc: 'TC', place: "Cockburn Town" }], 'providenciales': [{ cc: 'TC', place: "The Bight Settlements" }] } },
  { key: 'grandTurk|southCaicos', source: 'https://en.wikipedia.org/wiki/South_Caicos (Grand Turk ↔ South Caicos)',
    ports: { 'grandTurk': [{ cc: 'TC', place: "Cockburn Town" }], 'southCaicos': [{ cc: 'TC', place: "Cockburn Harbour" }] } },
  { key: 'honshu|izuOshima', source: 'https://www.tokaikisen.co.jp/ (Tokyo ↔ Ōshima)',
    ports: { 'honshu': [{ cc: 'JP', place: "Tokyo" }], 'izuOshima': [{ cc: 'JP', place: "Ōshima" }] } },
  { key: 'australia|rottnest', source: 'https://en.wikipedia.org/wiki/Rottnest_Island (Fremantle ↔ Rottnest Island)',
    ports: { 'australia': [{ cc: 'AU', place: "East Fremantle" }], 'rottnest': [{ cc: 'AU', place: "Rottnest Island" }] } },
  { key: 'australia|melvilleIsland', source: 'https://en.wikipedia.org/wiki/Melville_Island_(Northern_Territory) (Darwin ↔ Milikapiti (Melville))',
    ports: { 'australia': [{ cc: 'AU', place: "Darwin" }], 'melvilleIsland': [{ cc: 'AU', place: "Milikapiti" }] } },
  { key: 'australia|elcho', source: 'https://en.wikipedia.org/wiki/Elcho_Island (Nhulunbuy ↔ Galiwin’ku (Elcho))',
    ports: { 'australia': [{ cc: 'AU', place: "Nhulunbuy" }], 'elcho': [{ cc: 'AU', place: "Galiwinku" }] } },
  { key: 'australia|grooteEylandt', source: 'https://en.wikipedia.org/wiki/Groote_Eylandt (Nhulunbuy ↔ Alyangula (Groote Eylandt))',
    ports: { 'australia': [{ cc: 'AU', place: "Nhulunbuy" }], 'grooteEylandt': [{ cc: 'AU', place: "Alyangula" }] } },
  { key: 'catalina|northAmerica', source: 'https://catalinaexpress.com/schedule-fares/ (Long Beach ↔ Avalon (Catalina))',
    ports: { 'catalina': [{ cc: 'US', place: "Avalon" }], 'northAmerica': [{ cc: 'US', place: "Long Beach", near: [33.7701, -118.1937] }] } },
  { key: 'continental|tioman', source: 'https://en.wikipedia.org/wiki/Tioman_Island (Mersing ↔ Kampung Tekek (Tioman))',
    ports: { 'continental': [{ cc: 'MY', place: "Mersing" }], 'tioman': [{ cc: 'MY', place: "Kampung Tekek" }] } },
  { key: 'continental|kohTao', source: 'https://en.wikipedia.org/wiki/Ko_Tao (Chumphon ↔ Ko Tao)',
    ports: { 'continental': [{ cc: 'TH', place: "Chumphon" }], 'kohTao': [{ cc: 'TH', place: "Koh Tao" }] } },
  { key: 'continental|koTarutao', source: 'https://en.wikipedia.org/wiki/Ko_Tarutao (La-ngu ↔ Ko Tarutao)',
    ports: { 'continental': [{ cc: 'TH', place: "La-ngu" }], 'koTarutao': [{ cc: 'TH', place: "Son" }] } },
  { key: 'coche|margarita', source: 'https://en.wikipedia.org/wiki/Coche_Island (Porlamar ↔ San Pedro de Coche)',
    ports: { 'coche': [{ cc: 'VE', place: "San Pedro de Coche" }], 'margarita': [{ cc: 'VE', place: "Porlamar" }] } },
  { key: 'manus|newGuinea', source: 'https://en.wikipedia.org/wiki/Manus_Island (Lae ↔ Lorengau (Manus))',
    ports: { 'manus': [{ cc: 'PG', place: "Lorengau" }], 'newGuinea': [{ cc: 'PG', place: "Lae" }] } },
  { key: 'lihir|newIreland', source: 'https://en.wikipedia.org/wiki/Lihir_Island (Kavieng ↔ Londolovit (Lihir))',
    ports: { 'lihir': [{ cc: 'PG', place: "Londolovit" }], 'newIreland': [{ cc: 'PG', place: "Kavieng" }] } },
  { key: 'chizumulu|likoma', source: 'https://en.wikipedia.org/wiki/Chizumulu_Island (Likoma ↔ Chizumulu)',
    ports: { 'chizumulu': [{ cc: 'MW', place: "Chisumulu" }], 'likoma': [{ cc: 'MW', place: "Likoma" }] } },
  { key: 'gonave|hispaniola', source: 'https://en.wikipedia.org/wiki/Gon%C3%A2ve_Island (Port-au-Prince ↔ Anse-à-Galets (La Gonâve))',
    ports: { 'gonave': [{ cc: 'HT', place: "Anse à Galets" }], 'hispaniola': [{ cc: 'HT', place: "Port-au-Prince" }] } },
  { key: 'bantayan|kinatarkan', source: 'https://en.wikipedia.org/wiki/Kinatarcan_Island (Santa Fe ↔ Hagdan (Kinatarkan))',
    ports: { 'bantayan': [{ cc: 'PH', place: "Santa Fe" }], 'kinatarkan': [{ cc: 'PH', place: "Hagdan" }] } },
  { key: 'leyteSamar|sanVicenteSamar', source: 'https://en.wikipedia.org/wiki/San_Vicente,_Northern_Samar (Allen ↔ San Vicente)',
    ports: { 'leyteSamar': [{ cc: 'PH', place: "Allen" }], 'sanVicenteSamar': [{ cc: 'PH', place: "San Vicente" }] } },
  { key: 'laoang|leyteSamar', source: 'https://en.wikipedia.org/wiki/Laoang (Catarman ↔ Laoang)',
    ports: { 'laoang': [{ cc: 'PH', place: "Laoang" }], 'leyteSamar': [{ cc: 'PH', place: "Catarman", near: [12.4989, 124.6383] }] } },
  { key: 'adduLink|hulhumeedhoo', source: 'https://en.wikipedia.org/wiki/Addu_City (Hithadhoo ↔ Meedhoo (Addu))',
    ports: { 'adduLink': [{ cc: 'MV', place: "Hithadhoo" }], 'hulhumeedhoo': [{ cc: 'MV', place: "Meedhoo" }] } },
  { key: 'continental|mafia', source: 'https://en.wikipedia.org/wiki/Mafia_Island (Kisiju ↔ Kilindoni (Mafia))',
    ports: { 'continental': [{ cc: 'TZ', place: "Kisiju" }], 'mafia': [{ cc: 'TZ', place: "Kilindoni" }] } },
  { key: 'bubaque|continental', source: 'https://en.wikipedia.org/wiki/Bubaque (Bissau ↔ Bubaque)',
    ports: { 'bubaque': [{ cc: 'GW', place: "Bubaque" }], 'continental': [{ cc: 'GW', place: "Bissau" }] } },
  { key: 'bolama|continental', source: 'https://en.wikipedia.org/wiki/Bolama (Bissau ↔ Bolama)',
    ports: { 'bolama': [{ cc: 'GW', place: "Bolama" }], 'continental': [{ cc: 'GW', place: "Bissau" }] } },
  { key: 'batam|karimun', source: 'https://en.wikipedia.org/wiki/Karimun_Regency (Batam ↔ Tanjung Balai (Karimun))',
    ports: { 'batam': [{ cc: 'ID', place: "Batam" }], 'karimun': [{ cc: 'ID', place: "Tanjung Balai" }] } },
];
