// Villes portuaires du lot 1 (liaisons FERRY_ROUTES) — voir scripts/build-ferry-ports.js.
// 22/09/2026 : Toulon, Calais, Le Havre, Saint-Malo et Manila ont reçu leur « near ». Ces noms ne désignaient plus un
// seul lieu — Manila depuis toujours (une seconde Manila à Mimaropa, 260 km au sud, et le générateur REFUSAIT déjà de
// tourner sur le dépôt : personne ne l'avait vu, son test est désactivé par défaut), les quatre français depuis que
// les lieux-dits GeoNames sont publiés (un hameau « Toulon » en Vienne et un autre en Charente-Maritime, « Calais »
// en Dordogne et dans l'Eure, « Le Havre » dans la Manche, « Saint-Malô » dans l'Orne). Le « near » est la coordonnée
// de la ville portuaire elle-même, prise dans les données publiées : le générateur retient le lieu le plus proche à
// 30 km au plus, donc le bon, et refuserait de choisir si la ville portuaire disparaissait.
// Les coordonnées viennent des données de lieux du projet ; quand la localité du port n'existe pas sous son nom,
// la localité la plus proche du terminal sur la bonne masse terrestre est retenue (commentaire « port → lieu »).
const P = (cc, place, near) => near ? { cc, place, near } : { cc, place };
const FH = i => 'https://www.ferryhopper.com/en/ferries/greece/' + i;

module.exports = [
  { key: 'continental|corsica',
    source: 'https://www.corsicalinea.com/preparer-votre-voyage/les-ports ; https://www.lameridionale.fr ; https://www.corsica-ferries.co.uk/crossing/corsica-ferry/ ; https://www.mobylines.com',
    ports: {
      continental: [P('FR', 'Marseille'), P('FR', 'Toulon', [43.14, 5.93]), P('FR', 'Nice'), P('IT', 'Savona'), P('IT', 'Genova', [44.40, 8.94]), P('IT', 'Livorno'), P('IT', 'Piombino', [42.93, 10.53])],
      corsica: [P('FR', 'Ajaccio'), P('FR', 'Bastia'), P('FR', 'Calvi'), P('FR', "L'Île-Rousse"), P('FR', 'Porto-Vecchio'), P('FR', 'Propriano')] } },
  // Masse « balearic » = Majorque seule (Minorque et Ibiza ont leur propre masse).
  { key: 'balearic|continental',
    source: 'https://www.trasmed.com ; https://www.balearia.com/en/routes-timetables/ferry-barcelona-mallorca ; https://www.ferryhopper.com/en/ferry-routes/direct/ferry-valencia-mallorca',
    ports: {
      balearic: [P('ES', 'Palma'), P('ES', 'Alcúdia')],
      continental: [P('ES', 'Barcelona'), P('ES', 'Valencia', [39.47, -0.38]), P('ES', 'Denia')] } },
  // Masse « canary » = Grande Canarie seule (Tenerife, Lanzarote… ont leur propre masse).
  { key: 'canary|continental',
    source: 'https://armastrasmediterranea.com/en/routes-timetables/ferry-cadiz-gran-canaria ; https://www.balearia.com/en/routes-timetables/ferry-grancanarias-huelva',
    ports: {
      canary: [P('ES', 'Las Palmas de Gran Canaria')],
      continental: [P('ES', 'Cadiz'), P('ES', 'Huelva')] } },
  { key: 'continental|sardinia',
    source: 'https://www.ferryhopper.com/en/ferries/italy/sardinia ; https://www.ferryhopper.com/en/ferry-routes/direct/france-sardinia ; https://www.corsica-ferries.co.uk/crossing/sardinia-ferry/ ; https://www.mobylines.com',
    ports: {
      continental: [P('IT', 'Genova', [44.40, 8.94]), P('IT', 'Livorno'), P('IT', 'Piombino', [42.93, 10.53]), P('IT', 'Civitavecchia', [42.09, 11.80]), P('IT', 'Napoli'), P('FR', 'Toulon', [43.14, 5.93]), P('FR', 'Nice'), P('ES', 'Barcelona')],
      sardinia: [P('IT', 'Olbia'), P('IT', 'Golfo Aranci'), P('IT', 'Porto Torres'), P('IT', 'Cagliari'), P('IT', 'Arbatax')] } },
  { key: 'continental|sicily',
    source: 'https://www.ferryhopper.com/en/ferries/italy/sicily ; https://www.gnv.it/en/ferries-destinations/sicily ; https://www.carontetourist.it',
    ports: {
      continental: [P('IT', 'Villa San Giovanni', [38.22, 15.64]), P('IT', 'Reggio Calabria'), P('IT', 'Salerno', [40.68, 14.79]), P('IT', 'Napoli'), P('IT', 'Civitavecchia', [42.09, 11.80]), P('IT', 'Genova', [44.40, 8.94]), P('IT', 'Livorno')],
      sicily: [P('IT', 'Messina'), P('IT', 'Palermo'), P('IT', 'Termini Imerese')] } },
  { key: 'malta|sicily', source: 'https://www.virtuferries.com (Valletta ↔ Pozzallo, Catania)',
    ports: { malta: [P('MT', 'Valletta')], sicily: [P('IT', 'Pozzallo'), P('IT', 'Catania')] } },
  // Ċirkewwa → Mellieħa (localité du terminal).
  { key: 'gozo|malta', source: 'https://www.gozochannel.com (Ċirkewwa ↔ Mġarr)',
    ports: { gozo: [P('MT', 'Mġarr')], malta: [P('MT', 'Mellieħa')] } },
  { key: 'continental|jersey', source: 'https://www.condorferries.co.uk (St Malo ↔ St Helier)',
    ports: { continental: [P('FR', 'Saint-Malo', [48.65, -2.01])], jersey: [P('JE', 'Saint Helier')] } },
  { key: 'continental|guernsey', source: 'https://www.condorferries.co.uk (St Malo ↔ St Peter Port)',
    ports: { continental: [P('FR', 'Saint-Malo', [48.65, -2.01])], guernsey: [P('GG', 'Saint Peter Port')] } },
  { key: 'guernsey|jersey', source: 'https://www.condorferries.co.uk (St Helier ↔ St Peter Port)',
    ports: { guernsey: [P('GG', 'Saint Peter Port')], jersey: [P('JE', 'Saint Helier')] } },
  // Brestova → Zagorje (Istrie) ; Valbiska (Krk, relié par pont) → Pinezići.
  { key: 'continental|cres', source: 'https://www.jadrolinija.hr/en (Brestova ↔ Porozina, Valbiska ↔ Merag)',
    ports: { continental: [P('HR', 'Zagorje', [45.146, 14.217]), P('HR', 'Pinezići', [45.045, 14.48])], cres: [P('HR', 'Porozina'), P('HR', 'Merag')] } },
  // Mišnjak → Barbat.
  { key: 'continental|rab', source: 'https://www.jadrolinija.hr/en (Valbiska ↔ Lopar) ; Rapska plovidba (Stinica ↔ Mišnjak)',
    ports: { continental: [P('HR', 'Stinica'), P('HR', 'Pinezići', [45.045, 14.48])], rab: [P('HR', 'Barbat'), P('HR', 'Lopar')] } },
  { key: 'continental|ugljan', source: 'https://www.jadrolinija.hr/en (Zadar ↔ Preko)',
    ports: { continental: [P('HR', 'Zadar')], ugljan: [P('HR', 'Preko')] } },
  { key: 'continental|dugiOtok', source: 'https://www.jadrolinija.hr/en (Zadar ↔ Brbinj)',
    ports: { continental: [P('HR', 'Zadar')], dugiOtok: [P('HR', 'Brbinj')] } },
  { key: 'brac|continental', source: 'https://www.jadrolinija.hr/en (Split ↔ Supetar, Makarska ↔ Sumartin)',
    ports: { brac: [P('HR', 'Supetar'), P('HR', 'Sumartin')], continental: [P('HR', 'Split'), P('HR', 'Makarska')] } },
  { key: 'continental|solta', source: 'https://www.jadrolinija.hr/en (Split ↔ Rogač)',
    ports: { continental: [P('HR', 'Split')], solta: [P('HR', 'Rogač')] } },
  { key: 'continental|hvar', source: 'https://www.jadrolinija.hr/en (Split ↔ Stari Grad, Drvenik ↔ Sućuraj)',
    ports: { continental: [P('HR', 'Split'), P('HR', 'Drvenik', [43.156, 17.249])], hvar: [P('HR', 'Stari Grad'), P('HR', 'Sućuraj')] } },
  { key: 'continental|vis', source: 'https://www.jadrolinija.hr/en (Split ↔ Vis)',
    ports: { continental: [P('HR', 'Split')], vis: [P('HR', 'Vis')] } },
  // Dominče → Korčula.
  { key: 'continental|korcula', source: 'https://www.jadrolinija.hr/en (Orebić ↔ Dominče, Split ↔ Vela Luka)',
    ports: { continental: [P('HR', 'Orebić'), P('HR', 'Split')], korcula: [P('HR', 'Korčula'), P('HR', 'Vela Luka')] } },
  // Prapratno → Prapratna.
  { key: 'continental|mljet', source: 'https://www.jadrolinija.hr/en (Prapratno ↔ Sobra)',
    ports: { continental: [P('HR', 'Prapratna')], mljet: [P('HR', 'Sobra')] } },
  { key: 'continental|lastovo', source: 'https://www.jadrolinija.hr/en (Split ↔ Vela Luka ↔ Ubli)',
    ports: { continental: [P('HR', 'Split')], lastovo: [P('HR', 'Ubli')] } },
  // Newcastle (terminal DFDS) → North Shields ; Rotterdam-Europoort (P&O) couvert par Hoek van Holland, voisin.
  { key: 'continental|greatBritain',
    source: 'https://ferrygogo.co.uk/united-kingdom/ ; https://ferrygogo.co.uk/france/ferry-to-france-from-the-uk/ ; https://www.dfds.com ; https://www.brittany-ferries.co.uk ; https://www.stenaline.co.uk',
    ports: {
      continental: [P('FR', 'Calais', [50.95, 1.87]), P('FR', 'Dunkerque'), P('FR', 'Dieppe'), P('FR', 'Le Havre', [49.50, 0.13]), P('FR', 'Ouistreham'), P('FR', 'Cherbourg-en-Cotentin'), P('FR', 'Saint-Malo', [48.65, -2.01]), P('FR', 'Roscoff'), P('ES', 'Santander'), P('ES', 'Bilbao'), P('NL', 'Hoek van Holland'), P('NL', 'IJmuiden')],
      greatBritain: [P('GB', 'Dover'), P('GB', 'Newhaven', [50.80, 0.055]), P('GB', 'Portsmouth', [50.80, -1.09]), P('GB', 'Poole', [50.71, -1.98]), P('GB', 'Plymouth'), P('GB', 'Harwich'), P('GB', 'Kingston upon Hull'), P('GB', 'North Shields')] } },
  { key: 'greatBritain|ireland',
    source: 'https://ferrygogo.co.uk/united-kingdom/ ; https://www.stenaline.co.uk ; https://www.irishferries.com (Holyhead ↔ Dublin, Fishguard/Pembroke ↔ Rosslare, Liverpool/Birkenhead ↔ Dublin/Belfast, Cairnryan ↔ Belfast/Larne)',
    ports: {
      greatBritain: [P('GB', 'Holyhead'), P('GB', 'Fishguard'), P('GB', 'Pembroke Dock'), P('GB', 'Liverpool'), P('GB', 'Birkenhead'), P('GB', 'Cairnryan')],
      ireland: [P('IE', 'Dublin'), P('IE', 'Rosslare'), P('GB', 'Belfast'), P('GB', 'Larne')] } },
  { key: 'greatBritain|isleOfMan', source: 'https://www.steam-packet.com (Heysham, Liverpool ↔ Douglas)',
    ports: { greatBritain: [P('GB', 'Heysham'), P('GB', 'Liverpool')], isleOfMan: [P('IM', 'Douglas')] } },
  { key: 'bornholm|continental', source: 'https://www.bornholmslinjen.com (Ystad ↔ Rønne, Sassnitz ↔ Rønne)',
    ports: { bornholm: [P('DK', 'Rønne')], continental: [P('SE', 'Ystad'), P('DE', 'Sassnitz')] } },
  { key: 'continental|gotland', source: 'https://www.destinationgotland.se (Nynäshamn, Oskarshamn ↔ Visby)',
    ports: { continental: [P('SE', 'Nynäshamn'), P('SE', 'Oskarshamn', [57.26, 16.45])], gotland: [P('SE', 'Visby')] } },
  { key: 'aland|continental', source: 'https://visitaland.com/en/plan-your-journey/travelling-to-aland/ (Turku, Naantali, Helsinki, Stockholm, Kapellskär, Grisslehamn ↔ Mariehamn, Långnäs, Eckerö)',
    ports: {
      aland: [P('AX', 'Mariehamn'), P('AX', 'Långnäs hamn'), P('AX', 'Eckerö')],
      continental: [P('FI', 'Turku', [60.45, 22.27]), P('FI', 'Naantali'), P('FI', 'Helsinki'), P('SE', 'Stockholm'), P('SE', 'Kapellskär'), P('SE', 'Grisslehamn')] } },
  // Souda (port de La Canée) ; Pirée → Peiraiás.
  { key: 'continental|crete', source: FH('crete') + ' (Pirée ↔ Héraklion, Souda/La Canée, Réthymnon, Sitia, Kissamos ; Gythio ↔ Kissamos)',
    ports: { continental: [P('GR', 'Peiraiás'), P('GR', 'Gýtheio')], crete: [P('GR', 'Irákleion'), P('GR', 'Soúda', [35.49, 24.07]), P('GR', 'Rethymno'), P('GR', 'Kíssamos'), P('GR', 'Sitia')] } },
  { key: 'continental|rhodes', source: FH('rhodes') + ' (Pirée ↔ Rhodes)',
    ports: { continental: [P('GR', 'Peiraiás')], rhodes: [P('GR', 'Ródos')] } },
  { key: 'continental|kos', source: FH('kos') + ' (Pirée ↔ Kos)',
    ports: { continental: [P('GR', 'Peiraiás')], kos: [P('GR', 'Kos')] } },
  // Pothia → Kálymnos.
  { key: 'continental|kalymnos', source: FH('kalymnos') + ' (Pirée ↔ Kálymnos/Pothia)',
    ports: { continental: [P('GR', 'Peiraiás')], kalymnos: [P('GR', 'Kálymnos')] } },
  { key: 'continental|leros', source: 'https://www.greeka.com/dodecanese/leros/ferries/ (Pirée ↔ Lakki)',
    ports: { continental: [P('GR', 'Peiraiás')], leros: [P('GR', 'Lakkí')] } },
  { key: 'continental|patmos', source: FH('patmos') + ' (Pirée ↔ Skala)',
    ports: { continental: [P('GR', 'Peiraiás')], patmos: [P('GR', 'Skála')] } },
  { key: 'continental|karpathos', source: FH('karpathos') + ' (Pirée ↔ Kárpathos/Pigadia, Diafani)',
    ports: { continental: [P('GR', 'Peiraiás')], karpathos: [P('GR', 'Karpathos'), P('GR', 'Diafánion')] } },
  { key: 'continental|corfu', source: FH('corfu') + ' (Igoumenitsa ↔ Corfou, Lefkimmi)',
    ports: { continental: [P('GR', 'Igoumenítsa')], corfu: [P('GR', 'Kérkyra'), P('GR', 'Lefkímmi')] } },
  { key: 'continental|kefalonia', source: FH('kefalonia') + ' ; https://www.ferries.gr/en/ferry-routes/kilinipatras-cefalonia/ (Kyllini ↔ Poros, Patras/Astakos ↔ Sami, Vasiliki ↔ Fiskardo)',
    ports: { continental: [P('GR', 'Kyllíni', [37.94, 21.15]), P('GR', 'Pátra'), P('GR', 'Astakós'), P('GR', 'Vasilikí', [38.63, 20.61])], kefalonia: [P('GR', 'Póros'), P('GR', 'Sámi'), P('GR', 'Fiskárdo')] } },
  // Pisaetos → Aetós ; Vathy → Itháki.
  { key: 'continental|ithaca', source: FH('ithaki') + ' ; https://www.ferries.gr/en/ferry-routes/kilinipatras-ithaca/ (Patras, Astakos ↔ Pisaetos ; Vasiliki ↔ Frikes)',
    ports: { continental: [P('GR', 'Pátra'), P('GR', 'Astakós'), P('GR', 'Vasilikí', [38.63, 20.61])], ithaca: [P('GR', 'Aetós'), P('GR', 'Fríkes')] } },
  { key: 'continental|zakynthos', source: FH('zakynthos') + ' (Kyllini ↔ Zakynthos)',
    ports: { continental: [P('GR', 'Kyllíni', [37.94, 21.15])], zakynthos: [P('GR', 'Zákynthos')] } },
  { key: 'continental|kythira', source: 'https://www.kithera.gr/en/itineraries-ferry-tickets-to-kythira/ ; ' + FH('kythira') + ' (Neapoli, Gythio ↔ Diakofti)',
    ports: { continental: [P('GR', 'Neápoli', [36.51, 23.06]), P('GR', 'Gýtheio')], kythira: [P('GR', 'Diakófti')] } },
  { key: 'continental|lesvos', source: FH('lesvos') + ' (Pirée, Kavala, Thessalonique ↔ Mytilène)',
    ports: { continental: [P('GR', 'Peiraiás'), P('GR', 'Kavála'), P('GR', 'Thessaloníki')], lesvos: [P('GR', 'Mytilíni')] } },
  { key: 'chios|continental', source: FH('chios') + ' (Pirée, Lavrio, Kavala, Thessalonique ↔ Chios)',
    ports: { chios: [P('GR', 'Chios')], continental: [P('GR', 'Peiraiás'), P('GR', 'Lávrio'), P('GR', 'Kavála'), P('GR', 'Thessaloníki')] } },
  { key: 'continental|samos', source: FH('samos') + ' (Pirée, Kavala, Thessalonique ↔ Vathy, Karlovasi)',
    ports: { continental: [P('GR', 'Peiraiás'), P('GR', 'Kavála'), P('GR', 'Thessaloníki')], samos: [P('GR', 'Vathý'), P('GR', 'Néon Karlovásion')] } },
  { key: 'continental|ikaria', source: FH('ikaria') + ' (Pirée, Kavala, Thessalonique ↔ Agios Kirykos, Evdilos)',
    ports: { continental: [P('GR', 'Peiraiás'), P('GR', 'Kavála'), P('GR', 'Thessaloníki')], ikaria: [P('GR', 'Agios Kirykos'), P('GR', 'Évdilos')] } },
  { key: 'continental|syros', source: FH('syros') + ' (Pirée, Lavrio ↔ Ermoupoli)',
    ports: { continental: [P('GR', 'Peiraiás'), P('GR', 'Lávrio')], syros: [P('GR', 'Ermoúpolis')] } },
  { key: 'continental|tinos', source: FH('tinos') + ' (Pirée, Rafina, Lavrio ↔ Tinos)',
    ports: { continental: [P('GR', 'Peiraiás'), P('GR', 'Rafína', [38.02, 24.01]), P('GR', 'Lávrio')], tinos: [P('GR', 'Tínos')] } },
  { key: 'continental|naxos', source: FH('naxos') + ' (Pirée, Rafina, Lavrio ↔ Naxos)',
    ports: { continental: [P('GR', 'Peiraiás'), P('GR', 'Rafína', [38.02, 24.01]), P('GR', 'Lávrio')], naxos: [P('GR', 'Náxos')] } },
  { key: 'continental|paros', source: FH('paros') + ' (Pirée, Rafina, Lavrio ↔ Parikia)',
    ports: { continental: [P('GR', 'Peiraiás'), P('GR', 'Rafína', [38.02, 24.01]), P('GR', 'Lávrio')], paros: [P('GR', 'Páros')] } },
  { key: 'andros|continental', source: FH('andros') + ' (Rafina ↔ Gavrio)',
    ports: { andros: [P('GR', 'Gávrio')], continental: [P('GR', 'Rafína', [38.02, 24.01])] } },
  { key: 'continental|mykonos', source: FH('mykonos') + ' (Pirée, Rafina, Lavrio ↔ Mykonos)',
    ports: { continental: [P('GR', 'Peiraiás'), P('GR', 'Rafína', [38.02, 24.01]), P('GR', 'Lávrio')], mykonos: [P('GR', 'Mykonos')] } },
  // Athinios → Firá.
  { key: 'continental|santorini', source: FH('santorini') + ' (Pirée, Rafina ↔ Athinios)',
    ports: { continental: [P('GR', 'Peiraiás'), P('GR', 'Rafína', [38.02, 24.01])], santorini: [P('GR', 'Firá')] } },
  { key: 'continental|milos', source: FH('milos') + ' (Pirée, Rafina, Lavrio ↔ Adamas)',
    ports: { continental: [P('GR', 'Peiraiás'), P('GR', 'Rafína', [38.02, 24.01]), P('GR', 'Lávrio')], milos: [P('GR', 'Adámas')] } },
  { key: 'continental|ios', source: FH('ios') + ' (Pirée, Rafina, Lavrio ↔ Ios)',
    ports: { continental: [P('GR', 'Peiraiás'), P('GR', 'Rafína', [38.02, 24.01]), P('GR', 'Lávrio')], ios: [P('GR', 'Íos')] } },
  { key: 'amorgos|continental', source: FH('amorgos') + ' (Pirée ↔ Katapola, Aigiali)',
    ports: { amorgos: [P('GR', 'Katápola'), P('GR', 'Aigiali')], continental: [P('GR', 'Peiraiás')] } },
  { key: 'aegina|continental', source: FH('aegina') + ' (Pirée ↔ Égine)',
    ports: { aegina: [P('GR', 'Aegina')], continental: [P('GR', 'Peiraiás')] } },
  { key: 'continental|poros', source: FH('poros') + ' ; https://www.greeka.com/saronic/poros/ferries/ (Pirée ↔ Poros, Galatas ↔ Poros)',
    ports: { continental: [P('GR', 'Peiraiás'), P('GR', 'Galatás', [37.50, 23.45])], poros: [P('GR', 'Póros')] } },
  // Port de Mantoudi (Eubée) → Kymási.
  { key: 'continental|skiathos', source: FH('skiathos') + ' (Volos, Mantoudi, Thessalonique ↔ Skiathos)',
    ports: { continental: [P('GR', 'Vólos'), P('GR', 'Kymási'), P('GR', 'Thessaloníki')], skiathos: [P('GR', 'Skiáthos')] } },
  { key: 'continental|skopelos', source: FH('skopelos') + ' (Volos, Mantoudi, Thessalonique ↔ Skopelos, Glossa)',
    ports: { continental: [P('GR', 'Vólos'), P('GR', 'Kymási'), P('GR', 'Thessaloníki')], skopelos: [P('GR', 'Skópelos'), P('GR', 'Glóssa')] } },
  { key: 'alonissos|continental', source: FH('alonissos') + ' (Volos, Mantoudi, Thessalonique ↔ Patitiri)',
    ports: { alonissos: [P('GR', 'Patitírion')], continental: [P('GR', 'Vólos'), P('GR', 'Kymási'), P('GR', 'Thessaloníki')] } },
  // Port de Kymi → Paralía Kímis.
  { key: 'continental|skyros', source: FH('skyros') + ' (Kymi ↔ Linaria)',
    ports: { continental: [P('GR', 'Paralía Kímis')], skyros: [P('GR', 'Linariá')] } },
  { key: 'greatBritain|orkney', source: 'https://www.northlinkferries.co.uk (Scrabster ↔ Stromness)',
    ports: { greatBritain: [P('GB', 'Scrabster')], orkney: [P('GB', 'Stromness')] } },
  { key: 'greatBritain|shetland', source: 'https://www.northlinkferries.co.uk (Aberdeen ↔ Lerwick)',
    ports: { greatBritain: [P('GB', 'Aberdeen')], shetland: [P('GB', 'Lerwick')] } },
  { key: 'orkney|shetland', source: 'https://www.northlinkferries.co.uk (Kirkwall ↔ Lerwick)',
    ports: { orkney: [P('GB', 'Kirkwall')], shetland: [P('GB', 'Lerwick')] } },
  // Port de Hilf (Masirah) → Maşīrah.
  { key: 'continental|masirah', source: 'https://nfc.mwasalat.om (Shannah ↔ Masirah)',
    ports: { continental: [P('OM', 'Shannah')], masirah: [P('OM', 'Maşīrah')] } },
  { key: 'mayotteGrandeTerre|mayottePetiteTerre', source: 'https://la1ere.franceinfo.fr/mayotte/un-nouveau-tarif-pour-les-tickets-de-barge-a-partir-du-mois-de-mai-1687304.html (Mamoudzou ↔ Dzaoudzi)',
    ports: { mayotteGrandeTerre: [P('FR', 'Mamoudzou')], mayottePetiteTerre: [P('FR', 'Dzaoudzi')] } },
  { key: 'continental|unguja', source: 'https://bakhresa.com/azam-marine/ (Dar es Salaam ↔ Zanzibar)',
    ports: { continental: [P('TZ', 'Dar es Salaam', [-6.82, 39.27])], unguja: [P('TZ', 'Zanzibar')] } },
  { key: 'pemba|unguja', source: 'https://bakhresa.com/azam-marine/ ; https://www.marineradar.com/vessel/mmsi-677070700/azam-sealink-1 (Zanzibar ↔ Mkoani)',
    ports: { pemba: [P('TZ', 'Mkoani')], unguja: [P('TZ', 'Zanzibar')] } },
  { key: 'continental|nosyBe', source: 'https://fr.allafrica.com/stories/202608270372.html ; https://normada.com/178-traversee-vers-nosy-be/1532-toky-bac-2.html (Ankify ↔ Hell-Ville)',
    ports: { continental: [P('MG', 'Ankify')], nosyBe: [P('MG', 'Hell-Ville')] } },
  { key: 'mauritius|rodrigues', source: 'https://www.msclmu.com/services/marine-services/ (Port Louis ↔ Port Mathurin)',
    ports: { mauritius: [P('MU', 'Port Louis')], rodrigues: [P('MU', 'Port Mathurin')] } },
  { key: 'continental|ukerewe', source: 'https://www.temesa.go.tz/news/the-way-water-transport-has-become-a-solution-in-the-lake-zone (Kisorya ↔ Rugezi)',
    ports: { continental: [P('TZ', 'Kisorya')], ukerewe: [P('TZ', 'Rugezi')] } },
  // Luku (Bugala) absent des données → Beta, localité de Bugala la plus proche de la traversée.
  { key: 'continental|ssese', source: 'https://www.kis.co.ug/pages/view-page/Ferry-Services (Bukakata ↔ Luku)',
    ports: { continental: [P('UG', 'Bukakata')], ssese: [P('UG', 'Beta')] } },
  // Débarcadère de Mfangano → Sena.
  { key: 'continental|mfangano', source: 'https://mbitaferryservices.com/about-mbita-ferry/ (Mbita ↔ Mfangano)',
    ports: { continental: [P('KE', 'Mbita')], mfangano: [P('KE', 'Sena')] } },
  { key: 'continental|likoma', source: 'https://www.malawitourism.com/transport/ilala-malawi-shipping-company/ (Nkhata Bay ↔ Likoma)',
    ports: { continental: [P('MW', 'Nkhata Bay')], likoma: [P('MW', 'Likoma')] } },
  { key: 'bioko|continental', source: 'https://www.revistaequato.com/el-ferry-san-valentin-3-suspende-temporalmente-la-ruta-malabo-bata-2/ (Malabo ↔ Bata)',
    ports: { bioko: [P('GQ', 'Malabo', [3.75, 8.78])], continental: [P('GQ', 'Bata')] } },
  // Bandar Pol → Pol-e Angūr (0,3 km).
  { key: 'continental|qeshm', source: 'https://www.sharghdaily.com/بخش-اقتصادی-12/1091407-تردد-در-بنادر-مسافری-قشم-عادی-پایدار-است ; http://mana.ir/fa/news/83282 (Bandar Pol ↔ Laft)',
    ports: { continental: [P('IR', 'Pol-e Angūr')], qeshm: [P('IR', 'Bandar-e Lāft')] } },
  { key: 'continental|kish', source: 'https://www.iscanews.ir/news/1316564 (Charak ↔ Kish)',
    ports: { continental: [P('IR', 'Bandar-e Chārak')], kish: [P('IR', 'Kīsh')] } },
  { key: 'continental|hormuz', source: 'https://sepris.com/mag/traveling-to-hormoz-with-personal-car/ ; https://www.sobhesahel.com/news/124572 (Bandar Abbas ↔ Hormuz)',
    ports: { continental: [P('IR', 'Bandar Abbas')], hormuz: [P('IR', 'Hormoz')] } },
  { key: 'continental|farasan', source: 'https://www.spa.gov.sa/en/N2163485 (Jazan ↔ Farasan)',
    ports: { continental: [P('SA', 'Jizan')], farasan: [P('SA', 'Farasān')] } },
  // Ras Al Ard (Salmiya, absente des données) → Al Bida‘ (6 km) ; port de Failaka → Az Zawr.
  { key: 'continental|failaka', source: 'https://kuwaitalez.com/2448/جدول-رحلات-جزيرة-فيلكا/ (Ras Al Ard ↔ Failaka)',
    ports: { continental: [P('KW', 'Al Bida‘')], failaka: [P('KW', 'Az Zawr')] } },
  { key: 'honshu|sado', source: 'https://www.sadokisen.co.jp/faretables/ (Niigata ↔ Ryōtsu)',
    ports: { honshu: [P('JP', 'Niigata')], sado: [P('JP', 'Ryōtsu-minato')] } },
  { key: 'dogo|honshu', source: 'https://www.oki-kisen.co.jp/fare/ (Shichirui, Sakaiminato ↔ Saigō)',
    ports: { dogo: [P('JP', 'Saigō')], honshu: [P('JP', 'Mihonosekichō-shichirui'), P('JP', 'Sakaiminato')] } },
  // Hakata → Fukuoka ; Izuhara absent des données → Tarugahama (8,8 km, localité de Tsushima la plus proche).
  { key: 'honshu|tsushima', source: 'https://www.kyu-you.co.jp/price/8.html (Hakata ↔ Izuhara)',
    ports: { honshu: [P('JP', 'Fukuoka', [33.60, 130.42])], tsushima: [P('JP', 'Tarugahama')] } },
  { key: 'honshu|iki', source: 'https://www.kyu-you.co.jp/price/8.html (Karatsu ↔ Indōji)',
    ports: { honshu: [P('JP', 'Karatsu', [33.44, 129.97])], iki: [P('JP', 'Ishidachō-indōjiura')] } },
  { key: 'iki|tsushima', source: 'https://www.kyu-you.co.jp/price/8.html (Gōnoura ↔ Izuhara)',
    ports: { iki: [P('JP', 'Gōnourachō-gōnoura')], tsushima: [P('JP', 'Tarugahama')] } },
  { key: 'fukue|honshu', source: 'https://kyusho.co.jp/vehicles/8336 (Nagasaki ↔ Fukue)',
    ports: { fukue: [P('JP', 'Fukuechō')], honshu: [P('JP', 'Nagasaki', [32.75, 129.88])] } },
  { key: 'honshu|nakadori', source: 'https://kyusho.co.jp/vehicle?term=sasebo_kamigoto (Sasebo ↔ Arikawa)',
    ports: { honshu: [P('JP', 'Sasebo')], nakadori: [P('JP', 'Arikawa')] } },
  { key: 'honshu|yakushima', source: 'https://ferryyakusima2.com/timetable (Kagoshima ↔ Miyanoura)',
    ports: { honshu: [P('JP', 'Kagoshima')], yakushima: [P('JP', 'Miyanoura')] } },
  { key: 'honshu|tanegashima', source: 'https://cosmoline.jp/guide (Kagoshima ↔ Nishinoomote)',
    ports: { honshu: [P('JP', 'Kagoshima')], tanegashima: [P('JP', 'Nishinoomote')] } },
  { key: 'honshu|shodoshima', source: 'https://www.shikokuferry.com/route2 (Takamatsu ↔ Tonoshō)',
    ports: { honshu: [P('JP', 'Takamatsu', [34.33, 134.05])], shodoshima: [P('JP', 'Tonoshō')] } },
  { key: 'hokkaido|rishiri', source: 'https://heartlandferry.jp/faretable/ (Wakkanai ↔ Oshidomari)',
    ports: { hokkaido: [P('JP', 'Wakkanai')], rishiri: [P('JP', 'Oshidomari')] } },
  // Kafuka → Kafukamura.
  { key: 'hokkaido|rebun', source: 'https://heartlandferry.jp/faretable/ (Wakkanai ↔ Kafuka)',
    ports: { hokkaido: [P('JP', 'Wakkanai')], rebun: [P('JP', 'Kafukamura')] } },
  { key: 'rebun|rishiri', source: 'https://heartlandferry.jp/faretable/ (Oshidomari ↔ Kafuka)',
    ports: { rebun: [P('JP', 'Kafukamura')], rishiri: [P('JP', 'Oshidomari')] } },
  // hokkaido|okushiri : ports dans corrections.js (quais OpenStreetMap).
  // Régies municipales d'Okinawa : même port de départ (Unten, à Nakijin) pour les deux îles.
  { key: 'izena|okinawa', source: 'https://vill.izena.okinawa.jp/about/access/ (Unten ↔ Nakada)',
    ports: { izena: [P('JP', 'Nakada', [26.93, 127.95])], okinawa: [P('JP', 'Unten', [26.68, 128.0])] } },
  { key: 'iheya|okinawa', source: 'https://www.vill.iheya.okinawa.jp/soshiki/9/1144.html (Unten ↔ Maedomari)',
    ports: { iheya: [P('JP', 'Maedomari', [27.04, 127.97])], okinawa: [P('JP', 'Unten', [26.68, 128.0])] } },
  { key: 'kumejima|okinawa', source: 'http://www.kumeline.com/fare_ticket/ (Naha/Tomari ↔ Kanegusuku)',
    ports: { kumejima: [P('JP', 'Kumejima')], okinawa: [P('JP', 'Naha')] } },
  // Port de Wando → Deolleomeo (0,3 km).
  { key: 'continental|jeju', source: 'https://www.hanilexpress.co.kr/expressFerry/shipfare/shippingFareB.do (Wando ↔ Jeju)',
    ports: { continental: [P('KR', 'Deolleomeo')], jeju: [P('KR', 'Jeju City')] } },
  // Port de Sadong → Ullŭng.
  { key: 'continental|ulleungdo', source: 'https://www.ulcruise.co.kr/www/flight/fare (Pohang ↔ Sadong)',
    ports: { continental: [P('KR', 'Pohang', [36.03, 129.36])], ulleungdo: [P('KR', 'Ullŭng', [37.48, 130.91])] } },
  // Port de Xuwen (Hai'an) → Hai’an ; Xinhai (Haikou) → Xinhaicun.
  { key: 'continental|hainan', source: 'https://m.gmw.cn/2026-01/27/content_1304320237.htm (Xuwen ↔ Haikou Xinhai)',
    ports: { continental: [P('CN', 'Hai’an', [20.28, 110.23])], hainan: [P('CN', 'Xinhaicun')] } },
];

const MARINA = 'https://marina.gov.ph/wp-content/uploads/2026/04/Philippine-Nautical-Highway-Matrix-MAR-2026.pdf';
const PH = (key, label, ports) => ({ key, source: MARINA + ' (' + label + ')', ports });
module.exports.push(
  PH('leyteSamar|luzon', 'Matnog ↔ Allen', { leyteSamar: [P('PH', 'Allen')], luzon: [P('PH', 'Matnog', [12.59, 124.09])] }),
  PH('leyteSamar|mindanao', 'Liloan ↔ Lipata', { leyteSamar: [P('PH', 'Liloan', [10.16, 125.12])], mindanao: [P('PH', 'Lipata')] }),
  PH('negros|panay', 'Dumangas ↔ Banago', { negros: [P('PH', 'Banago')], panay: [P('PH', 'Dumangas')] }),
  PH('cebu|negros', 'Toledo ↔ San Carlos', { cebu: [P('PH', 'Toledo')], negros: [P('PH', 'San Carlos')] }),
  PH('negros|siquijor', 'Dumaguete ↔ Siquijor, Larena', { negros: [P('PH', 'Dumaguete')], siquijor: [P('PH', 'Siquijor'), P('PH', 'Larena')] }),
  PH('mindanao|negros', 'Dumaguete ↔ Dapitan', { mindanao: [P('PH', 'Dapitan', [8.66, 123.42])], negros: [P('PH', 'Dumaguete')] }),
  PH('cebu|leyteSamar', 'Polambato ↔ Palompon', { cebu: [P('PH', 'Polambato')], leyteSamar: [P('PH', 'Palompon')] }),
  PH('bohol|leyteSamar', 'Ubay ↔ Bato', { bohol: [P('PH', 'Ubay')], leyteSamar: [P('PH', 'Bato', [10.33, 124.79])] }),
  PH('guimaras|panay', 'Iloilo ↔ Jordan', { guimaras: [P('PH', 'Jordan')], panay: [P('PH', 'Iloilo')] }),
  PH('luzon|marinduque', 'Lucena ↔ Balanacan', { luzon: [P('PH', 'Lucena')], marinduque: [P('PH', 'Balanacan')] }),
  PH('catanduanes|luzon', 'Tabaco ↔ San Andres, Virac', { catanduanes: [P('PH', 'San Andres'), P('PH', 'Virac')], luzon: [P('PH', 'Tabaco')] }),
  PH('luzon|masbate', 'Pilar ↔ Masbate City', { luzon: [P('PH', 'Pilar', [12.92, 123.67])], masbate: [P('PH', 'Masbate')] }),
  PH('camotes|cebu', 'Danao ↔ Consuelo', { camotes: [P('PH', 'Consuelo')], cebu: [P('PH', 'Danao')] }),
  PH('bantayan|cebu', 'Hagnaya ↔ Santa Fe', { bantayan: [P('PH', 'Santa Fe')], cebu: [P('PH', 'Hagnaya', [11.09, 123.94])] }),
  PH('mindanao|samal', 'Sasa ↔ Babak', { mindanao: [P('PH', 'Sasa')], samal: [P('PH', 'Babak')] }),
  PH('dinagat|mindanao', 'Surigao ↔ San Jose', { dinagat: [P('PH', 'San Jose', [10.01, 125.57])], mindanao: [P('PH', 'Surigao')] }),
  PH('mindanao|siargao', 'Surigao ↔ Dapa', { mindanao: [P('PH', 'Surigao')], siargao: [P('PH', 'Dapa')] }),
  // Isabela City absente des données → San Rafael (1,6 km du port).
  PH('basilan|mindanao', 'Zamboanga ↔ Isabela', { basilan: [P('PH', 'San Rafael', [6.70, 121.97])], mindanao: [P('PH', 'Zamboanga')] }),
  PH('jolo|mindanao', 'Zamboanga ↔ Jolo', { jolo: [P('PH', 'Jolo')], mindanao: [P('PH', 'Zamboanga')] }),
  PH('luzon|tablas', 'Batangas ↔ Odiongan', { luzon: [P('PH', 'Batangas', [13.76, 121.06])], tablas: [P('PH', 'Odiongan')] }),
  PH('lubang|luzon', 'Manila ↔ Tilik', { lubang: [P('PH', 'Tilik')], luzon: [P('PH', 'Manila', [14.60, 120.98])] })
);
